### ISSUE TITLE
Firebase Authentication - Invalid token

### ISSUE THREAD

**Issue by aiswaryaqaptive** [firebase/firebase-ios-sdk#10052]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a GitHub issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.4.1
  * Firebase SDK version: 8.10.0
  * Installation method:  CocoaPods 
  * Firebase Component: _____ Auth
  * Target platform(s): All 

#### Steps to reproduce:

Login the application using firebase authentication. 
Logout from App 
Login Again 
Firebase verifyPhone number function returns error "Invalid token"

**Comment by rizafran** [comment]
Thanks for reporting, @aiswaryaqaptive. Could you confirm if you're using phone auth to sign in to your app? Note that this issue usually happens when the APNs device token provided is either incorrect or does not match the private certificate uploaded in the Firebase Console. With this, could you try the following troubleshooting steps:
- Check if the bundle ID in your app is the same as the bundle ID registered in Firebase Console (Check "Project Settings > Your App" for the bundle ID registered).
- Check if the [uploaded APNS certificate](https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications) is correct and up-to-date.
- Download an updated [GoogleService-Info.plist](https://firebase.google.com/docs/ios/setup#add-config-file) and add it to your app.
- Verify the APNs device token is not expired.
- Verify your App ID and Team ID are [setup correctly](https://support.google.com/firebase/answer/9137750?hl=en).

Let me know how it goes.

**Comment by aiswaryaqaptive** [comment]
I am using phone auth for signing in to app. Where we are using APNs device token? Any token is sending from iOS App to the firebase server? For my Application signing is working fine for the first time. After signing out its not able to signing with FirebaseAuth . Its showing error "Invalid token".

**Comment by rizafran** [comment]
@aiswaryaqaptive I see. Our [doc](https://firebase.google.com/docs/auth/ios/phone-auth#appendix:-using-phone-sign-in-without-swizzling) states that APNs device token is usually used in phone sign-in without swizzling as you should explicitly pass the APNs device token, push notifications, and the custom scheme redirect URL to Firebase Authentication. Additionally, if you're using [silent API notification method](https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications), you need to enable APN notifications and provide the APNs authentication key in the console.

If you're not using these methods, could you provide a sample app that reproduces the issue?

**Comment by aiswaryaqaptive** [comment]
Thank you for responding immediately. I have fixed the issue . Issue is due to incorrect GoogleService-Info.plist .
