### ISSUE TITLE
Phone auth

### ISSUE THREAD

**Issue by alexanderkhitev** [firebase/firebase-ios-sdk#1007]
Hello! I use FirebaseUI / Phone pod to register to the application, I entered the number, but the SMS did not come, I pressed the "Resend sms" button several times, but there was no result. After a few minutes, several sms came at once, but before that I had already restarted the application, after trying to log in again, I had the message "This phone number has been used too many times". Is there any way to turn it off for tests? How long does this warning go?

**Comment by protocol86** [comment]
Hi alexanderkhitev,

It seems like your issue is related to FirebaseUI-iOS which is a different repository. Could you move the issue to [the Firebase UI repo](https://github.com/firebase/FirebaseUI-iOS)? Can you also add all details about the error you encountered when trying to sign in again including the `code`, `description` and the `userInfo` if available.
