### ISSUE TITLE
Sign with apple nonce error

### ISSUE THREAD

**Issue by jesus-mg-ios** [firebase/firebase-ios-sdk#10462]
### Description

Sometimes when user tries to login/signin with apple, an error is experimented. The code used is the code published on Firebase documentation.
Thanks in advance

`ERROR_MISSING_OR_INVALID_NONCE`
`Code: 17094`
`Domain: FIRAuthErrorDomain.FIRAuthErrorDomain, 17094`
`LocalizedDescription`
`The nonce in ID Token "_______________________________________________" does not match the SHA256 hash of the raw nonce "___________________________" in the request.`

### Reproducing the issue

Random when a user tries a login or signing

### Firebase SDK Version

9.6.0

### Xcode Version

13.4.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### Relevant Log Output

```shell
----
```

### If using Swift Package Manager, the project's Package.resolved

We use another tool that under the hood use SPM

### If using CocoaPods, the project's Podfile.lock

---

**Comment by rizafran** [comment]
Thanks for reporting this, @jesus-mg-ios. This issue usually happens when you're passing an invalid nonce. With this, make sure that you're passing the correct `rawNonce`. You may also check the [doc](https://firebase.google.com/docs/auth/ios/apple#sign_in_with_apple_and_authenticate_with_firebase) for more info. If the issue persists, please provide an [mcve](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by jesus-mg-ios** [comment]
I'm sure, the error is random and I'm using the code that appears on firebase doc.
Thanks in advance. I really appreciate your hard work

**Comment by jesus-mg-ios** [comment]
Okay, I'm gonna try it, but I've already said, it happens randomly in clients. I mean the number of times of a sign-in or sign-up is made on production is more than I can test with the quick app start ... Even I have to use a real Apple ID ... and it makes that if the error happens in the signup process, catching it with a user test is gonna be very difficult.

**Comment by jesus-mg-ios** [comment]
@rizafran I couldn't reproduce it.
