### ISSUE TITLE
iPhone 14 / 14 Pro models not appears on Analytics Dashboard

### ISSUE THREAD

**Issue by dabaicaifen** [firebase/firebase-ios-sdk#10528]
### Description

Using Swift Package Manager.
Firebase SDK version is 10.2.0. 

The Analytics Dashboard and real-time DebugView cannot show iPhone 14 Pro models. 

### Reproducing the issue

The issue can be reproduced every time by simply setup Firebase Analytics.

### Firebase SDK Version

10.2.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @dabaicaifen, it seems that your issue is most likely on the backend side. With this, please file a ticket through our [Firebase support channel](https://firebase.google.com/support) so that the team will be able to assist you better since they have a visibility in your project details. That being said, I'll be closing this issue now.
