### ISSUE TITLE
AppCheck not working on new iPhone 14 

### ISSUE THREAD

**Issue by ian-sayles** [firebase/firebase-ios-sdk#10561]
### Description

When AppCheck was released we updated our app to use it, and its been working perfectly.

But just recently when some of our customers have upgraded their phones to the new iPhone14 when they run our app it does not show any data from Firestore, when on older phone it did.

The app as min 15.0.0 iOS set, and don't think its an iOS version issue,  for older phones running iOS 16.1.2 work ok.

Checking the App Check API for Cloud Firestore it does show "unverified: invalid requests" when the user run our app.

What is strange if I connect the iPhone to my computer and run the app from Xcode it does work ok.
This is using a different firebase project than the production app from the App Store, but both projects are configured the same.

Does AppCheck support the latest phones from Apple?  

### Reproducing the issue

Code in app

let providerFactory = YourAppCheckProviderFactory()
AppCheck.setAppCheckProviderFactory(providerFactory)
       
class YourAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
  func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
    return AppAttestProvider(app: app)
  }
} 
       

### Firebase SDK Version

9.6.0

### Xcode Version

14.1

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @ian-sayles, sorry for the trouble. Just to confirm, you're able to reproduce the following behavior:
- Verify that AppCheck **does not** work when running your app on physical iPhone 14
- Verify that AppCheck **does** work when deploying an app (that uses a different firebase project) onto the **same** iPhone 14 via connecting it your computer

**Comment by ian-sayles** [comment]
Verify that AppCheck does not work when running your app on physical iPhone 14

- Yes, when they sign into the app on a iPhone they can't view any data from FireStore
- Same login on an older phone they can see their data in FireStore.
- We have also just purchased a new iPhone 14  (not a Pro model) and with a different account to our customer and experienced the same issue, on any other phone can see Firestore data, on the iPhone14 nothing.

Verify that AppCheck does work when deploying an app (that uses a different firebase project) onto the same iPhone 14 via connecting it your computer
- Yes, when using our new iPhone14, data from FireStore is shown with no issues.

**Comment by ncooke3** [comment]
Thanks, have you tried running each scenario with debug logging on? You can set `-FIRDebugEnabled` as a launch argument in the scheme editor.

I'd be curious if this help surface what the difference is between the two scenarios.

**Comment by ian-sayles** [comment]
I have switched on the -FIRDebugEnabled and also changed the app to use the production Google-Service-Info file so it is the same as the app from the app store.
When debug the app,  we can see data from the Firestore database on the iPhone 14, as we could before when using the development firebase project.

So the issue seems to be when using the released app from the App Store on a iPhone 14.  
Is there anywhere to view debug in the Google Cloud console for App Check?

**Comment by ncooke3** [comment]
Thanks @ian-sayles. There isn't  anywhere to view debug info in the console for App Check.

Just to verify, when you said:
> Verify that AppCheck does work when deploying an app (that uses a different firebase project) onto the same iPhone 14 via connecting it your computer
>
>Yes, when using our new iPhone14, data from FireStore is shown with no issues.

Were you using debug tokens or a real attestation provider?

**Comment by ian-sayles** [comment]
When the phone is connected to my computer it shows data from Firestore when using either my development or production firebase projects.

The same phone when using the app download from the App Store, does not show any data from Firestore.

The following is the code for AppCheck:

let providerFactory = YourAppCheckProviderFactory()
AppCheck.setAppCheckProviderFactory(providerFactory)
        
class YourAppCheckProviderFactory: NSObject, AppCheckProviderFactory {
  func createProvider(with app: FirebaseApp) -> AppCheckProvider? {
    return AppAttestProvider(app: app)
  }
}

**Comment by ncooke3** [comment]
I think we should see what's being logged from the release build since that's where it's failing.  

First, see [this](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs#Access-device-console-logs) guide for viewing app's logs from the Console.app. Ideally, we should seem some error messages from the AppCheck SDK. Try this first with the release build you are able to repro the failure with.

If this doesn't surface anything, we can increase the Firebase logger level:

- Put the below line right **before** your call to `FirebaseApp.configure()`:
```swift
FirebaseConfiguration.shared.setLoggerLevel(.max)
```
- Then create a release build ([doc](https://developer.apple.com/documentation/xcode/testing-a-release-build)) to and run it while plugged into your machine again

**Comment by michaelscampbell** [comment]
I've noticed that Firebase's implementation of AppCheck does not correctly handle reinstallation. 

Per Apple's DeviceCheck documentation: "The keys that you generate remain valid through regular app updates, but don’t survive app reinstallation, device migration, or restoration of a device from a backup. In these cases, you need to start the process from the beginning and generate a new key."

https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity

**Comment by ncooke3** [comment]
Thanks @michaelscampbell, could you explain to me why AppCheck does not correctly handle reinstallation?

**Comment by michaelscampbell** [comment]
@ncooke3 We saw issues with AppCheck for users of our own app and during our investigation we concluded the problem lies with the scenarios highlighted in the quoted Apple documentation. In particular, (1) device migration (an example is an issue we saw with a user migrating from iPhone 13 to iPhone 14) and (2) restoration (an example is an issue we saw with an iPhone 8 user restoring an offloaded app).

Since Ian mentioned his issue occurred with existing users who upgraded their phones, it sounded to me like it could be the device migration issue that we had seen. Naturally, I might be wrong. Since installing from Xcode puts the app on the phone in a different way than device migration and restoration that could explain why installing from Xcode works for Ian. We saw that Xcode installs did NOT have a problem with AppCheck -- the bug was only tickled by migration and restoration.

**Comment by ian-sayles** [comment]
I have today just checked the app on the same iPhone that was not working earlier in the month and it is now working ok.
We then upgraded the phone to the latest iOS 16.2 and reinstalled the app and again it work ok.

We have App Check set  "Token time to live" to 2 days, could this cause the issue we encountered?

I would assume new tokens will be created on each devices, but are they copied from other devices.

The reason we set it to 2 days, during testing we would get a lot of Unverified warnings, which after increasing the time to live they disappeared.

**Comment by ncooke3** [comment]
Thank you @michaelscampbell for sharing-- that's really good to know! I agree that it could be related here.

@ian-sayles, that's good that it is now working. Since there were no SDK changes, it makes me think that it could be even more an Apple issue. I don't _think_ the TTL would cause this type of issue, but I'm going to check with the AppCheck backend team to verify for you.

**Comment by sjpickup** [comment]
I have had what I think is the same problem with my app, which uses App Attest but not Device Check. Users complain that it isn't working after they restore from an icloud backup onto a new device (not just iPhone 14). Deleting and reinstalling the app solves the problem.

Reproducing it today I find that in after reinstalling an iPhone 8 plus from an iCloud backup, within AppCheck.token(), FIRAppAttestProvider.attestionState() passes through all checks and returns a state of FIRAppAttestAttestationStateKeyRegistered, then ultimately failing on call to DCAppAttestService.attestKey() returning DCError.invalidKey, which is documented by Apple to occur "for a key that’s already been attested".

After reinstalling the app, FIRAppAttestProvider.attestionState() returns state of FIRAppAttestAttestationStateSupportedInitial, and ulitmately succeeds.

Without analysing fully, I am guessing there is some issue with state retained via NSUserDefaults (which would be retained across iCloud restore) vs the keychain (which would not be).

I have yet to confirm but a hacky workaround would be, upon seeing this failure, to remove relevant entries from NSUserDefaults and call AppCheck.token() again.

This all seems consistent with what @michaelscampbell was saying above. I look forward to a fix. Let me know if you need more info.

**Comment by ncooke3** [comment]
Hi @sjpickup, question regarding your repro notes.

> Reproducing it today I find that in after reinstalling an iPhone 8 plus from an iCloud backup, within AppCheck.token(), FIRAppAttestProvider.attestionState() passes through all checks and returns a state of FIRAppAttestAttestationStateKeyRegistered, 

Yep, I understand this part.

> then ultimately failing on call to DCAppAttestService.attestKey() returning DCError.invalidKey, which is documented by Apple to occur "for a key that’s already been attested".

Do you recall how your repro's execution flow got to here? I don't see clear path if `FIRAppAttestAttestationStateKeyRegistered` was returned previously. It seems that the below two states would get us there:
https://github.com/firebase/firebase-ios-sdk/blob/6d9f33435a81d07ba21017be8054e0ca57408fb4/FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m#L229-L233

**Comment by ncooke3** [comment]
@sjpickup, got it. 

But do you recall how the state transitioned from `FIRAppAttestAttestationStateKeyRegistered` to `FIRAppAttestAttestationStateKeyRegistered`?

**Comment by sjpickup** [comment]
No I don’t, but will run it again within the next day or two to check.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sjpickup** [comment]
OK @ncooke3, I have checked it again. This is the relevant code in `FIRAppAttestProvider.attestionState()`:

https://github.com/firebase/firebase-ios-sdk/blob/6d9f33435a81d07ba21017be8054e0ca57408fb4/FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m#L434-L451

On the first run after restoring a backup, both checks 2 and 3 pass (meaning both `UserDefaults` and keychain entries are present), thus line 450 returns `FIRAppAttestAttestationStateKeyRegistered`, leading to `DCAppAttestService.attestKey()` returning `DCError.invalidKey`.

The workaround/recovery is to **delete** and reinstall the app, which clears `UserDefaults`, thus check 2 fails and line 438 returns `FIRAppAttestAttestationStateSupportedInitial`.

Perhaps the misunderstanding here is I didn't explicitly say the user **deletes** the app and reinstalls to fix things.

**Comment by ncooke3** [comment]
Thanks @sjpickup, that clarification does help. I do have one followup question though–– how does `FIRAppAttestAttestationStateKeyRegistered` lead to `DCAppAttestService.attestKey()` being executed? 

Because I'm not seeing how it happens. For example, the `DCAppAttestService.attestKey()` call happens in `- [FIRAppAttestProvider initialHandshakeWithKeyID:]` on line **258**.

https://github.com/firebase/firebase-ios-sdk/blob/f567ed9a2b30e29159df258049a9c662c517688e/FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m#L246-L259


And this code path does not run for the `FIRAppAttestAttestationStateKeyRegistered` state (line **229** and **230**):

https://github.com/firebase/firebase-ios-sdk/blob/f567ed9a2b30e29159df258049a9c662c517688e/FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m#L229-L233

**Comment by andrewheard** [comment]
We added a [fix](https://github.com/firebase/firebase-ios-sdk/pull/11986) and additional [debug info](https://github.com/firebase/firebase-ios-sdk/pull/11956) in Firebase 10.17.0. When you get a chance to upgrade to `10.17.0+` ([`10.18.0` released](https://github.com/firebase/firebase-ios-sdk/releases/tag/10.18.0) today), please let us know if this resolves the issue for you and, if not, any new debugging info you can provide.
