### ISSUE TITLE
On iOS only last sent data message is retrieved when the app back online

### ISSUE THREAD

**Issue by Zeus64** [firebase/firebase-ios-sdk#10569]
### Description

When I send via http V1 several data messages to my iOS app while it is in background, then when **i put back my app online** I receive only **the very last data message** in application:didReceiveRemoteNotification:fetchCompletionHandler:

In legacy http all the data messages was queued and I could retrieve them by calling setShouldEstablishDirectChannel and listening messagingDidReceiveMessage

How in http V1 can I retrieve when the app is back online all data messages that was sent when the app was in background ? 

### Firebase SDK Version

10.2.0

### Xcode Version

delphi

### Installation Method

Zip

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Hi @Zeus64, thanks for reporting. Since `shouldEstablishDirectChannel` method is already deprecated in v1, FCM contacts the APNs to deliver the notifications, and with this, we don't have a control on keeping track of the pending messages. Also, as described [here](https://firebase.blog/posts/2019/02/life-of-a-message#ios-message-delivery-factor): 
> After APNs accepts the message request, APNs is responsible for delivering the notification to the device. In this case, FCM on its own does not collect any delivery information and messages sent through APNs are subject to the same types of message delivery factors as other APNs messages. 

If you want to send a test notification, you may try making a call directly through APNs as explained [here](https://firebase.blog/posts/2017/01/debugging-firebase-cloud-messaging-on#4-make-a-call-directly-through-apns). I'll be closing this ticket for now, but feel free to comment if you have any questions.
