### ISSUE TITLE
Firestore listener on iOS not getting fired when query params include a field that's set using FieldValue.serverTimestamp

### ISSUE THREAD

**Issue by nrkrishna** [firebase/firebase-ios-sdk#10964]
### Description

We ran into a peculiar situation in our use of Firestore on iOS. We have a document that has a `lastUpdated` field which is being set with `FieldValue.serverTimestamp()`. We have an active listener that is looking for all documents more recent than the last update time it knows about. The issue we are running into is that when a document is written to the local cache with lastUpdated as `FieldValue.serverTimestamp()` and the device is **offline**, the active listener doesn't fire. 

When the device is **online**, its behaving exactly as written about in Doug Stevenson's medium [post](https://medium.com/firebase-developers/the-secrets-of-firestore-fieldvalue-servertimestamp-revealed-29dd7a38a82b), where `lastUpdated` is a null value and then populates as expected once the document is written to the cloud. We are expecting a similar behavior when the device is offline, but that doesn't seem to be the case.

Is it a bug or working as intended? If the latter, much appreciate any suggestions on how we can handle for the offline scenario.

Thanks

### Firebase SDK Version

10.6.0

### Xcode Version

14.2

### Installation Method

CocoaPods

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

**Comment by cherylEnkidu** [comment]
Hi,
Is the `active listener` you mentioned `onSnapShot` ? Or it is some other class you create? If it is `onSnapShot`, can I rephrase your request as you want the `onSnapShot` monitor the document field changes in cache?

**Comment by nrkrishna** [comment]
@cherylEnkidu yes, it's onSnapshot specifically the `addSnapshotListener` call in iOS. Yes, rephrasing the request sounds good to me. Thanks

**Comment by cherylEnkidu** [comment]
Hi,

Thanks for your clarification! This is a feature request inside our backlog. Unfortunately, currently firestore does not have a work around for that. The reason is snapshot listener is a feature lives inside server and we don't have the similar logic in SDK. I added this ticket as the support evidence inside the internal tracking ticket (b/169688224) to help us better plan for the roadmap. Thank you again for filling up this ticket.

**Comment by nrkrishna** [comment]
@cherylEnkidu Understood - thanks for the quick reply. We'll find a workaround for now.

**Comment by cherylEnkidu** [comment]
Hi @nrkrishna ,

Sorry I misunderstood something here previously. The SDK should be able to raise listener from changes when offline. If the firing failed, one possible reason is the document doesn't exist in the cache. In this case, `update` will try to `get` from server first, then the operation fails.

Some changes might be helpful:
1. use a less eager garbage collector, e.g. levelDB
2. use `set` with `merge` instead of `update`, so it wouldn't try fetch from server first

Please let me know if you need more help
