### ISSUE TITLE
AppCheck with AppAttest getToken producing occasional com.apple.devicecheck.error Code=2

### ISSUE THREAD

**Issue by mattpis-cgi** [firebase/firebase-ios-sdk#11264]
### Background:
We have rolled out app check to prod over a month ago and we use appcheck to secure our back end.
We dont use it in combination with other firebase frameworks. Our application min iOS version is 15.0. Firebase version is 10.6
For most of our users, AppCheck get token succeeds. We are experiencing issues with small number of users, approximately 10-5%.

### Issues:
1: Most of our getToken failures result with error:
```
error Domain=com.apple.devicecheck.error Code=2 
```
This error is produced by apples attestation API. Apple docs about error:
https://developer.apple.com/documentation/devicecheck/dcerror/code/invalidinput

Description says:
```
An error code that indicates when your app provides data that isn’t formatted correctly.
```

2. Occasionally we receive:
```
 Error Domain=com.apple.devicecheck.error Code=3 
```
This error is also produced by apples attestation API. Apple docs about error:
https://developer.apple.com/documentation/devicecheck/dcerror/code/invalidkey
Description says:
```
You receive this error if something goes wrong with generating, retrieving, or using an App Attest cryptographic key, when:
- we attestKey
- we generateAssertion
- app Attest service rejects the key.
```

### Investigation:
We did try to reproduce with no luck on multiple devices. We tried:
- change region, time and date.
- multiple iOS versions.
- use iCloud keychain storage to retain its data between installations, since framework uses it as a storage.

Non of the above did not help in reproducing the issue.

We are looking for clues and we ask for help to solve this.

### Reproducing the issue

Hard to reproduce. We failed to reproduce it.

### Firebase SDK Version

10.1

### Xcode Version

14.1

### Installation Method

Zip

### Firebase Product(s)

App Check

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ncooke3** [comment]
Hi @mattpis-cgi, thanks for reporting and sorry for the trouble.

Have you tried reproducing when re-installing the app on a _different_ device? 

So something like: 
1. install app on device 1 while logged into an iCloud account 
2. run the app and confirm an app check token is successfully created/used
3. now, install app on device 2 and log into the same iCloud account
4. run the app and confirm an app check token is successfully created/used

This could help rule out that users re-installing your app on a new device aren't the ones affected.

**Comment by mattpis-cgi** [comment]
Hi @ncooke3,
thank you for your response and help. 
I have tested above scenario multiple times, I did not reproduce an issue.

On top of that I also re-do those tests with keychain sharing to iCloud account enabled. We are able to see that before our attestation attempt the keychain appcheck data from other device is present in keychain. This is not casing the issue and we are able to getToken from appcheck.

You said:
```
This could help rule out that users re-installing your app on a new device aren't the ones affected.
```
How would the new device installation affect the success/failure of attestation ?

What could be the next steps in reproducing / solving this issue?

**Comment by newbstudent** [comment]
Having sudden issues with AppCheck myself....I posted this on stackoverflow, reposting here incase it is of any assistance

-----
AppCheck suddenly sending invalid tokens for legitimate iOS app instances for Firebase requests

Losing my mind here because the app was working great before my testers and I took a few weeks off of beta testing and now we're testing again and the app is failing and it is tied to AppCheck.  Forget exact dates but say worked for all of April and not now, May 12-18 we started trying to test again with minor code updates for the UI, no changes at all to do with AppCheck.  If I set AppCheck to UNenforced in the Firebase console, everything works perfectly and I see the "Unverified: Invalid requests" coming in from *SOME* of my app instances while others are still sending proper verified requests.  All the same version of the app (as in exact same build number in TestFlight).

Was using Firebase iOS SDK 10.3.0 when things were working, when things started failing tried updating to latest version (10.9.0) with no resolution.

Using AppAttest as the attestation provider (NOT using DeviceCheck)

**Scenario where AppCheck IS still working correctly:**

release mode:

Three of my personal devices that are registered to my Apple Developer account are all working (i.e. verified requests) when running the app build distributed via Test Flight (i.e. release mode)

- iOS 15.6, 15.7.* & iOS 16 (16.1 up to 16.4.1 (a) and all versions in between)

- I was using registered debug tokens for these devices during development (with AppCheck set to enforce) when I was running debug builds but have since deleted these tokens, as in there are no registered debug tokens at all.

debug mode:

Registering debug tokens still works for debug builds but of course this isn't likely relevant to my problem

**Scenario where AppCheck is NOT working correctly anymore:**

Any release mode app instance running on my testers' devices, distributed via TestFlight.  Testers were using iOS 16.4 (when things were working), now they are on 16.4.1 and 16.4.1 (a) .  I do NOT think it is the iOS version though since my personal devices running 16.4.1 and 16.4.1 (a) are just fine.

So did something change on Apple's end? Firebase's end?  Something to do with my personal devices being registered to my Apple Developer account???  Something to do with previously using debug tokens for these devices even though they are deleted now? I don't see a large number of posts about App Attest or App Check failing and imagine if this was a widespread issue it would be all over the place, or am I one of the few people using it???

Fortunately I can still test and publish the app with AppCheck unenforced since I have extensive Firebase security rules in place to protect all user data (which is end to end encrypted anyway) but would still run the risk of an authenticated user hammering the server and bankrupting the company, so ok risk in the short term but need to get it sorted in next few months.

Have tried having testers delete the app, reinstall from TestFlight, no luck.  Creating a new build and uploading it to TestFlight to see if that resolved it when everyone updated, no luck.

**Comment by mattpis-cgi** [comment]
@newbstudent please share stack overflow link.

**Comment by newbstudent** [comment]
> @newbstudent please share stack overflow link.

it was downvoted and closed since I wasn’t asking a specific coding question, so no useful replies there, but here it is:

https://stackoverflow.com/questions/76285673/appcheck-suddenly-sending-invalid-tokens-for-legitimate-ios-app-instances-for-fi

I’ve given up for now on using AppCheck and figuring out the issue, will deploy app without enforcing and just hope it resolves itself.  I’ll notice if it’s working again due to appcheck monitor mode statistics. Only backend protection I have is all of my Firestore and Storage security rules require an authenticated user as a minimum requirement.

**Comment by ian-sayles** [comment]
I had issues with AppCheck not working earlier this year,  https://github.com/firebase/firebase-ios-sdk/issues/10561

Did like @newbstudent and switched it off, not ideal,  but it does not look when good when user install your app and its broken from day one.

**Comment by marcinreliga** [comment]
I am facing similar issues as mentioned above. Specifically I get some percentage of users that are failing this call:
```
AppCheck.appCheck().token(forcingRefresh: forcingRefresh) { [weak self] result, error in
    ...
}
```

with the following error:

`com.firebase.appCheck Code=0` (and underlying error from Apple: `com.apple.devicecheck.error Code=2`)

Most of those users were able to get the token at least once, at some point in the past. I store those tokens locally, so I'm able to log their expiration date, and in many cases they expired months ago. That would mean that `AppCheck.appCheck().token(...)` is failing for those users repeatedly since then.

I have found a way to reproduce the `com.apple.devicecheck.error Code=2`, however only by using the `DCAppAttestService` directly (not via Firebase AppCheck). It happens in the following scenario:
1. Generate the key (`DCAppAttestService.shared.generateKey(...)` and store the `keyID` in the keychain.
2. Attest the key (`DCAppAttestService.shared.attestKey(...)`). <-- works fine at this point
3. Delete the app and install it again.
4. Attest the key again, using the key that was generated for the previous app installation.

In the above scenario the fix that works for me is to generate the key once again, for the current app installation, and then use that new key for attestation.

I wonder if the same error (but via Firebase AppCheck) might be caused by the same (or similar) scenario? And if so, how to make it work?

**Comment by neugartf** [comment]
Hey @ncooke3! 
Is this being checked on? 🙇

**Comment by SamC-Apadmi** [comment]
I'm also getting this :(

**Comment by lumenlunae** [comment]
We have one member that is unable to access our system and gets authentication errors when AppCheck is enforced, but no one else is. 

The error from phone number sign in is:
```
"error": "Error Domain=FIRAuthErrorDomain Code=17999 \"An internal error has occurred, print and inspect the error details for more information.\" UserInfo={FIRAuthErrorUserInfoNameKey=ERROR_INTERNAL_ERROR, NSLocalizedDescription=An internal error has occurred, print and inspect the error details for more information., NSUnderlyingError=0x283af9f20 {Error Domain=FIRAuthInternalErrorDomain Code=3 \"(null)\" UserInfo={NSUnderlyingError=0x283a0ba80 {Error Domain=com.google.HTTPStatus Code=401 \"(null)\" UserInfo={data={length = 284, bytes = 0x7b0a2020 22657272 6f72223a 207b0a20 ... 220a2020 7d0a7d0a }, data_content_type=application/json; charset=UTF-8}}, FIRAuthErrorUserInfoDeserializedResponseKey={\n    code = 401;\n    errors =     (\n                {\n            domain = global;\n            message = \"Firebase App Check token is invalid.\";\n            reason = unauthorized;\n        }\n    );\n    message = \"Firebase App Check token is invalid.\";\n    status = UNAUTHENTICATED;\n}}}}"
```

I don't know how to add debugging logs around the App check portion, but I wonder if this is similar? Is there something in the App Check token creation that's not working correctly for our team member (but it's fine for everyone else) ?

**Comment by gchux** [comment]
> I am facing similar issues as mentioned above. Specifically I get some percentage of users that are failing this call:
> 
> ```
> AppCheck.appCheck().token(forcingRefresh: forcingRefresh) { [weak self] result, error in
>     ...
> }
> ```
> 
> with the following error:
> 
> `com.firebase.appCheck Code=0` (and underlying error from Apple: `com.apple.devicecheck.error Code=2`)
> 
> Most of those users were able to get the token at least once, at some point in the past. I store those tokens locally, so I'm able to log their expiration date, and in many cases they expired months ago. That would mean that `AppCheck.appCheck().token(...)` is failing for those users repeatedly since then.
> 
> I have found a way to reproduce the `com.apple.devicecheck.error Code=2`, however only by using the `DCAppAttestService` directly (not via Firebase AppCheck). It happens in the following scenario:
> 
> 1. Generate the key (`DCAppAttestService.shared.generateKey(...)` and store the `keyID` in the keychain.
> 2. Attest the key (`DCAppAttestService.shared.attestKey(...)`). <-- works fine at this point
> 3. Delete the app and install it again.
> 4. Attest the key again, using the key that was generated for the previous app installation.
> 
> In the above scenario the fix that works for me is to generate the key once again, for the current app installation, and then use that new key for attestation.
> 
> I wonder if the same error (but via Firebase AppCheck) might be caused by the same (or similar) scenario? And if so, how to make it work?

this seems plausible; @marcinreliga have you tried using `resetAttestation` [1] [2] on `AppCheckProvider`?
atm, it is only called if they SDK gets an `HTTP/403` from the AppCheck API [3]

___

[1]: https://github.com/firebase/firebase-ios-sdk/blob/10.14.0/FirebaseAppCheck/Sources/AppAttestProvider/FIRAppAttestProvider.m#L360

[2]: https://github.com/firebase/firebase-ios-sdk/blob/10.14.0/FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestArtifactStorage.m#L94-L100

[3]: https://github.com/firebase/firebase-ios-sdk/blob/10.14.0/FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestArtifactStorage.m#L118-L121

**Comment by andrewheard** [comment]
We added a [fix](https://github.com/firebase/firebase-ios-sdk/pull/11986) and additional [debug info](https://github.com/firebase/firebase-ios-sdk/pull/11956) in Firebase 10.17.0. When you get a chance to upgrade to `10.17.0+` ([`10.18.0` released](https://github.com/firebase/firebase-ios-sdk/releases/tag/10.18.0) today), please let us know if this resolves the issue for you and, if not, any new debugging info you can provide.

**Comment by paulb777** [comment]
See #12629 for an ongoing related discussion
