### ISSUE TITLE
[Firebase 11]:  Firebase App Check's limited use token API as required

### ISSUE THREAD

**Issue by ncooke3** [firebase/firebase-ios-sdk#11284]
### Description

The `FirebaseAppCheckInterop` contains an API for getting limited-use tokens. This was introduced in 10.10 and was marked as optional for backwards compatibility purposes. The `@optional` attribute can now be removed for a major version breaking change.

### API Proposal

In `FirebaseAppCheck/Interop/FIRAppCheckInterop.h`:
```diff 
-  // MARK: - Optional API
- 
-  @optional

 /// Retrieve a new limited-use Firebase App Check token
 - (void)getLimitedUseTokenWithCompletion:(FIRAppCheckTokenHandlerInterop)handler
    NS_SWIFT_NAME(getLimitedUseToken(completion:));
```

### Firebase Product(s)

App Check

**Comment by mikehardy** [comment]
Hey there 👋 - @paulb777 and @ncooke3 I have a question about this that might affect the API shape of the limited use token functionality

Here's the context:

For dynamic language environments (react-native at least, Flutter also I presume) it is difficult for the user to configure App Check as a system because App Check expects to be initialized at app startup and never changed after. This configuration constraint is a window that closes during an app lifecycle phase that is prior to the dynamic language environment being up and available though and means that by the time the dynamic language environment knows what it wants to configure and could do so, it is too late to do so for the underlying SDK's constraints.

I have worked around this by implementing a [custom provider](https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/ios/RNFBAppCheck/RNFBAppCheckProvider.m) and [custom provider factory](https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/ios/RNFBAppCheck/RNFBAppCheckProviderFactory.m) that stores a reference to one of the concrete underlying providers from the SDKs, and I have library consumers [initialize our module](https://rnfirebase.io/app-check/usage#initialize), then [configure/install our dynamically delegating custom provider](https://rnfirebase.io/app-check/usage#configure-a-custom-provider) for usage.

Now when the dynamic language environment is available, they can configure the custom provider the way they want (perhaps setting the debug factory up, with a debug token...) and install it - all the web/android/ios API disjointedness happily smoothed over and dynamically configurable - something that was *very* difficult to do with the app-check module unlike all the other modules.

This has been working really well, it was an innovation that finally made app check user friendly for react-native-firebase.

Why am I commenting here? Unless the [getLimitedUseTokenWithCompletion](https://firebase.google.com/docs/reference/ios/firebaseappcheck/api/reference/Classes/FIRAppCheck#/c:objc(cs)FIRAppCheck(im)limitedUseTokenWithCompletion:) method is on the [AppCheckProvider interface](https://firebase.google.com/docs/reference/ios/firebaseappcheck/api/reference/Protocols/FIRAppCheckProvider.html), I can not use that type (as I do with [getTokenWithCompletion](https://firebase.google.com/docs/reference/ios/firebaseappcheck/api/reference/Protocols/FIRAppCheckProvider.html#/c:objc(pl)FIRAppCheckProvider(im)getTokenWithCompletion:)...) to dynamically and in a provider-agnostic way in my custom provider, so I cannot proxy the call through and implement this API.

This is a current concern for me as I attempt to shepherd through a community PR to implement it: https://github.com/invertase/react-native-firebase/pull/7424

If it seems reasonable to add the limited use token API to the interface and you can do so then I'll propose the same thing over on firebase-android-sdk for [their similar interface](https://firebase.google.com/docs/reference/android/com/google/firebase/appcheck/AppCheckProvider)

**Comment by paulb777** [comment]
+ @andrewheard who may also have some thoughts

**Comment by mikehardy** [comment]
I should check the source more carefully! Here I was looking at the docs, but apparently it is there, just marked optional - https://github.com/firebase/firebase-ios-sdk/blob/8fe1ddc5f16957da5b2dc8b1dee90e5bd85205ff/FirebaseAppCheck/Sources/Public/FirebaseAppCheck/FIRAppCheckProvider.h#L35-L47

appears to work well when I call it (and call it with the correct name...)

Not seeing "consumed" in there as a claim but that may be added by verify() in admin-sdk, that's just on me to test. I need to look more closely at firebase-android-sdk then

My general comments on the difficulty of configuration + smoothing over API disjointedness from native SDKs to dynamic language environments are still on point, but my custom provider shim may be able to paper over this new API as well without much issue

**Comment by paulb777** [comment]
Closing, since it should remain optional for custom providers
