### ISSUE TITLE
CocoaPods integration question

### ISSUE THREAD

**Issue by mgrms** [firebase/firebase-ios-sdk#11299]
### Description

Hello,

We use Firebase for a long time and at the moment we integrate Firebase products in a following way:

```
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
and etc...
```

As we see the current documentation shows Firebase installation with pod names **without slash (/)**, like:

```
pod 'FirebaseAnalytics'
pod 'FirebaseCrashlytics'
and etc...
```

Could you please tell what is the difference and what should we use? We missed that moment when this names change has been made.

Thank you.

### Firebase SDK Version

10.9

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebase Product(s)

All

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
In CocoaPods, the `/` syntax denotes a subspec - so `Firebase/Analytics` means use the `Analytics` subspec in the `Firebase` pod.  It has been functionally very similar to the `FirebaseAnalytics` pod since the `FirebaseAnalytics` pod is a dependency of the `Firebase/Analytics` subspec. See https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase.podspec for implementation details. 

Using the Firebase pod historically provided additional capability for Objective C-only apps, including access to importing `Firebase.h` -  that is less relevant as the world is moving to Swift.

There are no immediate plans to discontinue the Firebase pod support, but the long-term supported path is to recommend choosing the requested Firebase pods directly.

I'll close, but feel free to continue the conversation here.

**Comment by mgrms** [comment]
Hi @paulb777 

Thank you very much for a great explanation! Appreciate it!

Could you please tell what about FirebaseCore? As I see Firebase/Analytics and other Firebase/ pods(subspecs) have and install Firebase Core dependency. When using this new FirebaseAnalytics, FirebaseFirestore etc approach, do we need to add this `pod 'FirebaseCore'` as a separator line to Podfile? Or is it no longer needed at all?

Thanks.

**Comment by paulb777** [comment]
All of the other Firebase pods have an explicit dependency on FirebaseCore which tells CocoaPods to install it.

It's needed, but is optional to be specified in the Podfile.
