### ISSUE TITLE
Issue with 10 seconds delay in the getDocument() request from cache is still reproducing

### ISSUE THREAD

**Issue by v-lavrentikov** [firebase/firebase-ios-sdk#1165]
* Xcode version: 9.3
* Firebase SDK version: 4.13 (and latest from repository)
* Firebase Component: Firestore
* Component version: 0.11.0

Old issue from the Firebase 4.11.0 is still reproducing.

* Resolved a regression in the Firebase iOS SDK release 4.11.0 that could cause getDocument() requests made while offline to be delayed by up to 10 seconds rather than returning from cache immediately.

Query sometimes delayed for 10 seconds in the getDocument() request when application is offline.

**Comment by mikelehen** [comment]
@v-lavrentikov Can you provide more detail, in particular what you mean precisely by "application is offline."?

The behavior around this is subtle and heuristic-based.  If the client has already decided it is offline, it should return results from cache immediately.  But if the client hasn't yet decided it is offline (in particular the first request it tries to make doesn't provide any response) it could take up to 10 seconds to determine it's offline.  From then on, results should be immediate without incurring the timeout again.

**Comment by DenisMishin** [comment]
@mikelehen This random 10-second delays issue is reproduced by placing phone in either airplaine mode, or just with explicitly disabled wifi or cellular connections, and issuing repeated requests in succession with couple second delays between them. A fair % of requests will experience this 10-second delay.

**Comment by mikelehen** [comment]
Thanks.  That indeed doesn't sound correct. I'll see if I can reproduce.

**Comment by mikelehen** [comment]
Ahh, I see what's happening.  The "good" news is that as a workaround you could add a snapshot listener (to any document or query, it doesn't matter).  As long as you have an active snapshot listener, you shouldn't incur these delays.

The issue is basically that when your getDocument() call completes (returning data from cache because you're offline), we no longer have a need to establish a connection to the backend and so we stop trying to connect. And so when you do another getDocument() request, we basically start from scratch with no assumption about whether we're online or not. This makes some sense if it's been minutes / hours since your last getDocument() call. But if you /just/ did a getDocument() call seconds ago, we should probably assume you're still offline and not incur the delay of trying to reach the backend.

I'll see what we can do to improve this...  Thanks for the report!

**Comment by DenisMishin** [comment]
@mikelehen thanks! 

Probably you could utilize [SCNetworkReachability](https://developer.apple.com/documentation/systemconfiguration/scnetworkreachability-g7d) to set your connection state machine initial state - i.e. in cases described above it'll be immediately Offline 

`A remote host is considered reachable when a data packet, sent by an application into the network stack, *can leave the local device* `

**Comment by mikelehen** [comment]
@DenisMishin Thanks!  Yeah, we have plans to incorporate SCNetworkReachability and that should definitely improve matters. I'm not sure when that will happen, but it's definitely on the roadmap. We may be able to do something shorter-term to improve the situation, but I'm not sure yet.

**Comment by zxu123** [comment]
Will we track connectivity per-query or for an arbitrary query? If this issue is about device connectivity, seems tracking for an arbitrary query is enough. But keep a listener per-query grant more information if there is change and thus we can determine whether to re-fetch or not and speed up subsequent same query; however that way leads more network traffic.

**Comment by mikelehen** [comment]
We already track connectivity for the entire watch stream (see https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/Remote/FSTOnlineStateTracker.mm for where most of the logic lives).

The change I think we want to make is related to https://github.com/firebase/firebase-ios-sdk/blob/3fd7b456d5b58481fada7a31305bb21bb64dbd06/Firestore/Source/Remote/FSTRemoteStore.mm#L341

Basically, we should keep trying to reconnect for a period of time even if there are no watch targets.

**Comment by mikelehen** [comment]
FYI- We've made some improvements that should help somewhat.  In particular, https://github.com/firebase/firebase-ios-sdk/pull/1783 will cause us to fail faster (after only 1 retry attempt) and https://github.com/firebase/firebase-ios-sdk/pull/1712 will make sure we retry right away if our exponential backoff delay has already elapsed.

We have more work planned, in particular integrating SCNetworkReachability, so I'll leave this open.

Ultimately for now your best bet will still be to keep an active listener ongoing which will ensure the SDK continually tries to retry its connection to the backend.

**Comment by wilhuff** [comment]
We believe that this issue has been resolved (for quite some time now). If you're still experiencing random long delays please file a new issue with as many details as you can.
