### ISSUE TITLE
Cannot build for visionOS   

### ISSUE THREAD

**Issue by asshoffm** [firebase/firebase-ios-sdk#11665]
### Description

I have updated Firebase to the latest version 10.13.0 that should support visionOS according to the release notes. 

Unfortunately, building the framework fails with `application:openURL:sourceApplication:annotation:' is unavailable: not available on visionOS` in the `AppDelegateSwizzler`. 

Is this particular framework not supported yet? 

### Firebase SDK Version

10.13.0

### Xcode Version

15.0 beta 6

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Remote Config

### Targeted Platforms

N/A

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andrewheard** [comment]
Hi @asshoffm, would you be willing to post Swift Package Manager `Package.resolved` file? Specifically, please check that you're pulling in `GoogleUtilities` `7.11.5` since I think the `application:openURL:sourceApplication:annotation:` issue was fixed by https://github.com/google/GoogleUtilities/pull/116.

If you find that you have GoogleUtilities `7.11.4`, you could try Xcode → File → Packages → Update to Latest Package Versions.

Note: @paulb777's suggestion to use beta 5 is still accurate since we have not finished addressing the changes introduced in beta 6. I don't think this issue is related to beta 6 though since it's in Objective-C code.

**Comment by paulb777** [comment]
Closing since the updates to support beta 6 have merged for our next release.
