### ISSUE TITLE
App Attest - Namespace UserDefaults Key by Device for App Attest Key

### ISSUE THREAD

**Issue by benedelstein** [firebase/firebase-ios-sdk#11853]
### Description

If you get a new phone and transfer your apps from your previous phone, your app attest key id is persisted from the transfer. Attesting with this key id fails, because the key should be limited to 1 device. I've had this happen to countless users who get new phones.

Reinstalling the app fixes it.

This was mentioned here: https://github.com/firebase/firebase-ios-sdk/issues/10561
see https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity#3579384

I see you're storing app attest key ids using UserDefaults [in this file](https://github.com/firebase/firebase-ios-sdk/blob/91a6974365663fc6688986bbfb79658c0db25637/FirebaseAppCheck/Sources/AppAttestProvider/Storage/FIRAppAttestKeyIDStorage.m#L90), which will be persisted across phone transfers and iCloud backups. You could either namespace the user defaults key using the [device id](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) or use a restricted [keychain item](https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility). 

This might be a bit of a breaking change, so you could migrate users from the old key location to the new one.

### Reproducing the issue

Install app on phone with app attest App Check provider set up
Get a new phone, transfer data from old phone
Try to attest with new phone (fails)
Delete and reinstall app on new phone (works)

### Firebase SDK Version

10.9

### Xcode Version

14.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check

### Targeted Platforms

iOS

### Relevant Log Output

```shell
DCError.Code.invalidKey https://developer.apple.com/documentation/devicecheck/dcerror/3585177-invalidkey
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andrewheard** [comment]
Hi @benedelstein, in Firebase https://github.com/firebase/firebase-ios-sdk/releases/tag/10.17.0 we're now clearing the stored key ID from `UserDefaults` if [`attestKey:clientDataHash:completionHandler:`](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573911-attestkey?language=objc) fails due to [`DCErrorInvalidKey`](https://developer.apple.com/documentation/devicecheck/dcerror/dcerrorinvalidkey?language=objc) (https://github.com/firebase/firebase-ios-sdk/pull/11986 for details). This should happen the first time an app is launched after being restored on a new device, or if the key is invalid for any other reason.

I've held off on exploring using the [`identifierForVendor`](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) as a key prefix since this would require auditing / documentation around potential privacy implications. We did consider migrating to the keychain (https://github.com/firebase/firebase-ios-sdk/pull/11962) but went forward with handling `DCErrorInvalidKey` specifically instead.

Please let me know if Firebase 10.17 resolves this issue in your app.
