### ISSUE TITLE
Crash for Firestore, iOS 12.5, Xcode 15

### ISSUE THREAD

**Issue by ivkim** [firebase/firebase-ios-sdk#11951]
### Description

Similar to the issue described at https://github.com/firebase/firebase-ios-sdk/issues/11829, running a release build app on a 12.5 iOS device resulted in an immediate crash when launching.

the -ld_classic seemed to work for making an iPad iOS 12.5 not crash when directly connected to Xcode. However, when published to the App Store with this linker flag set, we still encountered the same issue where the app would immediately close out. We had to revert to Xcode 14 to resolve this issue. Xcode 15.1 still seems to have this issue as we were also testing by creating Ad Hoc release builds distributed to ourselves.

This issue behaved the same for both v 10.16 and 10.9

### Firebase SDK Version

10.16, 10.9

### Xcode Version

15

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by dconeybe** [comment]
Can you provide a stack trace of the crash? Or some other information that would help identify the crash?

**Comment by osfunapps** [comment]
@ivkim you've mentioned earlier that in order to resolve the issue, you had to revert back to Xcode 14:

> the -ld_classic seemed to work for making an iPad iOS 12.5 not crash when directly connected to Xcode. However, when published to the App Store with this linker flag set, we still encountered the same issue where the app would immediately close out. We had to revert to Xcode 14 to resolve this issue. Xcode 15.1 still seems to have this issue as we were also testing by creating Ad Hoc release builds distributed to ourselves.

Can you tell me what version of Xcode 14 worked for you? The latest is Xcode 14.3.1. I sure hope they still allow binary updates from this Xcode version to the App Store Connect.

Also, when you've mentioned Xcode 15.1, did you meant Xcode 15.1 beta? Because stable 15.1 isn't out yet:
[Xcode release notes](https://developer.apple.com/documentation/xcode-release-notes)

If so, it bothers me that they wrote that:

> Fixed: Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650)

Meaning, from Apple perspective, the issue has been resolved which doesn't make sense
