### ISSUE TITLE
Conflict with latest Cocoapods CocoaSecurity 1.2.4 openssl_grpc/base.h file not found

### ISSUE THREAD

**Issue by willswinson** [firebase/firebase-ios-sdk#12064]
I cannot install the cocoapod "CocoaSecurity" and "Firebase/Firestore" in the same project. I will receive an error message when building CocoaSecurity and the BoringSSL-GRPC frameworks reading:

openssl_grpc/base.h file not found

CocoaSecurity is a must have in the app at the moment. And we cannot move from Cocoapods to SPM (even if we could, that has different errors also).

Revealing in log shows:
```
In file included from /Users/foobar/Docs/Dev/foobar/FoorBarApp/Pods/CocoaSecurity/CocoaSecurity/CocoaSecurity.m:12:
/Users/foobar/Docs/Dev/foobar/FoorBarApp/Pods/BoringSSL-GRPC/src/include/openssl/base64.h:60:10: fatal error: 'openssl_grpc/base.h' file not found
#include <openssl_grpc/base.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by ncooke3** [comment]
Hi @willswinson, it looks like the issue's description disappeared. Should I close this?

**Comment by willswinson** [comment]
> Hi @willswinson, it looks like the issue's description disappeared. Should I close this?

Accidentally deleted. I updated again.

**Comment by ncooke3** [comment]
What version of CocoaPods is installed?

**Comment by paulb777** [comment]
@willswinson Thanks for the report. 

The problem is CocoaSecurity importing an ambiguous Base64.h and picking up the one from the BoringSSL install.  Please report this issue to the CocoaSecurity maintainers.

![Screenshot 2023-11-07 at 11 13 22 AM](https://github.com/firebase/firebase-ios-sdk/assets/73870/43bb197b-e882-47c9-b673-44e2cb334899)

![Screenshot 2023-11-07 at 11 11 10 AM](https://github.com/firebase/firebase-ios-sdk/assets/73870/a46008bf-3477-435b-8b8a-318111f759b5)
