### ISSUE TITLE
How can I use App Check in the context of an App extension?

### ISSUE THREAD

**Issue by anonys** [firebase/firebase-ios-sdk#12082]
### Description

I need to invoke a cloud function with AppCheck enforced within the App extension - I did register both the app host and extension in AppCheck and they are both under one Project on Firebase . The cloud function works well when invoked from the app host but not when invoked within the app extension (Got the unauthenticated error). I read somewhere that the app extension doesn't support App Check ? if it the case how can I still proceed with invoking the cloud function from the app extension. Also is it necessary to call configure FirebaseApp for both ? 

### Reproducing the issue

Within App Delegate of my App Host
```
let providerFactory = DeviceCheckProviderFactory()
 AppCheck.setAppCheckProviderFactory(providerFactory)
 FirebaseApp.configure()
```

Within the View Conroller of my app extension 
```
   let providerFactory = DeviceCheckProviderFactory()
        AppCheck.setAppCheckProviderFactory(providerFactory)
        
        if FirebaseApp.app() == nil {
                   let filePath = Bundle(for: type(of: self)).path(forResource: "GoogleService-Info-AppExtension", ofType: "plist")
                   guard let fileopts = FirebaseOptions(contentsOfFile: filePath!)
                       else { assert(false, "Couldn't load config file") }
                   FirebaseApp.configure(options: fileopts)
               }
```
### Firebase SDK Version

10.17

### Xcode Version

15

### Installation Method

Swift Package Manager

### Firebase Product(s)

App Check, Functions

### Targeted Platforms

iOS, App Extensions

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by andrewheard** [comment]
Hi @anonys, the documentation you mentioned might be [Apple's docs on App Attest](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity#3576028):

> **Most app extensions don’t support App Attest.** Generally, when executing code in these extensions, bypass key generation and attestation, even if the [isSupported](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573915-issupported) method property is true. **The only app extensions that support App Attest are watchOS extensions in watchOS 9 or later.**

Unfortunately, the documentation on DeviceCheck doesn't mention whether it supports any App Extensions or not. You could try calling [`isSupported`](https://developer.apple.com/documentation/devicecheck/dcappattestservice/3573915-issupported) in your extension to try it:
```
import DeviceCheck
...
let deviceCheckSupported: Bool = DCDevice.current.isSupported
```

Firebase App Check itself should work in an extension but I suspect that the underlying attestation providers, DeviceCheck and App Attest, do not. A [custom provider](https://firebase.google.com/docs/app-check/ios/custom-provider) or calling your backend via your host app (rather than in the extension itself) could be options, though this wouldn't be straightforward to implement.

**Comment by anonys** [comment]
Thanks for your reply @andrewheard! yes unfortunately it is not supported, will look for an alternative in this case.

**Comment by andrewheard** [comment]
> Thanks for your reply @andrewheard! yes unfortunately it is not supported, will look for an alternative in this case.

No problem, @anonys! Sorry I couldn't be more help. I'll mark this as closed but feel free to re-open if you have more questions.
