### ISSUE TITLE
[FR]: Vision OS Support for FireStore

### ISSUE THREAD

**Issue by AhsanAli65** [firebase/firebase-ios-sdk#12164]
### Description

Adding Support to entertain FireStore in the Vision OS applications

### API Proposal

Adding Support to entertain FireStore in the Vision OS applications

### Firebase Product(s)

Firestore

**Comment by AhsanAli65** [comment]
Firebase Firestore SDK does not have support to run on Vision OS

**Comment by ncooke3** [comment]
If you're using SPM, there is an option to build Firestore from source. This should work on visionOS. See [this release note](https://firebase.google.com/support/release-notes/ios#cloud-firestore_5) from Firebase 10.12.0.

**Comment by rokon-uddin** [comment]
Developers using Firestore on visionOS must use a source Firestore distribution rather than the default binary distribution. To do this, quit Xcode and open the desired project from the command line with the FIREBASE_SOURCE_FIRESTORE environment variable. open --env FIREBASE_SOURCE_FIRESTORE /path/to/project.xcodeproj To go back to using the binary distribution of Firestore, quit Xcode and open Xcode like normal, without the environment variable ([#11492](https://github.com/firebase/firebase-ios-sdk/issues/11492)).
