### ISSUE TITLE
FirebaseFirestoreSwift import issue on visionOS

### ISSUE THREAD

**Issue by michaeldadzie** [firebase/firebase-ios-sdk#12296]
### Description

I'm currently using Firestore on visionOS by using a source Firestore distribution rather than the default binary distribution by running this command in the terminal to open my project `open --env FIREBASE_SOURCE_FIRESTORE /path/to/project.xcodeproj`

When i try to build the project i ran into import issues with FirebaseFirestoreSwift

<img width="1130" alt="Screenshot 2024-01-18 at 09 18 38" src="https://github.com/firebase/firebase-ios-sdk/assets/52431642/23184f2c-bb5e-4ed2-8368-bd702e1394b8">

### Firebase SDK Version

10.19.1

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics, Authentication, Crashlytics, Firestore, Storage

### Targeted Platforms

iOS, visionOS

**Comment by ncooke3** [comment]
Hi @michaeldadzie, could you double check that `FirebaseFirestoreSwift` is listed as a dependency in your target's general settings?

<img width="771" alt="Screenshot 2024-01-18 at 9 22 56 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/36927374/7f944293-51bb-4b30-a180-a47326ae1ed6">

In any case though, because you are using 10.19.1, importing `FirebaseFirestoreSwift` is no longer necessary in Firebase 10.17.0+ (you'll see a warning when importing it). All of the API that used to live in the `FirebaseFirestoreSwift` namespace now also lives in the `FirebaseFirestore` namespace. So removing your `FirebaseFirestoreSwift` imports in favor of importing `FirebaseFirestore` is recommended ahead of the next breaking change. 

I'd recommend trying to instead remove the problematic imports and instead import `FirebaseFirestore`.

**Comment by michaeldadzie** [comment]
Hello @ncooke3 I did remove the `FirebaseFirestoreSwift` imports in the project since you mentioned that all of that API now lives in `FirebaseFirestore`, ran into some issues with Auth and used the `FirebaseAuth` import instead of the regular `Firebase` import and i was able to build the project after making these changes. Thank you.
