### ISSUE TITLE
User's display name is nil after linking anonymous account to Google or Apple credentials.

### ISSUE THREAD

**Issue by marwaniaaj** [firebase/firebase-ios-sdk#12358]
### Description

When user is signed in anonymously, and then link this anonymous account to either Google or Apple credentials using `user.link(with:)`, user's displayName in returned `AuthDataResult` is nil.

### Reproducing the issue

````
/// Sign-in anonymously first
try await Auth.auth().signInAnonymously()

/// Then, link with Google credentials
guard let user = Auth.auth().currentUser else { return nil }
let result = try await user.link(with: credentials)

/// print out results.
print("Display name: \(result.user.displayName)")
print("Email: \(result.user.email)")
print("GoogleSignInSuccess: \(result.user.uid)")
````
Result 👇🏻
<img width="351" alt="Screenshot 2024-02-06 at 12 11 59 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/10337793/1d14d11c-0546-4229-bc80-cfd40c89ae90">

### Firebase SDK Version

10.18

### Xcode Version

15.2

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by NhienLam** [comment]
Hi @marwaniaaj, I think this issue is similar to https://github.com/firebase/firebase-ios-sdk/issues/1694#issuecomment-424085098. 

This is working as intended. When linking a provider, the provider’s displayName are not automatically copied to the top level. You can get the `displayName` from [providerData](https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/User#providerdata) and update the user profile after linking.

**Comment by marwaniaaj** [comment]
Thanks @NhienLam for clarifying that!
I've updated my code to update user's profile data with `displayName` from `providerData`.
