### ISSUE TITLE
[FR]: Provide documentation for satisfying Apple's new Privacy Manifest requirements

### ISSUE THREAD

**Issue by kkaliher** [firebase/firebase-ios-sdk#12586]
### Description

After scouring our app it appears the Crashlytics pod is solely responsible for triggering a warning from Apple that we need to add a Disk Space API reason in a Privacy manifest file, required by May 2024.  Specifically, it uses statfs which is one of the listed APIs.

In documentation for the Crashlytics Pod please provide the relevant reason developers should use in their Privacy manifests: 85F4.1, E174.1 (I suspect), or 7D9E.1 - complete descriptions of which can be found here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

### Firebase Product(s)

Crashlytics

**Comment by saikumar-osv** [comment]
I have 2 Apps one with 10.21.0 and another with 10.9.0 and both got this warning. Can you specify which version can fix this issue.

**Comment by paulb777** [comment]
10.22.0+

**Comment by jacobsapps** [comment]
I'm using 1.23.0 and still getting this warning.

Looking at the [Privacy Manifest documentation on Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278397), it appears to suggest that the use of the Firebase SDK to collect this info is invalid?

85F4.1
Declare this reason to display disk space information to the person using the device. Disk space may be displayed in units of information (such as bytes) or units of time combined with a media type (such as minutes of HD video).

Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to send disk space information over the local network to another device operated by the same person only for the purpose of displaying disk space information on that device; this exception only applies if the user has provided explicit permission to send disk space information, and the information may not be sent over the Internet.

E174.1
Declare this reason to check whether there is sufficient disk space to write files, or to check whether the disk space is low so that the app can delete files when the disk space is low. The app must behave differently based on disk space in a way that is observable to users.

Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception that allows the app to avoid downloading files from a server when disk space is insufficient.

7D9E.1
Declare this reason to include disk space information in an optional bug report that the person using the device chooses to submit. The disk space information must be prominently displayed to the person as part of the report.

Information accessed for this reason, or any derived information, may be sent off-device only after the user affirmatively chooses to submit the specific bug report including disk space information, and only for the purpose of investigating or responding to the bug report.

B728.1
Declare this reason if your app is a health research app, and you access this API category to detect and inform research participants about low disk space impacting the research data collection.

Your app must comply with [App Store Review Guideline §5.1.3](https://developer.apple.com/app-store/review/guidelines/#health-and-health-research). Your app must not offer any functionality other than providing information about and allowing people to participate in health research.

**Comment by saikumar-osv** [comment]
> 10.22.0+

As you suggested I updated the firebase and still got this warning from Apple today when I submit my App.

<img width="642" alt="Screenshot 2024-03-27 at 8 03 31 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/68215379/41e02262-20ab-495c-aa5c-28e53f3f3d31">
<img width="866" alt="Screenshot 2024-03-27 at 8 04 51 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/68215379/0bb1c928-b1a2-4ecf-b1e6-68f5b53564e1">

**Comment by technoplato** [comment]
@saikumar-osv did you also add those required descriptions to your project's privacy file?

**Comment by saikumar-osv** [comment]
> @saikumar-osv did you also add those required descriptions to your project's privacy file?

Nope, do I need to add it ?
