### ISSUE TITLE
Publish links to zip archives of old releases

### ISSUE THREAD

**Issue by jaschaio** [firebase/firebase-ios-sdk#1270]
Hey there,
I am using the Firebase SDK together with [react-native-firebase](https://github.com/invertase/react-native-firebase/).

Unfortunately it seems that the latest version `5.0.0` incoporated some breaking changes and I am still required to use `4.13.0` instead.

On the [Add Firebase to your iOS Project](https://firebase.google.com/docs/ios/setup#frameworks) Guide Page is a download link to the SDK under the `Integrate without CocoaPods` Section. But unfortunately it downloads always the latest version and gives no option to download previous ones. I wasn't able to find a download link to previous versions anywhere else.

In this github repro under `Releases` is a download Link to `4.13.0` but it seems to differ significant to the download referenced in the Guide as it only contains a sub-section of the source.

**Where can I get the complete 4.13.0 Firebase for iOS SDK from?**

Thanks

**Comment by jaschaio** [comment]
Finnally found the download link for 4.13.0: https://dl.google.com/firebase/sdk/ios/4_13_0/Firebase-4.13.0.zip

Would be great to have the previous versions linked somewhere within the official google docs for people who integrate without cocoapods or other package managers. For example here: https://github.com/firebase/firebase-ios-sdk/releases

**Comment by paulb777** [comment]
[Rome](https://github.com/firebase/firebase-ios-sdk/blob/master/Rome.md) is an alternative way to access binary frameworks from any release.

**Comment by ryanwilson** [comment]
Starting with 5.14.0, we've started publishing the zip file as a [GitHub Release](https://github.com/firebase/firebase-ios-sdk/releases), which should help for finding previous releases.

In order to find releases older than 5.14.0, you can currently use this format for our download URLs:

```
https://dl.google.com/firebase/sdk/ios/<MAJOR>_<MINOR>_<PATCH>/Firebase-<MAJOR>.<MINOR>.<PATCH>.zip
```

For example, 5.0.1 would be `https://dl.google.com/firebase/sdk/ios/5_0_1/Firebase-5.0.1.zip`.

As Paul mentioned, you can also use [Rome](https://github.com/firebase/firebase-ios-sdk/blob/master/Rome.md) to access binary frameworks from any release.

Thanks for the suggestion @jaschaio!
