### ISSUE TITLE
[FR]: Firestore recursive delete

### ISSUE THREAD

**Issue by ynechaev** [firebase/firebase-ios-sdk#12747]
### Description

Right now deleting a document will not delete it's sub-collections. 
They will be left hanging in database and require additional work to remove them.

The following proposal brings feature parity with Firebase Node.JS library, which has [RecursiveDelete](https://googleapis.dev/nodejs/firestore/latest/Firestore.html#recursiveDelete) function implemented.

### API Proposal

Implement the following interface of `FIRDocumentReference`:

```objective-c
- (void)deleteDocumentRecursively NS_SWIFT_NAME(recursiveDelete());
- (void)deleteDocumentRecursivelyWithCompletion:(nullable void (^)(NSError *_Nullable error))completion
    NS_SWIFT_NAME(recursiveDelete(completion:));
```

which translates into the following Swift API:
```swift
open class DocumentReference : NSObject {
    open func recursiveDelete()
    open func recursiveDelete(completion: (((any Error)?) -> Void)? = nil)
}
```

Additionally, async-await interface:
```swift
    open func recursiveDelete() async throws
```

### Firebase Product(s)

Firestore

**Comment by dconeybe** [comment]
Thank you for your suggestion. The Firestore team has considered at length providing this functionality from the mobile and web SDKs; however, there are technical limitations that make it unable to scale reliably when used in flaky network conditions like mobile and web environments. So we have decided _against_ exposing this functionality from the client SDKs since the general case does not have guaranteed reliability.

If you want to provide recursive delete from your mobile clients, we suggest using Cloud Functions for Firebase (https://firebase.google.com/docs/functions). Specifically, add a field to a document called something like "recursiveDelete" and set up a cloud function to watch for changes to that property. When changed to true, for example, the cloud function can perform the recursive delete.

I'm going to close this issue since we do not plan to implement the feature. Thank you for taking the time to write up the suggestion though.
