### ISSUE TITLE
Token mismatch using iOS 18 Beta 1

### ISSUE THREAD

**Issue by Meyssam120** [firebase/firebase-ios-sdk#13144]
### Description

I'm getting the following error when running my app on iOS 18 and requesting phoneAuthentication:
`Error Domain=FIRAuthErrorDomain Code=17048 "Token mismatch" UserInfo={NSLocalizedDescription=Token mismatch, FIRAuthErrorUserInfoNameKey=INVALID_APP_CREDENTIAL}`.
Before the update to iOS 18 everything worked normally. I triple checked the configuration and everything should be okay on my side. Everything's untouched except the iOS version.
Strangely I could fix the issue by changing `.prod -> .unknown` in
```Auth.auth().setAPNSToken(deviceToken, type: .unknown)```
```Messaging.messaging().setAPNSToken(deviceToken, type: .unknown)```

### Firebase SDK Version

10.28.0

### Xcode Version

16.0 Beta (16A5171c)

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication, Firestore, Messaging, Storage

### Targeted Platforms

iOS

### Relevant Log Output

```shell
Error Domain=FIRAuthErrorDomain Code=17048 "Token mismatch" UserInfo={NSLocalizedDescription=Token mismatch, FIRAuthErrorUserInfoNameKey=INVALID_APP_CREDENTIAL}
```

**Comment by rizafran** [comment]
Thanks for reporting, @Meyssam120. I tried to reproduce the issue on iOS 18 beta, but I can't get the same behavior. You mentioned that the issue was fixed by changing the APNs token type to `.unknown`, in which the actual token will be auto detected from your provisioning profile. The error you encountered usually happens when the APNs device token is either incorrect or doesn't match the certificate uploaded in the console. 

With this, could you verify the following:
- Check if the bundle ID in your app is the same as the bundle ID registered in the console (Check Project Settings -> Your App for the bundle ID registered)
- Check that the [uploaded APNS certificate](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key) is correct and up-to-date
- Download an updated [GoogleService-Info.plist](https://firebase.google.com/docs/ios/setup#add-config-file) and add it to your app
- Verify if the APNs device token is not expired
- Verify if your App ID and Team ID are [setup correctly](https://support.google.com/firebase/answer/9137750?hl=en)

**Comment by rizafran** [comment]
Thanks for verifying, @Meyssam120. May I know if the issue occurred to all users or just in a specific region?

**Comment by Meyssam120** [comment]
The app is not public yet, so I've only experienced myself in Germany.

**Comment by rizafran** [comment]
@Meyssam120, is it possible for you to provide a sample app that reproduces the issue? Also, are you reproducing it using a simulator or a physical device?
