### ISSUE TITLE
[FR]: Modify custom keys behavior to be consistent with Android

### ISSUE THREAD

**Issue by luqas11** [firebase/firebase-ios-sdk#13153]
### Description

If multiple non fatal reports are sent, and different custom key values are set between them, all the reports have the the values of the last one.
This behavior is not consistent with the Android SDK, where each report is sent with the custom key values set at the moment of calling the `recordException` method.

For example, if I do the following sequence:
1. Set key `some_attribute` with value `value1`
2. Send a non-fatal exception with the `recordError` method
3. Set key `some_attribute` with value `value2`
4. Send another non-fatal exception with the `recordError` method
5. Restart the app

**On iOS**, both non-fatal errors are shown in the Crashlytics dashboard with the `some_attribute` key set to `value2`.
**On Android**, the first and the second non-fatal errors are shown in the Crashlytics dashboard with the `some_attribute` key set to `value1` and `value2` respectively.

From my perspective, having different behaviors between platforms adds complexity to the error reporting implementations and while doing error analysis. Before the FR, I created [an issue](https://github.com/firebase/firebase-ios-sdk/issues/13124) about this, including detailed code examples and screenshots. I got the confirmation that the current behavior is intentional, and that I should report it as a feature request.

Is a behavior unification viable?

### Firebase Product(s)

Crashlytics

**Comment by willywagtail** [comment]
Any updates on this issue?

**Comment by themiswang** [comment]
This is an expected behaviour and we do realize the discrepancy. An alternative is when logging non-fatal, you can added additional `userInfo` as extra parameter. UserInfo will attach to custom key values and it is on event base rather on session base. For API reference is [here](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics?_gl=1*huyza5*_up*MQ..*_ga*MTMwNDEyNDcwOS4xNzMyNjUwOTk3*_ga_CW55HF8NVT*MTczMjY1MDk5Ny4xLjAuMTczMjY1MDk5Ny4wLjAuMA..#/c:objc(cs)FIRCrashlytics(im)recordError:userInfo:).
