### ISSUE TITLE
[Question] How to download the framework SDK zip

### ISSUE THREAD

**Issue by b0f1df79** [firebase/firebase-ios-sdk#13207]
### Description

In release 10.28.1, I don't see the Firebase.zip file like previous releases.
Do you plan to update it in the future? Or do you no longer support downloading the framework SDK zip?

### Firebase SDK Version

10.28.1

### Xcode Version

15.1

### Installation Method

Zip

### Firebase Product(s)

All

### Targeted Platforms

iOS, macCatalyst

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @b0f1df79, the fix for zip distribution will be available in 10.29.0 as mentioned [here](https://github.com/firebase/firebase-ios-sdk/issues/13117#issuecomment-2189038068). The 10.28.1 release is only available for CocoaPods and Swift Package Manager.

I'll now be closing this ticket but feel free to comment if you have any questions.
