### ISSUE TITLE
StoreKit2 purchases are not shown in Firebase panel as in_app_purchase event

### ISSUE THREAD

**Issue by gbesler** [firebase/firebase-ios-sdk#13392]
### Description

We have followed the guide in the website for sending StoreKit 2 events with Firebase using;

`Analytics.logTransaction(transaction)`

But none of the events are showing up in Firebase panel. How to fix this issue? 

### Firebase SDK Version

10.29.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

**Comment by rizafran** [comment]
Thanks for reporting, @gbesler. Your issue seems related to #12597. Currently, there's an internal bug which is related to this issue. With this, please file via [Firebase Support](https://firebase.google.com/support/) so the team would be able assist you and provide the latest update regarding this issue.
