### ISSUE TITLE
Latest release is not available through Carthage

### ISSUE THREAD

**Issue by mpaulsonco** [firebase/firebase-ios-sdk#1342]
#### Enviornment
  * Xcode version: Not Applicable 
  * Firebase SDK version: 5.1.0
  * Firebase Component: Any
  * Component version: 5.1.0

#### Steps to reproduce:

1. Attempt to install Firebase 5.1.0 from Carthage

The latest version available from `https://dl.google.com/dl/firebase/ios/carthage/*.json` is `5.0.1` *however* Firebase `5.1.0` [has been released](https://github.com/firebase/firebase-ios-sdk/releases/tag/5.1.0).

**Comment by ryanwilson** [comment]
The Firebase `5.1.0` release just went out yesterday (even though the tags were created 5 days ago) but the Carthage release should be out soon!

**Comment by paulb777** [comment]
Firebase 5.1.0 is now available via Carthage.

**Comment by walsht** [comment]
Not working for me 
`*** Skipped building firebase-ios-sdk due to the error:
Dependency "firebase-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/firebase/firebase-ios-sdk/issues/new
`
