### ISSUE TITLE
Including FirebaseAuth 5.0 SDK is no longer possible in App extension

### ISSUE THREAD

**Issue by bojeil-google** [firebase/firebase-ios-sdk#1357]
iOS SDK and FirebaseAuth previously unofficially supported extensions and other similar environments up to 4.x.
Since 5.0, it was no longer possible to include FirebaseAuth.
One reason we don't support this is due to sharedapplication not being available in extensions which phone authentication depends on. However, many other APIs do not depend on this and were still usable. In addition to that, the 4.x SDK was still usable from extensions despite that limitation. As a result this is seen as a breaking change.

Due to this change, many existing app extensions are now unable to upgrade from 4.x to 5.x.

**Comment by paulb777** [comment]
Raised at https://stackoverflow.com/questions/50592585/can-firebaseauth-5-0-x-be-used-in-an-ios-app-extension and https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/OtbDoPGm4zg/wGib79IdAgAJ

**Comment by RickForAxios** [comment]
I would really like to see app extensions become officially supported. Even if not "officially supported", it really sucks to lose the ability to use FB in an extension. In our case, we have a Share Extension that lets the user send a web page URL to Firestore.

None of my options are good:

- Stick with FB 4.x SDK in the extension. This may force me to stick with 4.x across the board just to make things simple.
- Create a FB Function for the extension to call via HTTP. I would have to roll my own auth to some extent, since I wouldn't be able to rely on FBAuth.
- Kick the data over to the main app and hope the main app runs soon (either because the user opened it, or due to being woken up in the background by iOS).

Either yay or nay, it would be great to get an official stance from FB on App Extensions.
