### ISSUE TITLE
Analytics events didn't been track successfully  on  iOS 18 devices

### ISSUE THREAD

**Issue by ZDFiosDeveloper** [firebase/firebase-ios-sdk#13640]
### Description

Currently we are using the firebase 10.14.0, but we can't track the Analytics events on iOS 18 devices, but it can track successfully on the iOS 17 devices, so I upgrade the firebase version to 11.2.0, but it still been track successfully, so I check the debug log on iOS 
| iOS 17  | iOS 18 simulator | iOS 18 device|
| -- | -- | -- |
| <img width="300" alt="image" src="https://github.com/user-attachments/assets/fb3ad8de-f990-4878-a873-791712147c55"> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/70f218b7-3a73-4afd-90e7-63d6a46796e1"> | <img width="300" alt="image" src="https://github.com/user-attachments/assets/7c678db3-6839-4635-9e27-653c035989c0">|
And I think the scenario is same with https://github.com/firebase/firebase-ios-sdk/issues/13598, but I don't know why that issue had been closed.

### Firebase SDK Version

11.2.0

### Xcode Version

15.4

### Installation Method

Carthage

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by ZDFiosDeveloper** [comment]
I passed the debug flag  at the runtime using the process api, but even I didn’t  pass the debug flag, still can’t  find the iOS 18 devices in debug view

**Comment by ncooke3** [comment]
Thanks, @ZDFiosDeveloper, it seems that the `Process` API is no longer a reliable way to set the flag in iOS 18.

Could you please try switching over to instead passing the flag as a launch argument does not make a difference? See this example:
<img width="960" alt="Screenshot 2024-09-16 at 7 08 04 AM" src="https://github.com/user-attachments/assets/28f19b12-b22a-4d63-bba7-585b0b1e7fd0">

Additionally, I see you are using Carthage. Please ensure that `GoogleUtilities.xcframework` is from the lastest 11.2 Carthage distribution rather than leftover from a previous version's install.  The version is embedded in the `Info.plist` at the root of one of the platform directories inside the XCFramework (`GoogleUtilities.xcframework/ios-arm64/GoogleUtilities.framework/Info.plist`). It should be `8.0.2`.

**Comment by ZDFiosDeveloper** [comment]
@ncooke3  after change` -FIRDebugEnabled` to the arguments, it works fine now, thanks.

**Comment by ZDFiosDeveloper** [comment]
@ncooke3 , I have one more question, that is we can set the Argument Passed on launch when I connect with Xcode, but how can I set the Argument  when I need to build a package to QA members.

**Comment by iwb-kevin-hirsch** [comment]
Hello here 👋 

We are encountering the same issue when we need to provide a build to our QA team to test tracking. We are setting the Launch Argument in code and since iOS 18, this does not work anymore.

Is there any solution envisioned? Could we, for example, have access to a new API the Firebase SDK could expose for us to use (like `FirebaseAnalytics.debugViewEnabled = true`)?

**Comment by ZDFiosDeveloper** [comment]
@iwb-kevin-hirsch @dmytrochumakov  my team member fix it with 
` UserDefaults.standard.set(true, forKey: "/google/firebase/debug_mode")`
` UserDefaults.standard.set(true, forKey: "/google/measurement/debug_mode")`
