### ISSUE TITLE
when I add  s.dependency "Firebase/Core","5.0.0" in Podspec,then Use pod package failed

### ISSUE THREAD

**Issue by chatwyn** [firebase/firebase-ios-sdk#1369]
## I want to make private pod and i depend firebase， I add s.dependency "Firebase/Core","5.0.0" in Podspec, then I want to make a framework , I use pod package , then build failed. 

 /var/folders/qc/7_dh4q2x5_9g4ydsyn4_r03h0000gn/T/cocoapods-xgidm4bd/Pods/Static/FirebaseCore/Firebase/Core/FIRVersion.m:18:2: error: "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
    #error "Firebase_VERSION is not defined: add -DFirebase_VERSION=... to the build invocation"
     ^
    /var/folders/qc/7_dh4q2x5_9g4ydsyn4_r03h0000gn/T/cocoapods-xgidm4bd/Pods/Static/FirebaseCore/Firebase/Core/FIRVersion.m:22:2: error: "FIRCore_VERSION is not defined: add -DFIRCore_VERSION=... to the build invocation"
    #error "FIRCore_VERSION is not defined: add -DFIRCore_VERSION=... to the build invocation"
     ^
    2 errors generated.
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileC /var/folders/qc/7_dh4q2x5_9g4ydsyn4_r03h0000gn/T/cocoapods-xgidm4bd/Pods/build/Pods.build/Release-iphoneos/FirebaseCore.build/Objects-normal/arm64/FIRVersion.o FirebaseCore/Firebase/Core/FIRVersion.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

How can I solve It ?

**Comment by chatwyn** [comment]
I clone this project,then I use  'pod package FirebaseAuth.podspec --force' ,same error

**Comment by paulb777** [comment]
Thanks @chatwyn. I can reproduce now.  The failure also occurs without the dependency from FirebaseAuth to FirebaseCore by directly trying to package FirebaseCore with `pod package FirebaseCore.podspec`. 

It seems that `cocoapods-packager` does not correctly process the `pod_target_xcconfig` [podspec attribute](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore.podspec#L35).

The next step would be to [create an issue in the cocoapods-packager](https://github.com/CocoaPods/cocoapods-packager/issues) and investigate there.

**Comment by devpascoe** [comment]
How are folks going with this lately? I'm just chiming in now, i have my own library and corresponding podspec with the dependency specified for Firebase with:
s.dependency = 'Firebase/Core'

and get the error on the consuming app's pod install:
NoMethodError - undefined method `basename' for #<String:0x00007f9ecd4b02d0>

I've tried to have the consuming app's Podfile omit and include use_frameworks! to no avail.

Ideally i'd like to have our podspec specify the dependency on Firebase instead of asking the consuming Podfile to include it also along with our pod.

Note: for now specifying pod 'Firebase/Core' in the consuming Podfile is my workaround.

**Comment by devpascoe** [comment]
ah dang. Ignore above. No = after dependency
