### ISSUE TITLE
Inconsistent Firestore Access with Custom Claims After getIDTokenForcingRefresh(true)

### ISSUE THREAD

**Issue by HyenaJeremyLin** [firebase/firebase-ios-sdk#13830]
### Description

I encountered an issue related to Firestore access when using custom claims in our iOS app. Here’s the situation:

1. Our app calls our server’s API, where the admin sets a custom claim "pair_id" of type String for the user.
2. After the API call is complete, the app calls getIDTokenForcingRefresh(true) to refresh and retrieve the updated token, which includes the "pair_id" claim.
3. However, when attempting to access Firestore immediately after obtaining the refreshed token, our access is denied based on the security rules.
4. Interestingly, if we attempt to access Firestore again after waiting for around 5 seconds, it succeeds without issues.

It seems there is a delay in Firestore recognizing the updated custom claims. Is there a recommended way to adjust this behavior or a workaround to ensure Firestore permissions work immediately after refreshing the token?

I also came across this issue: [#1499](https://github.com/firebase/firebase-ios-sdk/issues/1499) Is re-authenticating the only solution for now?

### Firebase SDK Version

10.22.1

### Xcode Version

16.0

### Installation Method

Swift Package Manager

### Firebase Product(s)

Firestore

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by tom-andersen** [comment]
Hi @HyenaJeremyLin!

After discussing with @dconeybe, we have a working theory. If you can try our suggestion, please let us know if that works.

1. Yes, there is a delay. The SDK Auth component is separate from Firestore component. The communication between Auth and Firestore is asynchronous, such that a token refresh will arrive shortly after forcing it.
2. Normally, when Auth notifies Firestore of User token change, Firestore will disconnect and reconnect with new token.
3. Instead of waiting for Auth to notify Firestore, you can force reconnection by using Firestore disable/enable network methods.

See: https://firebase.google.com/docs/firestore/manage-data/enable-offline#disable_and_enable_network_access

Please try following steps:

1. Call `getIDTokenForcingRefresh(true)` as before.
2. Then disable network.
3. Then enable network.
4. Access document.

This should have the desired effect.

**Comment by marinofelipe** [comment]
> Hi @HyenaJeremyLin!
> 
> After discussing with @dconeybe, we have a working theory. If you can try our suggestion, please let us know if it works.
> 
> 1. Yes, there is a delay. The SDK Auth component is separate from Firestore component. The communication between Auth and Firestore is asynchronous, such that a token refresh will arrive shortly after forcing it.
> 2. Normally, when Auth notifies Firestore of User token change, Firestore will disconnect and reconnect with new token.
> 3. Instead of waiting for Auth to notify Firestore, you can force reconnection by using Firestore disable/enable network methods.
> 
> See: https://firebase.google.com/docs/firestore/manage-data/enable-offline#disable_and_enable_network_access
> 
> Please try following steps:
> 
> 1. Call `getIDTokenForcingRefresh(true)` as before.
> 2. Then disable network.
> 3. Then enable network.
> 4. Access document.
> 
> This should have the desired effect.

@tom-andersen , thanks for the reply.

I'm replying to you, because I'm facing the same at work. The use case is very similar to the one reported by @HyenaJeremyLin . 

The work-around I found was to refresh the token with a delay, after _0.3 seconds_ or so, which is quite "weak" and problematic imo. Now that I read your reply, I tried the approach suggest by you, but it unfortunately did not work.

A few follow up questions:
- Have this changed in the major bump from version 10.* to 11.*? For us, it works fine without the bump
- If there's a behavior change associated with the SDK major bump, shouldn't that be documented and clear in the release notes? I imagine others might face the same and have no idea what's going on
- Would it be possible to handle that inside the SDK? For example, there could be an async overload where the SDK delays the refresh and/or waits for claims to be updated. I reckon that is far from simple and might not be possible given it depends on the server and the client SDK is likely agnostic of it(?), but if everyone has to do manual tricks to asynchronously refresh the token, it might be better to have the SDK simplify that instead.

**Comment by marinofelipe** [comment]
Actually, even with the "manual" delay, it's not quite working 😢. It only works after the user gets signed out, which is a side effect of the 401 I get for the lack of the custom claim (our internal logic).

I also see the following logs before the claim starts to appear
> attempted to run migration and failed. closing connection.
 attempted to run migration and failed. closing connection.
attempted to run migration and failed. closing connection.

Which look like some internal Firestore calls (?)

**Comment by tom-andersen** [comment]
@marinofelipe Your question might be better directed towards someone from `api: auth`, since it doesn't involve Firestore (if I understand correctly). In which case, you might want to start new issue with reference to this issue for context.

I think what you desire, "there could be an async overload where the SDK delays the refresh and/or waits for claims to be updated", is done in Firestore by use of `FIRAuthStateDidChangeInternalNotification`. Someone who knows more about auth could help you get access to this notification. But that should be asked as a new issue, since it doesn't relate to Firestore.

**Comment by marinofelipe** [comment]
Hi @tom-andersen , it make sense. I assumed they were related. I'll do as you say and create a new issue attributed to `auth`, thank you!

**Comment by paulb777** [comment]
This may be related to the existing #7911 cc: @morganchen12
