### ISSUE TITLE
CRASHLYTICS - Undefined symbol: _OBJC_CLASS_$_JSContext

### ISSUE THREAD

**Issue by naticio** [firebase/firebase-ios-sdk#13995]
### Description

it happens when using other linker flags -Objc

### Reproducing the issue

it happens when using other linker flags -Objc

### Firebase SDK Version

10.28

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by naticio** [comment]
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JSContext", referenced from:
       in GoogleMobileAds[arm64][448](GADOMIDLightJSExecutor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

Undefined symbol: _OBJC_CLASS_$_JSContext

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by ncooke3** [comment]
The missing symbol comes from the GoogleMobileAds SDK rather than a Firebase SDK. 

> "_OBJC_CLASS_$_JSContext", referenced from:
> in GoogleMobileAds[arm64][448](GADOMIDLightJSExecutor.o)

The `JSContext` symbol is defined in Apple's `JavaScriptCore` framework: https://developer.apple.com/documentation/javascriptcore/jscontext?language=objc

I would recommend trying to link the `JavaScriptCore` by going to your target's build settings > _Frameworks, Libraries, and Embedded Content_ > + > search for JavaScriptCore` > select and add.

<img width="1512" alt="Screenshot 2024-10-30 at 9 07 59 AM" src="https://github.com/user-attachments/assets/0a02c523-e94c-4d83-9e76-6fb6c14ad625">

For more help with Google Mobile Ads, please file an issue over at https://github.com/googleads/swift-package-manager-google-mobile-ads
