### ISSUE TITLE
FCM failed to Fetching the current registration token on iOS 18.1.1

### ISSUE THREAD

**Issue by dongwk2024** [firebase/firebase-ios-sdk#14203]
### Description

When I upgraded my iPhone to iOS 18.1.1, running the Xcode debugging application to try and obtain the token failed,The code is as follows:
`        Messaging.messaging().token { token, error in
          if let error = error {
            print("Error fetching FCM registration token: \(error)")
          } else if let token = token {
            print("FCM registration token: \(token)")
              Application.shared.sendPushToken.onNext(token)
          }
        }
`
Log message:
`
Error fetching FCM registration token: Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}
`

My implementation process is roughly as follows:
The didFinishLaunchingWithOptions in Appdelegate initializes firebase (FirebaseApp. configuration())
Then it called (application.registerForRemoteNotifications()) again.

When App entered the viewDidLoad of the homepage viewController, I made a permission request and attempted to obtain the FCMtoken to upload to my application server. At this point, the above problem occurred.

The code for this section is as follows:
![截屏2024-12-03 15 53 28](https://github.com/user-attachments/assets/49430c51-9f34-4bf6-8cdd-33c35c943e73)

Other information:
I confirm that my code has not been modified. Regarding Firebase, I tried three different versions 10.24.0, 11.4.0, and 11.5.0, and the results were the same.
I have read the official document [https://firebase.google.com/docs/cloud-messaging/ios/client](url) My app did not manually register the APNS device token and instead used Method swizzing in Firebase Cloud Messaging
Regarding other logs on FCM:
![截屏2024-12-03 16 04 16](https://github.com/user-attachments/assets/d56cd424-5f8d-4ee3-80b6-33ae5ce67842)

This problem has been bothering me for a long time. I hope someone can provide help. Thanks.

### Firebase SDK Version

11.5.0

### Xcode Version

16.1

### Installation Method

CocoaPods

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS, All

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by rizafran** [comment]
Hi @dongwk2024, this error seems related to https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795 in which there was a change implemented starting [v10.4.0](https://firebase.google.com/support/release-notes/ios#fcm_10). With this, an APNs token must be provided to the SDK before retrieving an FCM token during startup, otherwise, an error will be returned as part of the completion in which you have encountered. We are declining vending an FCM token until an APNS token is provided. 

I also found this [related post](https://stackoverflow.com/questions/58246620/apns-device-token-not-set-before-retrieving-fcm-token-for-sender-id-react-nati/69316428#69316428) that would possibly resolve the issue.
