### ISSUE TITLE
Is GoogleService-Info.plist is harmful for jailbreak iOS devices or hacker?

### ISSUE THREAD

**Issue by asaduzzaman-shuvro** [firebase/firebase-ios-sdk#1442]
### Environment

  * Xcode version: 9.3.1
  - Firebase/Core (5.3.0):

**Comment by morganchen12** [comment]
Don't store sensitive information in remote config, and use security rules to secure your information in RTDB/Firestore/Storage. Leaking remote config values shouldn't be a significant concern since the values must be interpreted by your app to have meaning and they're going to be visible directly or indirectly in your app anyway.

In general you can't assume someone calling your Firebase APIs is necessarily a user using your app.
