### ISSUE TITLE
Two observers within the same app interfering with each other

### ISSUE THREAD

**Issue by yusuftor** [firebase/firebase-ios-sdk#1492]
* I'm using the latest versions of every component and Xcode.
  * Firebase Component: Database

I have two observers within my app, one that is ordered, one that isn't. The unordered observer seems to interfere with the ordered observer's results, when the unordered observer is called from a different view controller.

#### Steps to reproduce:

A simplified version of my database looks like this:

```
    "events" : {
        "Oo75nbcDsUK7vPWGDbnL" : {
          "queue" : {
              "K7THdbKzd2aSfaD9a0xmsszkReq1" : {
                "queuePosition" : 1
              },
              "R5UwSxlH3vhH6SjTNMGfMoiaGae2" : {
                "queuePosition" : 2
              }
           }
        }
    }
```
To reproduce the issue, I have a tab bar controller with two tabs. I put this code in one view controller's `viewDidLoad` method:

```
    let test1 = Database.database().reference()
            .child("events/Oo75nbcDsUK7vPWGDbnL/queue/R5UwSxlH3vhH6SjTNMGfMoiaGae2")
            .observe(.value, with: { snapshot in
                print(snapshot.key) // Prints out R5UwSxlH3vhH6SjTNMGfMoiaGae2
            })
```
Then put this code in another view controller's `viewDidLoad` method:
```
    let test2 = Database.database().reference()
            .child("events/Oo75nbcDsUK7vPWGDbnL/queue")
            .queryOrdered(byChild: "queuePosition")
            .queryLimited(toFirst: 25)
            .observe(.childAdded, with: { snapshot in
                 print(snapshot.key) // Prints out R5UwSxlH3vhH6SjTNMGfMoiaGae2, then K7THdbKzd2aSfaD9a0xmsszkReq1
            })
```

First view the view controller that has `test1` in, then view the one with `test2` in. 

Oddly, if these two pieces of code are put within the same `viewDidLoad` method of a view controller, then the ordered listener works as expected. I've asked for help on StackOverflow but no one has been able to help. If I remove the `test1` code, then `test2` works as expected.

**Comment by schmidt-sebastian** [comment]
Hi @yusuftor! Thanks for sending this over. This is actually the expected behavior. What is going on here is that the second listener will first returns results from cache, and then go back to the server to fetch the remaining data. Since you already fetched key `R5UwSxlH3vhH6SjTNMGfMoiaGae2`, it will be returned right away.

You are probably asking yourself why we don't respect the orderBy constraint you provided - but it turns out that we actually do. If you use one of the methods that return the key of the previous sibling (such as https://firebase.google.com/docs/reference/swift/firebasedatabase/api/reference/Classes/DatabaseReference#/c:objc(cs)FIRDatabaseReference(im)observeEventType:andPreviousSiblingKeyWithBlock:), you will see that we return `nil` as the previous child for both `R5UwSxlH3vhH6SjTNMGfMoiaGae2` and `K7THdbKzd2aSfaD9a0xmsszkReq1`. Every time we raise a snapshot we are thus appending an element to the top of the result set, which you can use to restore the original order.
