### ISSUE TITLE
Resetting password on user account does not remove currentUser  from auth

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [firebase/firebase-ios-sdk#198]
* Xcode version: Version 8.3.3 (8E3004b)
  * Firebase SDK version: 
Using Firebase (4.1.0)
Using FirebaseAnalytics (4.0.3)
Using FirebaseAuth (4.1.0)
Using FirebaseCore (4.0.5)
Using FirebaseCrash (2.0.1)
Using FirebaseDatabase (4.0.1)
Using FirebaseInstanceID (2.0.0)
Using FirebaseRemoteConfig (2.0.2)
Using FirebaseStorage (2.0.1)
Using FirebaseUI (4.1.1)

  * Library version: 4.1.0
  * Firebase Product: auth

#### Steps to reproduce:

What happened? How can we make the problem occur?

1. Implemented simple example account login with email login (according to guide)
2. Opened app successfully logged-in, app saved file on the cloud storage no issues.
3. Several days and app opens later, tried to login on another device, forgot my user password for test account. Sent reset password link to user via firebase console.
4. I reset password via email system and the web.
5. I logged in with new password on new device, all good.
6. Returned to my original device, cold started app, it appeared to be logged in (Auth.auth(app:app).currentUser was not nil and auth state change callback returned non nil user) 
7. **App attempted to upload a file to cloud storage and failed with auth error**.

Expected result:
If password is changed externally (login invalid), I expected .currentUser to be reset to nil.....

! Whats worse is deleting and re-installing the app still returned non-nil for current user! (it must be storing this in the keychain)
To reset the issue I had to add a call to explicitly logout. !

**Comment by XiangtianDai** [comment]
@LeeMatthewHiggins 
Firebase Auth does not attempt to validate the current signed-in user when loading them from Keychain at the time app starts, because we don't want to put the burden on all apps whether or not the current user is actually used for this edge case. I'll look into what we may be able to do in future. Meanwhile, you can work it around by calling `reloadWithCompletion:` on the current user after app starts and logout the user if the returned error is one of `FIRAuthErrorCodeUserNotFound`, `FIRAuthErrorCodeUserTokenExpired`, `FIRAuthErrorCodeInvalidUserToken`, or `FIRAuthErrorCodeUserDisabled`.

**Comment by LeeMatthewHiggins** [comment]
ok I´ll add that. I recommend adding a warning to the doc´s, this issue would be easy to miss and end up in a live app.

**Comment by XiangtianDai** [comment]
@LeeMatthewHiggins Thanks for the suggestion. I'll see what I can do.

Firebase Auth automatically refreshes the ID tokens before they expire if they are actively used another Firebase product such as Firebase Realtime Database, and automatically signs out the current user if the long-lived refresh token is no long valid, e.g., the password has been changed on another device. So I believe the issue here is perhaps not so troubling in a real world situation.

**Comment by kmdupr33** [comment]
Deleting a user causes this same issue. `currentUser` isn't cleared, so the app still thinks its logged in. unfortunately, it gets weirder: if you try to interact with the realtime database with your zombie user session, you'll get success messages back, even if you aren't actually able to change any of the data in the database.

**Comment by XiangtianDai** [comment]
@kmdupr33 Yes if the current user is deleting from another device there would be the same issue. And the same workaround to reload user and check for error would work, too.

**Comment by XiangtianDai** [comment]
Please note that in the newly released [FirebaseAuth 4.3.0](https://cocoapods.org/?q=FirebaseAuth), so invalidated users (such as user deleted or reseted password on another device) are automatically logged out as soon as any operation is attempted.

**Comment by morganchen12** [comment]
IIRC this is working as intended, but could maybe use a documentation update.
