### ISSUE TITLE
FirebaseCore, FirebaseAuth and FirebaseStorage xCode analyze errors

### ISSUE THREAD

**Issue by Idomo** [firebase/firebase-ios-sdk#2045]
* Xcode version: 10.1
  * Firebase SDK version: 5.4.1
  * Using FirebaseAuth (5.0.2)
  * Using FirebaseCore (5.0.6)
  * Using FirebaseStorage (3.0.0)

### Describe the problem
When running analyze via xCode (Product > Analyze) it will show some errors about Memory, Logic, API Misuse, Coding Conventions and more. 
#### Steps to reproduce:
Run Analyze via xCode on project that using the above versions of Firebase with those pods:
```
pod 'Firebase/Core', '~> 5.4.0'
pod 'Firebase/Storage', '~> 5.4.0'
pod 'Firebase/Auth' , '~> 5.4.0'
```

Hope you'll be able to fix those errors so our apps will be faster and reliable. 
Thanks,
Ido.

![image](https://user-images.githubusercontent.com/26777129/47964754-dfb03600-e046-11e8-9922-427e81bf7763.png) ![image](https://user-images.githubusercontent.com/26777129/47964751-d8892800-e046-11e8-8e21-6f190adb8014.png) ![image](https://user-images.githubusercontent.com/26777129/47964758-e76fda80-e046-11e8-9781-05ac0e1c4a0f.png)

**Comment by paulb777** [comment]
All the analyze warnings were fixed by Firebase 5.8.0 in [several PR's](https://github.com/firebase/firebase-ios-sdk/pulls?utf8=%E2%9C%93&q=is%3Apr+analyze). Please update to the a newer release.

We still need to confirm that Xcode 10.1 doesn't introduce anything new and will reopen if that's the case.
