### ISSUE TITLE
Investigate Firebase Core reading/writing NSUserDefaults outside of main thread

### ISSUE THREAD

**Issue by rsattar** [firebase/firebase-ios-sdk#209]
#### Configuration 
 * Xcode version: 8 or 9?
  * Firebase SDK version: 4.0.x
  * Library version: 4.0.x
  * Firebase Product: core

#### Describe the problem

@odrobnik [mentioned on Twitter](https://twitter.com/Cocoanetics/status/898906949470883841) than there are cases where NSUserDefaults are being written off the main thread. We should investigate whether this is really an issue, and if we need to any safeguards around them. [NSUserDefaults is thread-safe](https://developer.apple.com/documentation/foundation/userdefaults#overview), but there is a philosophical argument for using them on the main thread only. I'll let @odrobnik elaborate. 

#### Steps to reproduce:

The [Podfile being used](https://twitter.com/Cocoanetics/status/899702762795040772) indicates that only the subcomponent Firebase/Core is being imported:

![Podfile showing Firebase/Core](https://pbs.twimg.com/media/DHxi427XcAQNRtJ.jpg:large)

And that the [issue started when `iAd.framework` was added to the project](https://twitter.com/Cocoanetics/status/898911651294044160).

**Comment by odrobnik** [comment]
Firebase writes to User defaults on a background thread. This causes change notifications also to be sent from the same background thread. If an app monitors the update notification it might update UI on the background queue.

Normally only code of the developer would be interacting with user defaults and likely as a result of user action via main queue UI.

So it stands to reason that a third-party framework which triggers notifications that are part of the iOS SDK should be made safe by dispatching onto main queue before updating user defaults.

Or if not, then a warning about this fact should be added to the setup guide so that developers using Firebase are made aware that they have to do that.

The problem here is that tradi

**Comment by paulb777** [comment]
This is not an issue in the open source repo. 

We're tracking it internally at b/64945474 and will update here when there is a resolution.

**Comment by baolocdo** [comment]
@odrobnik Thanks for the report. Would you mind providing us some log to reproduce?

**Comment by odrobnik** [comment]
No, but you can easily reproduce it. Subscribe to the user defaults change notification and set a breakpoint there. You will see that you get there on a background thread

**Comment by baolocdo** [comment]
I totally agree with you that we should update the documentation that the Firebase SDKs do use NSUserDefaults to avoid surprises.
I think the problem here is that you try to update UI from the background thread. Any notification is not guaranteed to be called from the main queue and a good practice should be always update the UI on the main queue. Can you please provide us any documentation that suggests that _"only code of developer would be interacting with user defaults and likely as a result of user action via main queue UI"_? I'd like to learn more and it will be more compelling reason to update our SDKs.
Note that the iOS SDK can change NSUserDefaults but it doesn't send the notification but the implementation of NSUserDefaults sends it automatically from the calling thread as documented by Apple. Updating NSUseDefaults on the main queue can block the main queue, especially if it syncs to disk, so we try to avoid doing heavy operations on the main queue.

**Comment by katowulf** [comment]
We're testing a potential fix for updates to NSUserDefaults and threading issues. If anybody here would like to try it out, please shoot me an email. katowulf at the google.
