### ISSUE TITLE
FR: Swift Package Manager Support for Firestore and Auth

### ISSUE THREAD

**Issue by ghost** [firebase/firebase-ios-sdk#2135]
### [READ] Step 1: Are you in the right place?
 Current Firestore Implementation can be used in SPM with Module map.

### [REQUIRED] Step 3: Describe the problem

Use firestore and Auth with SPM Packege

**Comment by ryanwilson** [comment]
Thanks for the feature request, @ios3! I have a few questions about your usage, if you don't mind!

1. Do you currently use SPM for your iOS App?
2. Are you using SPM for other platforms?
3. You mentioned that the current Firestore Implementation can be used in SPM with a module map - have you tried this, and if so, can you please share some details?

This is something we're keeping a close eye on, but does have some challenges. Every dependency of a SPM project also needs to be on SPM, so there's some groundwork to be done in order to get up to speed there. The priority of this will jump significantly this when SPM gets official support for iOS, but ideally we already support it when that happens :) If you could help answer those questions above, it'll help us prioritize things and understand how SPM is being used in the wild.

Cheers!

**Comment by ios3** [comment]
Do you currently use SPM for your iOS App?
No, we are currently using SPM for our CLI App.
Are you using SPM for other platforms?
Yes, CLI and Server Side
You mentioned that the current Firestore Implementation can be used in SPM with a module map - have you tried this, and if so, can you please share some details?
No

**Comment by ryanwilson** [comment]
Thanks for the info, @ios3.

**Comment by ethanbonin** [comment]
Checking in on this. Any status? Anything I can help on to get Cloud Firestore out and in the open for SPM?

**Comment by ryanwilson** [comment]
Thanks for checking in @ethanbonin. 

We've done some preliminary investigations and part of the difficulty would be that all Firestore dependencies (and *their* dependencies) would also need to be available on Swift Package Manager.

You can see the list starting here: https://github.com/firebase/firebase-ios-sdk/blob/e04b6ba953440aae23f6ae9e3afe51002cf772ee/FirebaseFirestore.podspec#L54

A good start would be getting a package up and running with `GoogleUtilities`, followed by `FirebaseCore`. Hopefully we can get to that soon but until Apple announces support for iOS it's likely that it'll be a lower priority. If you want to give it a go, I'd be happy to help out, review, and provide any extra insight I can!

**Comment by possen** [comment]
OK Apple supports it now. High priority right!? :-)

**Comment by paulb777** [comment]
@possen Yep!

**Comment by MihaelIsaev** [comment]
Can't wait for SPM support!

**Comment by nakkht** [comment]
Would love to see SPM support!

**Comment by AlexLike** [comment]
Yes, *please*!

**Comment by spencerwhyte** [comment]
+1

**Comment by paulb777** [comment]
Closing in favor of #3136
