### ISSUE TITLE
Create MacOS storage sample app

### ISSUE THREAD

**Issue by SelfnessAid** [firebase/firebase-ios-sdk#221]
I'd like to show firebase storage image on macOS desktop application. 
But don't know how I can do it.
I've checked Example/Storage/MacOS, but found nothing there.
Please help me.

**Comment by paulb777** [comment]
One approach could be to start with the iOS Quick Start app at https://github.com/firebase/quickstart-ios/tree/master/storage and adapt it to macOS.

**Comment by morganchen12** [comment]
Loading the data from Firebase Storage should be exactly the same except for possibly a few extreme cases. For Mac programming, you should have a lot more freedom with downloading large images straight to memory instead of disk.

When displaying the image, you'll need to use [NSImage](https://developer.apple.com/documentation/appkit/nsimage/1519941-init) instead of UIImage.

Adding comprehensive Mac samples isn't high on our list of priorities, so this is unlikely to be added in the near future, but we're always happy to review external contributions. :)

**Comment by schmidt-sebastian** [comment]
Closing this issue for now as it has gone stale. We can re-open this if there is enough external interest.
