### ISSUE TITLE
FR: Build Firebase 5.15.0 binaries with Xcode 10.1

### ISSUE THREAD

**Issue by sraiteri** [firebase/firebase-ios-sdk#2221]
### Environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.15.0
  * Firebase Component: Analytics, Messaging
  * Component version: 5.15.0

### Describe the problem

Working for a team that is heavily reliant on Carthage, the experimental Cartage for Firebase SDK components (binaries) has been greatly appreciated :smile:.

We're looking at upgrading our project to Xcode 10.1 early in the new year, but notice that the latest binaries (5.15.0 versions) are built with Xcode 10, not Xcode 10.1.

Are there any plans to release Carthage binaries built for Xcode 10.1 soon?

**Comment by paulb777** [comment]
5.15.0 was actually built with Xcode 9.2.  We build Firebase with the earliest version that our infrastructure support since Apple typically supports linking binaries from older versions of Xcode but not from future versions.   This allows us to support a wider range of developers.

We will likely move to building with Xcode 10.1 when it becomes [required for App Store submission in March 2019](https://developer.apple.com/ios/submit/). 

In the meantime, we fully support usage of Xcode 10.1.

Why are you asking the question?  Are you seeing an issue with using the Xcode 9.2-built binaries with Xcode 10.1?

**Comment by sraiteri** [comment]
Thanks @paulb777, completely understand the requirement here to build with Xcode 9.2 to improve the compatibility range.

The March 2019 push for App Store updates to be built with at least iOS 12.1 SDK is exactly what we're starting to prepare for, but are having issues specifically with the Carthage dependencies:

## Firebase 5.15.0 Analytics & Messaging w/ Xcode 10.1

![image](https://user-images.githubusercontent.com/7417780/50494858-79a5c500-0a71-11e9-9cfe-1434b88e8e7f.png)

carthage bootstrap --platform iOS --no-use-binaries
```
*** Downloading binary-only framework firebase-analytics.json-5.15.0 at "https://host m:port/**/firebase-analytics.json-5.15.0.json"
*** Downloading binary-only framework firebase-messaging.json-5.15.0 at "https://host:port/**/firebase-messaging.json-5.15.0.json"
Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1).
```

Given the frameworks report as built with Swift 4.2, I had assumed that meant they were built using Xcode 10.0. They bootstrap perfectly fine in Xcode 10.0, but if I drop back to to Xcode 9.4.1, similar compatibility issues arise also:

## Firebase 5.15.0 Analytics & Messaging w/ Xcode 9.4.1

![image](https://user-images.githubusercontent.com/7417780/50495020-54fe1d00-0a72-11e9-9e85-3e55e3e74ccc.png)

carthage bootstrap --platform iOS --no-use-binaries
```
*** Downloading binary-only framework firebase-analytics.json-5.15.0 at "https://host m:port/**/firebase-analytics.json-5.15.0.json"
*** Downloading binary-only framework firebase-messaging.json-5.15.0 at "https://host:port/**/firebase-messaging.json-5.15.0.json"
Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).
```

Using component versions 5.12.0 are fine with Xcode 9.4.1.

**Comment by paulb777** [comment]
@sraiteri Thanks for the details. I'm not able to reproduce the issue with Xcode 10.1.  A few strange things:
- All of the Firebase code is binaries built from Objective C so Swift version should not matter. I suspect the "Incompatible Swift version" error may be coming from something other than Firebase. See https://stackoverflow.com/questions/46835129/carthage-build-failed
- I don't see any problem with it, but maybe there are issues related using the `--no-use-binaries` flag. Firebase is only distributed as binaries.
- Since you've modified/copied the json file paths from the ones listed at https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage, do you have the same issue with the original json paths?

**Comment by sraiteri** [comment]
@paulb777 - you were absolutely right on point #1. We had another external binary creep in last minute, and that ended up being the root cause of this issue (Carthage reporting here isn't great).

Dropping carthage dependencies back to just Firebase 5.15.0 components, I have no problems with carthage bootstrapping.

Thanks for your assistance on this one, sorry for the incorrect FR report!
