### ISSUE TITLE
GULAppDelegateSwizzler not accessible

### ISSUE THREAD

**Issue by jacobg** [firebase/firebase-ios-sdk#2343]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 5.16.0
  * Firebase Component: GoogleUtilities (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: 5.3.7

### [REQUIRED] Step 3: Describe the problem

Following the README.md instructions at to intercept certain AppDelegate methods:
https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/AppDelegateSwizzler/README.md

I try to declare `#import <GoogleUtilities/GULAppDelegateSwizzler.h>` in one of my app's classes. But there is an Xcode error that the file is not found. Indeed, GULAppDelegateSwizzler.h is a private header:
https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities.podspec

So how are we supposed to use GULAppDelegateSwizzler? Or alternatively, with GULAppDelegateSwizzler in place, how does my application do its own swizzling, e.g., in a cordova plugin?

**Comment by paulb777** [comment]
@tejasd Shouldn't `GoogleUtilities/GULAppDelegateSwizzler.h` be public since it is in the documentation?

@jacobg A private header in Xcode is still accessible if explicitly imported, so you should be able to work around the issue by adding `#import <GoogleUtilities/GULAppDelegateSwizzler.h>` to your source.  For example, see https://github.com/firebase/firebase-ios-sdk/blob/7c53489e03a2f2a4c4b3d1baad6796fb35719d3c/GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m#L15

**Comment by tejasd** [comment]
The assumption we had was that this would be used by other Cocoapods and not apps, which is why it was internal and not public (and internal is named private in cocoapods).

I'm still not sure what the use case is for apps (because apps control the app delegate, they can just add code to it rather than going through the swizzler?) but perhaps there's something we haven't thought about?

**Comment by jacobg** [comment]
Thanks for the replies. The use case is for a Cordova plugin.

I tried:
`#import <GoogleUtilities/GULAppDelegateSwizzler.h>`
But it doesn't find the file. If it's not on HEADER_SEARCH_PATHS, how will it find it?

**Comment by paulb777** [comment]
The GoogleUtilities framework should be in `HEADER_SEARCH_PATHS`

**Comment by paulb777** [comment]
What version of CocoaPods are you using and does your Podfile include `use_frameworks!`?

**Comment by paulb777** [comment]
I believe so - or add `"${PODS_ROOT}/Headers/Private/GoogleUtilities"` to `HEADER_SEARCH_PATHS`

**Comment by jacobg** [comment]
Ok thanks
