### ISSUE TITLE
Add tests for @testable

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#2367]
We should insure that Firebase continues to work in developers` tests and to prevent regressions like https://github.com/CocoaPods/CocoaPods/issues/8497

**Comment by ryanwilson** [comment]
Discussing this now, it seems like it's not a valid use-case to use `@testable import` with Firebase since there should be no need to access internal Firebase APIs. Also, `@testable` seems to be more Swift specific. 

Closing for now, but if anyone can provide an example where using `@testable` with Firebase makes sense, please comment or open a new issue.
