### ISSUE TITLE
Feature request: disable auto logging of in_app_purchase.

### ISSUE THREAD

**Issue by Igor-Poltavtsev** [firebase/firebase-ios-sdk#2435]
It's needed a way to stop tracking in_app_purchase automatically collected event on iOS.

**Comment by alexanderkhitev** [comment]
If this opportunity is made, it will be very good.

**Comment by HaseebYousaf** [comment]
This was the only reason we had to move a lot of our apps to other platform for analytics. Anyone who has access to crashlytics will have access to in-app purchase data. We have many layers of access rights. We don't want everyone to have access to financial data, on the team.

**Comment by sc0rch** [comment]
This issue is important and should be addressed.

**Comment by paulb777** [comment]
Tracked internally at b/130422135

**Comment by Igor-Poltavtsev** [comment]
Any chance get it soon?

**Comment by sc0rch** [comment]
179 days passed, just a reminder

**Comment by skuske** [comment]
Any update on this?

**Comment by HaseebYousaf** [comment]
I needed a team member to have access to crashlytics only and was not supposed to have access to in-app purchase and Admob data. I ended up creating a new role in IAM. It works but control of 'auto logging' would make things a lot easy.

**Comment by skuske** [comment]
I just found this through Google:

> "By default, the SDK collects in-app purchase information on iOS via the public transaction observer methods from Apple. On Android, this is enabled via Google Play In-app Billing. Both iOS and Android in-app purchase tracking can be turned off via the disableAutomatedInAppPurchaseReporting() method."

I am wondering how to use this method on iOS. I cannot find any further docs about that.

Found at the bottom of https://support.google.com/firebase/answer/6318039?hl=en

**Comment by paab72** [comment]
> I needed a team member to have access to crashlytics only and was not supposed to have access to in-app purchase and Admob data. I ended up creating a new role in IAM. It works but control of 'auto logging' would make things a lot easy.

Can you explain how you created the role in IAM?

**Comment by HaseebYousaf** [comment]
I quickly wrote down some steps for myself to remember, at that time. I am not sure if they will be work now. I have since moved my app away from Google eco-system. Here are the steps:


Firebase: Create user with Crashlytics access only

1. Open project in firebase
2. Select Settings->Permissions
3. Select Advanced Permissions
4. Select “Roles”
5. Search “Firebase Quality Admin”
6. Select “Create from Role”
7. Change title from “Custom Firebase Quality Admin” to “AFL Firebase Quality Admin”
8. Remove the permission:
    1. firebaseanalytics.resources.googleAnalyticsEdit
    2. firebaseanalytics.resources.googleAnalyticsReadAndAnalyze
9. Save
10. Goto IAM
11. Add user to the new role

**Comment by zhaoze1991** [comment]
any chance this issue could be fixed? thanks!

**Comment by Shani-Rabi** [comment]
> I just found this through Google:
> 
> > "By default, the SDK collects in-app purchase information on iOS via the public transaction observer methods from Apple. On Android, this is enabled via Google Play In-app Billing. Both iOS and Android in-app purchase tracking can be turned off via the disableAutomatedInAppPurchaseReporting() method."
> 
> Found at the bottom of https://support.google.com/firebase/answer/6318039?hl=en
> 
> Looks like this is a GADMobileAds method, and not a Firebase method, though.

Hi, Have you tried it? Did it work?

**Comment by Igor-Poltavtsev** [comment]
We haven't GADMobileAds in project, so looks disableAutomatedInAppPurchaseReporting() won't work for Firebase.

**Comment by touchberry** [comment]
Any updates on this? We want to onboard more team members to Firebase, but we don't need all of them to see revenue data.

**Comment by timbo-tj** [comment]
bump, our analytics data is at risk of being ruined by users who 'hack' IAP's. Our backend filters out invalid attempts by validating the receipt ID"s, but the attempts are logged to Firebase Analytics anyway so now our dashboard has a random day where we made 10,000% more than we usually make.. all thanks to one rouge user. It makes the chart illegible now since everything else (our 'valid' data) by comparison is crushed to near zero..

We'd like to report in_app_purchase manually once we validate the purchase on our backend

**Comment by slavasemeniuk** [comment]
+

**Comment by slavasemeniuk** [comment]
Any update on it?

**Comment by muneer-khan** [comment]
@paulb777 do you have any updates on this feature?

**Comment by htcgh** [comment]
This is not on the roadmap at this time. The use cases described above can be addressed by using features such as [data-restriction management](https://support.google.com/analytics/answer/9305587) or [user deletion](https://developers.google.com/analytics/devguides/config/userdeletion/v3). Closing this ticket for now, but feel free to provide more details on the underlying use cases not already described.
