### ISSUE TITLE
[Question] Serialize/Deserialize FIRFieldValue

### ISSUE THREAD

**Issue by businessengine** [firebase/firebase-ios-sdk#2511]
This is not a bug report just a question. Since enabling offline persistent made Firebase [too] slow with large collections, so we have to do caching ourselves. We need a way to serialize/deserialize special field values such as`FIRFieldValue.fieldValueForServerTimestamp`, `FIRFieldValue.fieldValueForArrayUnion`., etc, anyone how to do that? Thanks a lot.

**Comment by samtstern** [comment]
@businessengine what do you mean when you say "We need a way to serialize/deserialize special field values"?  Can you provide a code example of what you'd like to do and what's missing right now?

**Comment by businessengine** [comment]
We want to serialize NSDictionary with data such as `{name:"ABC, last_modified_at: FIRFieldValue.serverTimestamp}` as NSData via NSKeyedArchiver, or [FastCoding](https://github.com/nicklockwood/FastCoding), then save it in to a local file, later we read and deserialize the saved data to re-save into firebase, however the last_modified_at will be null.

**Comment by domness** [comment]
Yeh, it's a problem (and nice at the same time), that we get purely a [String: Any] back from the SDK for the data. That means converting to JSON fails when archiving as Timestamp can't be converted into the _seconds, _nanoseconds it's stored as.

**Comment by samtstern** [comment]
@wilhuff is there something simple we could be doing here to make the server timestamp sentinel value survive serialization?

@businessengine these `FieldValue` values are special sentinels and are not really "values", they represent operations that are performed server-side as part of the set/update.  I don't think we want to support people serializing them outside of our SDK, but it's possible that there's a low-hanging improvement we could make.

**Comment by morganchen12** [comment]
You can always convert those special values to your own sentinel values for serialization, but imo our long-term solution here should be to make Firestore not slow so that this workaround isn't needed.

**Comment by wilhuff** [comment]
So there's two issues in this thread: @businessengine is asking about `FIRFieldValue` types, and @domness is asking about `FIRTimestamp`. These are different and the news is mixed.

`FIRTimestamp` is a simple value type, whose public properties exactly represent the [type we store](https://github.com/protocolbuffers/protobuf/blob/791b86368778e21fd4936f0f8674daff44046dff/src/google/protobuf/timestamp.proto#L125). If your serialization framework supports reconstituting specific types it should be straightforward to add a category to `FIRTimestamp` to make it compatible.

The concrete types of the different kinds of `FIRFieldValue` are non-public, primarily because they could contain details specific to the implementation that we don't want to commit to publicly. These details are subject to change as we evolve the SDK.

Both Objective-C and Swift support extending types you don't control so you could apply that here. 
For example, we're working on formally supporting the Swift Codable protocol, and in that framework `Timestamp` ends up fully supported [through an extension](https://github.com/firebase/firebase-ios-sdk/pull/2229/files#diff-882d2177b95d585282ccd11e057ae2ce). You could similarly add a category or extension to support your serialization mechanism of choice.

For `FIRFieldValue` you'd likely need to write your own sentinel, and then as a post deserialization step convert to the Firestore sentinel. For example, with FastCoding, you could implement `-awakeAfterFastCoding` to return the Firestore sentinel.

As @morganchen12 says our goal is to make Firestore fast enough with large collections that you don't need to do this, but that's not happening immediately. In the meantime we can't really support external serialization through other frameworks.

**Comment by businessengine** [comment]
@wilhuff Thanks for the clarification, the FIRTimestamp is easy, the tricky one is the FIRFieldValue.fieldValueArrayXXXX(), but thanks for the suggestion we will try to follow your recommendation. @morganchen12 is there any rough timeline when we can get this awesome improvement?

**Comment by morganchen12** [comment]
@wilhuff can give a more comprehensive answer, but for now the answer is there's no timeline set.
