### ISSUE TITLE
Auth.signOut() does not recommend Auth.auth().signOut()

### ISSUE THREAD

**Issue by tristanbnewman** [firebase/firebase-ios-sdk#2558]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: _____
  * Firebase SDK version: _____
  * Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by tristanbnewman** [comment]
Xcode version: 10.1
Firebase SDK version: Latest as of 3/14/19
Firebase Component: Auth
Component version: Not sure


Steps to reproduce:
* import Firebase
* class{ Auth.signOut()}
* An error will flag that doesn't suggest the likely fix of Auth.auth().signOut()

**Comment by morganchen12** [comment]
This is a result of a Swift feature, and not something that would feasibly be corrected in Firebase. Basically what's happening is you're referencing the function as an instance member, and so Swift returns you the function itself as a result of this call without invoking it.

As a result, the line in your sample code should raise the following error recommending you use an instance of `Auth` instead of the type `Auth`:
```swift
let function = Auth.signOut() // Instance member 'signOut' cannot be used on type 'Auth'; did you mean to use a value of this type instead?
```

However, if you pass an instance of `Auth` into this declaration, it'll compile:
```swift
let function = Auth.signOut(Auth.auth()) // compiles without error
```

And, if you examine the type of `function`, you'll see it's `() throws -> ()`, which is the same as the instance member we're referencing (the `signOut` function).

I'll close this issue as `wontfix` for now, but please feel free to comment here if you have any questions.
