### ISSUE TITLE
FR: FIRDocumentReference initWithDocumentReference

### ISSUE THREAD

**Issue by 1amageek** [firebase/firebase-ios-sdk#2653]
### Introduction
When FIRDocumentReference conforms to Codable, initialization with Decodable is required.
However, because the initialization method is sealed, it can not conform well.
I understand why the initialization method is sealed. That is the proposal.

```objective-c
@interface FIRDocumentReference : NSObject

/** :nodoc: */
- (instancetype)init
    __attribute__((unavailable("FIRDocumentReference cannot be created directly.")));
```

### Proposed solution
I propose adding an initialization method that receives a FIRDocumentReference.

```objctive-c
- (instancetype)initWithDocumentReference:(FIRDocumentReference *)reference;
```

### Usage
``` swift
extension DocumentReference: Decodable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let documentReference: DocumentReference = try container.decode(DocumentReference.self)
        return DocumentReference(documentReference: DocumentReference)
    }
}
```

**Comment by 1amageek** [comment]
@paulb777 What do you think about this FR?

**Comment by wilhuff** [comment]
I have a design I'd like to share with you. Could you send me your email address to mcg@firebase.com?

**Comment by 1amageek** [comment]
@wilhuff OK I send.

**Comment by mikelehen** [comment]
Thanks for the feedback!  We actually have an existing issue discussing Codable support for Firestore over here: https://github.com/firebase/firebase-ios-sdk/issues/627  So if you have additional feedback, that would probably be the best place for it (or on the doc that @wilhuff has shared with you).

Note that DocumentReference is basically just a path to data and the actual Firestore data is stored in the DocumentSnapshot, and so we've been discussing Codable support in the context of DocumentSnapshot rather than DocumentReference.
