### ISSUE TITLE
build.swift script fails: "FrameworkMaker" does not contain a scheme named "FirebaseCore-macOS"

### ISSUE THREAD

**Issue by bcattle** [firebase/firebase-ios-sdk#271]
#### Environment:

  * Xcode version:  8.3.2 (8E2002)
  * Firebase SDK version: latest git commit b8f70da4ee4310b48addf046923a090d52839bef
  * Library version: iOS 10.3
  * Firebase Product: all / build system 

#### Problem:

Running `build.swift -all` fails with the error:
```
xcodebuild: error: The workspace named "FrameworkMaker" does not contain a scheme named "FirebaseCore-macOS". The "-list" option can be used to find the names of the schemes in the workspace.
```

#### Steps to reproduce:

```
$ git clone git@github.com:firebase/firebase-ios-sdk.git
$ cd firebase-ios-sdk/BuildFrameworks/
$ ./build.swift -all
``` 

#### Relevant Code:

Full command output is attached: 
[Terminal Saved Output.txt](https://github.com/firebase/firebase-ios-sdk/files/1304365/Terminal.Saved.Output.txt)

**Comment by paulb777** [comment]
./build.swift requires CocoaPods 1.3.1. If you can't upgrade CocoaPods, you could back out 76ac74b91560f3d56a02ffaab894c93c6d97f002

I'm going to close since we're unlikely to fix to work with old CocoaPod versions, since we're migrating the podspecs to CocoaPods 1.4 and its static_framework support in the near term.

**Comment by bcattle** [comment]
Thanks.

**Comment by paulb777** [comment]
Thanks for the report @bcattle!
