### ISSUE TITLE
Firestore switch to Caches Directory for tvOS

### ISSUE THREAD

**Issue by mcdonell-miller** [firebase/firebase-ios-sdk#2735]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * tvOS version: 12.1.2
  * Firebase SDK version: Newest commit https://github.com/firebase/firebase-ios-sdk/commit/45909c3ceb2318cd537adbd6930ba004d809a729
  * Firebase Component: Firestore

#### Steps to reproduce:

I tried to get Firestore running on an actual tvOS device. The Firestore startup fails at the moment since it uses the Documents directory, like iOS.

#### Relevant Code:

https://github.com/firebase/firebase-ios-sdk/blob/45909c3ceb2318cd537adbd6930ba004d809a729/Firestore/Source/Local/FSTLevelDB.mm#L397-L413

Switching to the NSCachesDirectory allows it to start & I could read from my Cloud Firestore.
However, I'm not sure how long the db would survive in the Caches directory...

**Comment by rsgowman** [comment]
Yeah, it looks like TARGET_OS_TV implies TARGET_OS_IPHONE (hence why it's not hitting that `#error` case.)

I don't know anything about tvOS, but it looks like writing to the caches directory is probably the right thing. It might be periodically deleted (while the app is not running), but it sounds like this is the norm on tvOS. Firestore should be able to recover from this, though it would imply having to fetch everything from the server after a cache purge, instead of being able to use the local disk.

We don't yet support tvOS, but as it happens, @wilhuff is actively working on it. I'll assign this issue to him; he should be able to give you a more intelligent response.

**Comment by paulb777** [comment]
See #2496 for the comparable change in Firebase/Messaging

**Comment by wilhuff** [comment]
Thanks for trying this out. Unfortunately the simulator doesn't catch this :-(.

We don't really have much of a choice about where to put this file. My best advice is that on tvOS, keep the cache size small to avoid eviction (see [`cacheSizeBytes`](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/FirestoreSettings#/c:objc(cs)FIRFirestoreSettings(py)cacheSizeBytes) for how to do this).
