### ISSUE TITLE
Remove Firestore deprecated APIs

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#2762]
There are two APIs that could be removed at this breaking change:

https://github.com/firebase/firebase-ios-sdk/blob/da3c019f8e5954bc727a379ce3cb1ef41f546cda/Firestore/Source/Public/FIRFirestore.h#L140

and 

https://github.com/firebase/firebase-ios-sdk/blob/da3c019f8e5954bc727a379ce3cb1ef41f546cda/Firestore/Source/Public/FIRFirestoreSettings.h#L67

@wilhuff were you hoping to remove these at this time or wait until next breaking change?

**Comment by wilhuff** [comment]
I'm actually thinking about undeprecating the first one because it's just so easy to recommend it. Also there are tons of issues we've posted where we've asked for people to collect logs that way so there's negative value in removing it.

The second one only became deprecated with the 1.0 release which wasn't too long ago. It's not really hurting us to leave it in place (the code to handle it is minor and fairly isolated) so I'm inclined to leave it rather than push aggressively.

That leaves me with no changes to make so I think this task is done! (... unless you disagree 😃)

**Comment by mikelehen** [comment]
FWIW- I'm pretty sure support still actively points people at the deprecated logging method.

**Comment by paulb777** [comment]
Removing from Firebase 6 milestone.

**Comment by ryanwilson** [comment]
Sounds good to me, thank you! Just wanted to make sure nothing slips through and we miss our one time a year removal.

Good to know about the logging, perhaps we can provide a better solution overall for enabling/disabling specific SDKs.
