### ISSUE TITLE
How to disable trash console logs

### ISSUE THREAD

**Issue by agordeev** [firebase/firebase-ios-sdk#2774]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2
  * Firebase SDK version: 5.19.0
  * Firebase Component: Firestore
  * Component version: 5.19.0

### [REQUIRED] Step 3: Describe the problem

Every time I run the app from Xcode I can see these trash logs in console output:

```
2019-04-09 10:04:47.530964+0300 App[19647:22338843] 5.19.0 - [Firebase/Firestore][I-FST000001] Committing transaction: <LevelDbTransaction Release query: 29 changes (242 bytes):
  - Put [document_target: path=events/0CkDEcBj4piqWvZUtc4l target_id=0] (1 bytes)
  - Put [document_target: path=events/0f5br5jh100vtslfqam37ifmsg target_id=0] (1 bytes)
  - Put [document_target: path=events/4qe7bnt8b8gael2896fqug9dtr target_id=0] (1 bytes)
  - Put [document_target: path=events/51m5a6v32sjil6ekjr13f1hfac target_id=0] (1 bytes)
  - Put [document_target: path=events/7Y2rEpBxSBut0TaH50Im target_id=0] (1 bytes)
  - Put [document_target: path=events/7uthn24gbsk0ml0pd56gni1iqj target_id=0] (1 bytes)
  - Put [document_target: path=events/9CpzE9gwzYyDDywOY23C target_id=0] (1 bytes)
  - Put [document_target: path=events/AAC5Xfc0nRoPqkbhdWMN target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAADQnuDMAAAAe5hMTQg960mfJHlCjfY1IwAAANCe7IoAAAA= target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAAC0RUxYAAAA target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAACsSmtvAAAA target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAAD__IjCAAAA target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAQPu4jEAAAA= target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAQPu4jIAAAA= target_id=0] (1 bytes)
  - Put [document_target: path=events/AQMkADAwATMwMAItZGEyMy02MDE3LTAwAi0wMAoARgAAA0mCRcnSlRNKi3MT8obCYGcHAHuYTE0IPetJnyR5Qo32NSMAAAIBDQAAAHuYTE0IPetJnyR5Qo32NSMAAQPu4jQAAAA= target_id=0] (1 bytes)
  - Put [document_target: path=events/BVjDoKjarBXEJYpTXUec target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:05A16B09-B02D-4933-B5EB-8AC09638576E target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:05A16B09-B02D-4933-B5EB-8AC09638576ERID=565170300 target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:4AF15EED-15E3-472E-A2FE-53A7AC5BD54A target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:8CF91408-64EA-4A0B-8275-7CB79740E446 target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:95A457D0-C5C0-4E0E-A9DF-73FDD4056123 target_id=0] (1 bytes)
  - Put [document_target: path=events/D2BC9870-E5EE-41DF-ABE9-E98F68CA2C19:C30486AD-BA4E-4E83-9605-0F963329FDF8 target_id=0] (1 bytes)
  - Put [document_target: path=events/EKphRhlnCrS9GJengH0c target_id=0] (1 bytes)
  - Put [document_target: path=events/XGwcnFITUADkfHtfTLan target_id=0] (1 bytes)
  - Put [document_target: path=events/ZYwXF5vr3RZJD5fzVDkl target_id=0] (1 bytes)
  - Put [document_target: path=events/Zmca4F5NJu6pA8kr0QqN target_id=0] (1 bytes)
  - Put [document_target: path=events/l3KOyQLuwnOBNKxZ7A6T target_id=0] (1 bytes)
  - Put [target: target_id=12] (195 bytes)
  - Put [target_global:] (20 bytes)>
2019-04-09 10:04:47.531903+0300 App[19647:22338843] 5.19.0 - [Firebase/Firestore][I-FST000001] WatchStream (7fa1b550c770) unwatch: <GCFSListenRequest 0x60000100e4c0>: {
    database: "projects/xxx/databases/(default)"
    remove_target: 12
}
2019-04-09 10:04:47.531982+0300 App[19647:22338843] 5.19.0 - [Firebase/Firestore][I-FST000001] WatchStream (7fa1b550c770) headers (whitelisted): date: Tue, 09 Apr 2019 07:04:45 GMT
2019-04-09 10:04:47.532069+0300 Ava[19647:22338843] 5.19.0 - [Firebase/Firestore][I-FST000001] WatchStream (7fa1b550c770) response: <GCFSListenResponse 0x600001519200>: {
    target_change {
      target_change_type: REMOVE
      target_ids: 10
    }
}
```

How do I disable them? 

`FirebaseConfiguration.shared.setLoggerLevel(.min)` seems to have an effect only for Firebase analytics component.

I also believe such debug logs should be disabled by default. There's no need to see them in 99.9% cases for SDK users.

**Comment by agordeev** [comment]
@rsgowman thanks for your answer. The method you're referencing to is deprecated:

```
/** Enables or disables logging from the Firestore client. */
+ (void)enableLogging:(BOOL)logging
    DEPRECATED_MSG_ATTRIBUTE("Use FirebaseConfiguration.shared.setLoggerLevel(.debug) to enable "
                             "logging.");
```

I'm calling `FirebaseConfiguration.shared.setLoggerLevel(.min)` instead.

I'm also getting these:

```
[Firebase/Analytics][I-ACS023073] Debug mode is enabled. Marking event as debug and real-time. Event name, parameters:
....
```

It says Debug mode is enabled but why?

**Comment by rsgowman** [comment]
It's actually about to become un-deprecated: https://github.com/firebase/firebase-ios-sdk/pull/2773 :)  But never mind, I think FirebaseConfiguration.shared.setLoggerLevel is better, so keep using that. (They effectively do the same thing.) But search your codebase for both; if either is setting the log level to debug, it'll override previous invocations of the other.

Failing that, you could set a breakpoint here: https://github.com/firebase/firebase-ios-sdk/blob/e3cafd4dfd1079cca0f0393c73813839c31f03fb/GoogleUtilities/Logger/GULLogger.m#L106. That's where the log level is actually set. If it triggers, you can inspect the stacktrace to see what's causing it.

Another worthwhile breakpoint location is in the GULLoggerForceDebug function: https://github.com/firebase/firebase-ios-sdk/blob/e3cafd4dfd1079cca0f0393c73813839c31f03fb/GoogleUtilities/Logger/GULLogger.m#L89.

If that *still* gets you nowhere, and if you're able/willing, see if you can create a minimum example that reproduces this behaviour and I'll take a look and see if I can figure out what the problem is.

**Comment by agordeev** [comment]
<img width="1042" alt="Screenshot 2019-04-12 at 10 26 52" src="https://user-images.githubusercontent.com/2883524/56019686-f5b8d580-5d0d-11e9-9c6d-ba9427646475.png">

After inspecting `sFIRLoggerUserDefaults` I noticed these values:

```
    "/google/firebase/debug_mode" = 1;
    "/google/measurement/debug_mode" = 1;
```
Looks like these are causing the issue? How to disable debug mode?

**Comment by rsgowman** [comment]
Given your stack trace, I think these may be coming from the 'defaults' system... or possibly your program arguments. (They're tightly related; the relevant program arguments are persisted into the defaults system.).

So lets checks your program arguments.

Open your app's schema, and look for any settings under the 'arguments passed on launch' section. (https://help.apple.com/xcode/mac/10.0/#/dev3ec8a1cb4). In particular, if you see something like `-FIRAnalyticsDebugEnabled` or `-FIRDebugEnabled` that would cause this issue. If either/both of these appear, then disable them (or delete them entirely.)

Removing/disabling these arguments is necessary, but not sufficient (because they're persisted via the defaults system.) So regardless of whether they were there are not, also add the following arguments: `-noFIRDebugEnabled` and `-noFIRAnalyticsDebugEnabled`. This should both disable the 'forced' debug mode, as well as clear the setting, if it had been set previously. (In fact, you can even see the code that does this in your screen shot.)

**Comment by agordeev** [comment]
Adding `-FIRDebugDisabled` argument and cleaning the project did the trick.

@rsgowman thanks for helping!
