### ISSUE TITLE
Firestore - gRPCCertificates.bundle: No such file or directory

### ISSUE THREAD

**Issue by mharrisweb** [firebase/firebase-ios-sdk#2898]
* Xcode version: 10.1
  * Firebase SDK version: 5.20.2
  * Firebase Component: Firestore

### Describe the problem

Cannot install Firestore pod, get the error:

```
CpResource /Users/macbookpro2018/sites/ejected-calendar/ios/gRPCCertificates.bundle /Users/macbookpro2018/Library/Developer/Xcode/DerivedData/rgcalendar-bfjzhbiwxklgqmchjhbjlpniuqst/Build/Products/Release-iphonesimulator/rgcalendar.app/gRPCCertificates.bundle (in target: rgcalendar)
    cd /Users/macbookpro2018/sites/ejected-calendar/ios
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -strip-debug-symbols -strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -resolve-src-symlinks /Users/macbookpro2018/sites/ejected-calendar/ios/gRPCCertificates.bundle /Users/macbookpro2018/Library/Developer/Xcode/DerivedData/rgcalendar-bfjzhbiwxklgqmchjhbjlpniuqst/Build/Products/Release-iphonesimulator/rgcalendar.app

error: /Users/macbookpro2018/sites/ejected-calendar/ios/gRPCCertificates.bundle: No such file or directory
```

#### Steps to reproduce:

Install pod 'Firebase/Firestore', build project.

**Comment by morganchen12** [comment]
Are you able to repro this in the Firestore sample app?

**Comment by mharrisweb** [comment]
No, I can setup a basic ios app with Firestore. My app also works on Android, its just ios I get the error.

**Comment by wilhuff** [comment]
Hi @mharrisweb, I'm able to create a `Podfile` containing just the `Firebase/Firestore` pod and things work as expected so there must be something else going on that's more specific to your situation.

The best way to make any forward progress on this is to make and share a minimal example that shows the issue. Often the effort of trying to strip things out of your configuration ends up helping to pinpoint what's going on.

Alternatively, a set of reproduction steps that work from nothing would work too. As it stands your steps to reproduce don't yield the problem you're describing.

This isn't an issue we've seen before so I don't have much to offer otherwise.
