### ISSUE TITLE
Linker command failed with exit code 1 (use -v to see invocation) for FIrebase 4.0.0

### ISSUE THREAD

**Issue by yurevich1** [firebase/firebase-ios-sdk#29]
Please, read this question.

https://stackoverflow.com/questions/43809514/clang-error-linker-command-failed-with-exit-code-1firebase

In my case the environment is

Xcode version: 8.3
Firebase SDK version: 4.0
Library version: 4.0
Firebase Product: analytics, admob

In my case, Firebase 4.0.0 fails for both manual and cocoapods variants of integration.
without '-ObjC' ('-force_load') it fails with `fira_UTF32Length unrecognized selector sent to instance`
with '-ObjC' it fails with `clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

What is it? Is it possible to make it work?

**Comment by morganchen12** [comment]
Can you post the full `ld` invocation? `exit code 1` is not very specific. Usually this is a result of project misconfiguration, so posting your project here (or a sample project that reproduces the issue) is very helpful to us.

**Comment by yurevich1** [comment]
I've send a sample of the project tofirebase support team.
This is the only what I have in the log. No more detailed information! This is the core of the problem.

I've found that if I use any other cloned framework (Swift) in xCode workspace then the linker crashes.

But if I use only Firebase (+ Cocoapods frameworks) it compiles and execuses.

It is needed to use '-ObjC' (or '-force_load') flag that prevents to build the project.

I will write what the Firebase support will answer to me.

**Comment by morganchen12** [comment]
You should be able to get the full invocation using Xcode's left pane navigator and clicking on the build that failed. Can you post your support ticket number here so I can look at your project?

**Comment by yurevich1** [comment]
[4-9489000017650 this is the ticket number. 
i say no more detailed information when i tap on the error text in the left panel. just this name of the error. nothing more. thats why i've wrote to support.

**Comment by morganchen12** [comment]
It turns out the full error is 

```
ld: library not found for -lGBDeviceInfo
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

For reference, the error can be found in the full log output of your build's invocation, not the error pane.

Upon looking at your project, there are a number of issues. 
-  I had to remove a bunch of unused libraries (like GBDeviceInfo and RNCryptor) out of your project's Link Binary With Libraries phase. In general if you're using CocoaPods, you shouldn't be also integrating dependencies manually. Manage everything through CocoaPods.
- Your project is written in Swift, but `use_frameworks!` wasn't specified in your Podfile.
- Your project was overriding CocoaPods' header search paths with hard-coded absolute paths, so your project was not portable to any computer outside of your own and caused Xcode to not find framework modules in some cases.

I've sent back a working project in the case you've submitted. Take a look at the git diff in that project for more details.

**Comment by yurevich1** [comment]
Please, read my ticket answer.

The project you received was not prepared enough. I sent wrong project. Execuse me.
Nevertheless, wonder suggestions. Thanks.

**Comment by morganchen12** [comment]
The solution offered with the old API should work just fine with the new one after running `pod update`. You'll find in the zip I sent back to you I moved the Firebase dependencies to CocoaPods instead of using standalone binaries, so you should have an easier time managing their versions once you've familiarized yourself more with CocoaPods.

The new project you've sent has almost exactly the same issues as the old one, and I encourage you examine the solutions presented there.

**Comment by yurevich1** [comment]
Hello.
When I wrote the last email Firebase was 3.x in CocoaPods. In the middle of the last week your team updated Specs and published 4.x for everyone. Ok, I've found that do you mean. I've remove wrong unused linker flags: '-framework <SomeUnusedFrameWork>'.
Nonetheless, it fails due to the other reason : "duplicate symbols for architecture x86-64"

similar to this question: https://stackoverflow.com/q/34084718/1979882

Namely, if I use Firebase and -ObjC flag.
So, it fails at runtime without -ObjC flag and fails while linking with -ObjC.

I will send an example to your email as soon as possible.

**Comment by morganchen12** [comment]
You've linked one of your static dependencies into your project multiple times. Look through your dependencies, identify the duplicate, and remove it.

What versions of CocoaPods and Xcode are you using?

**Comment by yurevich1** [comment]
It seems I've found the error.

1. I've got my own several static libs. Which depented like this: A > B (in B lib A is used) > MajorProject (in MajorProject both lib A and lib B are used). Everywhere in 'Link Binary With Libraries' were attached all of them: in B was attach A, in MajorProject B and A. So, it failed. I just removed libraries from 'Link Binary...'.

2. Google Analytics failed with the same error if I ad `libAdIdAccessLibrary`. I've just removed `libAdIdAccessLibrary.a` from `Link Binary`.
    /Users/admin/Documents/GoogleIDFASupport-3.14.0/libAdIdAccessLibrary.a(TAGActualAdIdAccess.o)
    /Users/admin/Documents/GoogleAnalyticsServicesiOS_3.17/libAdIdAccess.a(TAGActualAdIdAccess.o)

If somebody faced the same issue:
Choose `View > Navigator > Show Report Navigator`. It have to show your error (log).

Now It works. Thanks a lot! I suggested me to use report navigator. This is obvious but I did not tried.
