### ISSUE TITLE
memory leak:  FirebaseApp.configure()

### ISSUE THREAD

**Issue by kartikartik** [firebase/firebase-ios-sdk#3108]
![Screenshot 2019-05-28 at 4 39 47 PM](https://user-images.githubusercontent.com/28666702/58529441-50dc5400-81f8-11e9-9599-b4e012d5def5.png)

**Comment by kartikartik** [comment]
i install following pods 
       
 pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Messaging'
pod 'Crashlytics'

& configure all the code

**Comment by ryanwilson** [comment]
@kartikartik thanks for the report. The small leak appears to occur in `FirebaseCrash` (pulled from `Firebase/Crash`) which has been deprecated and is no longer in the `Firebase` pod (it's only available for Firebase 5.X and below, we've recently released Firebase 6).

I've confirmed that the leak no longer occurs when removing `pod 'Firebase/Crash'` from the Podfile.

This is the same for #3104, #3105, #3106, and #3107. Since `FirebaseCrash` is deprecated, we won't be able to make a fix for the small memory leak and suggest using Crashlytics (which you already are, which is great 😄).

Thanks again, let us know if you run into anything else!
