### ISSUE TITLE
[QUESTION] Query with predicate

### ISSUE THREAD

**Issue by filipealva** [firebase/firebase-ios-sdk#3113]
Hey guys,

I appreciate that the SDK has support for querying based on `NSPredicate`, but since Firestore has no explicit `id` field on the document, and we don't have access to the literal value of `FieldPath.documentID()`, how should we use `queryWithPredicate` for querying a document by its id? 

Thanks in advance! 

----

EDIT: Just figured out that the field is `__name__` u.u

So I'm updating the question for:

Is it safe to use this explicit value while querying using an `NSPredicate`?

Is it possible that you guys change this field name one day? Would it be a good idea to expose this field on `FieldPath.documentID()` so we can reference it instead of hardcoding the field name?

**Comment by filipealva** [comment]
I'm sad that we as developers struggle to find this kind of basic information :(

**Comment by wilhuff** [comment]
Sorry about the difficulty you ran into.

`__name__` is a stable identifier that’s a part of the protocol and a committed part of the API surface, not just in iOS but all APIs including REST. You can safely rely on this not changing.

We’ve struggled with whether/how to expose this. You’ve pretty much hit on the only case where it’s useful though and it would otherwise be confusing. On balance we feel the confusion isn’t worth it.
