### ISSUE TITLE
firestore-user-presence ionic3

### ISSUE THREAD

**Issue by aramkumar06** [firebase/firebase-ios-sdk#3252]
Need firestore-user-presence in ionic3

**Comment by ryanwilson** [comment]
Hi @aramkumar06 - can you elaborate on this please? Are you using the native iOS SDK, or a plugin like [this one, linked on the Ionic website](https://ionicframework.com/docs/native/firebase)?

**Comment by aramkumar06** [comment]
npm install angularfire2 firebase --save
https://angularfirebase.com/lessons/user-presenece-system-in-realtime/

**Comment by wilhuff** [comment]
There is no presence system in Firestore at all, let alone in ionic3. Due to the way our connections to the backend work we have no good way of exposing this information. Additionally, a key feature of the Realtime Database's presence system is the ability to buffer changes you want to apply when the connection is lost. In Firestore connections aren't very long lived so if we implemented an equivalent feature it wouldn't be all that useful.

If you need presence, right now your best bet is the Realtime Database. If you still want to use Firestore, we have the following advice for how to meld the two systems together: https://firebase.google.com/docs/firestore/solutions/presence
