### ISSUE TITLE
FR: Set timeout interval for detectTextRecognizer

### ISSUE THREAD

**Issue by XiongbinZhao** [firebase/firebase-ios-sdk#3397]
I want to set a timeout interval when detecting text in case of slow network.
But I could not find a way to set the timeout interval.

**Comment by morganchen12** [comment]
cc @miworking @ulukaya

**Comment by ulukaya** [comment]
For now you can create the timeout on the client side and disregard the response if it comes late, but I've filed a FR internally. b/138134555

**Comment by morganchen12** [comment]
The Firebase ML Kit barcode API has been deprecated since all on-device ML Kit features are no longer a part of Firebase. You should move to using the Google standalone ML Kit instead by following the migration guide [here](https://developers.google.com/ml-kit/migration).

We won't be considering adding new features to the deprecated pods.
