### ISSUE TITLE
FirebaseAnalyticsBinary 6.5.0 missing FirebaseCoreDiagnostics.framework

### ISSUE THREAD

**Issue by mlmcgrath** [firebase/firebase-ios-sdk#3406]
#### Environment

  * Xcode version: 10.2.1
  * Firebase SDK version: 6.5.0
  * Firebase Component: Analytics
  * Component version: 6.5.0

#### Steps to reproduce:

Downloading the most recent version of Analytics via Carthage results in a missing framework error for `FirebaseCoreDiagnostics`. From the [version JSON](https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json), in [version 6.5.0](https://dl.google.com/dl/firebase/ios/carthage/6.5.0/Analytics-fe0669fafb68cf16.zip) there is no FirebaseCoreDiagnostics framework. This file is present in [version 6.3.0](https://dl.google.com/dl/firebase/ios/carthage/6.3.0/Analytics-ecf84ca9f3b2ce64.zip), and appears to have been left out by mistake.

In the meantime, I have used the framework from 6.3.0.

**Comment by paulb777** [comment]
@mlmcgrath Thanks for the report. We're in the middle of moving the CoreDiagnostics framework from FirebaseAnalytics to FirebaseCore for Firebase 6.6.0 and a commit happened a bit too early.  This will be fixed in the next release.

In the meantime, the workaround of using `CoreDiagnostics.framwork` from a recent release is a good workaround.

**Comment by mlmcgrath** [comment]
Perfect, cheers!
