### ISSUE TITLE
Why FirebaseAnalytics has three static vendors frameworks as dependencies?

### ISSUE THREAD

**Issue by Beniamiiin** [firebase/firebase-ios-sdk#3504]
I'd like to know why FirebaseAnalytics has three static vendors frameworks as dependencies even though FirebaseAnalytics work with iOS 8+? Maybe we can convert these three static vendors frameworks to dynamic?

**Comment by paulb777** [comment]
CocoaPods has [a proposal ](https://docs.google.com/document/d/1lr2mHkwhNha5_0Wfa_pYL51MAxoro0LBxx_DUzuSu0Y/edit) to enable Podfile's to control static versus dynamic linking individually instead of all or none.  Once that is implemented, we should be able to add support to let the Podfile determine if the Analytics deps are linked statically or dynamically. 

In the meantime, we're hesitant to change Firebase apps to have the run-time penalty of dynamic linking.

Why do you ask?

**Comment by Beniamiiin** [comment]
I'm trying to find a way to use FirebaseAnalytics as dynamic frameworks. Maybe do you know how can I do it?

**Problem**

I have an application and two frameworks(_Platform_ and _Analytics_). Both of them are a dependency of the application. I connect `Firebase/Core` to the _Platform_ framework and `Firebase/Analytics` to _Analytics_ framework. All of this I do via cocoapods.

When I start my app I get a lot of warnings like this:
```
objc[76462]: Class APMPBStringFilter is implemented in both
/Users/User/Library/Developer/Xcode/DerivedData/App-
bvnjcqdldfagvubbfefrbqmmmdfx/Build/Products/Debug-
iphonesimulator/Analytics.framework/Analytics (0x10ce95160) and
/Users/User/Library/Developer/Xcode/DerivedData/App-
bvnjcqdldfagvubbfefrbqmmmdfx/Build/Products/Debug-
iphonesimulator/Platform.framework/Platform (0x10cb048c0).
One of the two will be used. Which one is undefined.
It happens because of FirebaseCore and FirebaseInstanceID are static frameworks.
These frameworks are dependencies of Firebase/Core and Firebase/Analytics.
```

**What I've already tried**
If I understand correctly It happens because `Firebase/Core` and `Firebase/Analytics` are static frameworks. So I tried to update pod specs of both pods to set `static_framework  = true`, but it didn't solve the problem, because of static vendor frameworks of `FirebaseAnalytics`.

**Comment by paulb777** [comment]
Since `FirebaseAnalytics` is a static framework, any frameworks that depend on it must also be static.  It is only released as binary, so there is not a way to use it as a dynamic framework.

BTW, `Firebase/Core` and `Firebase/Analytics` are equivalent subspecs of the [Firebase pod](https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/6.5.0/Firebase.podspec.json).

**Comment by paulb777** [comment]
Closing for now, but can continue to discuss if more questions.
