### ISSUE TITLE
Not able to install Firebase as static framework using cocoapods 

### ISSUE THREAD

**Issue by ankitgarg1mg** [firebase/firebase-ios-sdk#3736]
* Xcode version: 10.2
  * Firebase SDK version: 6.1.0
  * Firebase Component: Analytics, Performance, ABTesting

I am trying to install Firebase as static using cocoapods. For this, I removed flag use_framewroks!. Remains pods are installed as static but not firebase.
```

**Comment by paulb777** [comment]
The Firebase pods are always statically linked. The closed source pods will always be static frameworks since they're delivered in binary form. The open sourced pods will be[ static frameworks ](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseABTesting.podspec#L28) if `use_frameworks!` is in the Podfile. They'll be built as static libraries if it's not.
