### ISSUE TITLE
Crash caused by swizzling in GoogleUtilities

### ISSUE THREAD

**Issue by swillsea** [firebase/firebase-ios-sdk#3792]
### Describe your environment

  * Xcode version: 11.0 beta 6
  * Firebase SDK version: 6.5.0
  * Firebase Component: GoogleUtilities
  * Component version: 6.2.5

#### Steps to reproduce:

This code was added to `GULSwizzledObject.m` in https://github.com/firebase/firebase-ios-sdk/pull/3300:

```
- (void)dealloc {
  // We need to make sure the swizzler is deallocated after the swizzled object to do the clean up
  // only when the swizzled object is not used.
  GULObjectSwizzler *swizzler = nil;
  BOOL isInstanceOfGeneratedClass = NO;

  @autoreleasepool {
    Class generatedClass = [self gul_class];
    isInstanceOfGeneratedClass = object_getClass(self) == generatedClass;

    swizzler = [[self gul_objectSwizzler] retain];
    [GULObjectSwizzler setAssociatedObject:self
                                       key:kSwizzlerAssociatedObjectKey
                                     value:nil
                               association:GUL_ASSOCIATION_RETAIN_NONATOMIC];
  }

  [super dealloc];

  [swizzler swizzledObjectHasBeenDeallocatedWithGeneratedSubclass:isInstanceOfGeneratedClass];
  [swizzler release];
}
```
We're seeing a crash at `[super dealloc]` in iOS 13 triggered by the deinit call of a UIViewController class that holds a reference to a [custom WKWebView subclass](https://gist.github.com/novemberfiveco-gists/798e3cbb80b0d1a9f75d6ddfd0f87071). 

In iOS 12, we've seen that we can continue through the rest of this dealloc method above, but our app then crashes immediately after. 

When reverting to Firebase 5.19.0, our crashes disappeared. The crashes also disappeared when we replaced our custom WKWebView with the default WKWebView class. 

While we've been able to revert to the default WKWebView class to solve our own particular issue, other users are may be seeing similar crashes. The stack trace on iOS 12 wasn't giving us enough information to track down the issue:
[Stack Trace.txt](https://github.com/firebase/firebase-ios-sdk/files/3581483/Stack.Trace.txt)

iOS 13 was a little more helpful.
[iOS13 Stack Trace.txt](https://github.com/firebase/firebase-ios-sdk/files/3584986/iOS13.Stack.Trace.txt)

**Comment by maksymmalyhin** [comment]
@swillsea Thank you for the detailed bug report!

As far as I can see, the custom `WKWebView` subclass is swizzled by `Firebase Performance` because the class [declares `URLSessionTaskDelegate` conformance](https://gist.github.com/novemberfiveco-gists/798e3cbb80b0d1a9f75d6ddfd0f87071#file-wkcookiewebview-swift-L182). Based on this I can suggest following **temporary workaround options:**
1. Avoid `WKWebView` conformance to `URLSessionTaskDelegate` directly in your subclass. Prefer using a separate private class confirming to `URLSessionTaskDelegate` for this instead.
2. Temporary remove `Firebase Performance` from dependencies if other options are not working for you. 

There is ongoing work to make network performance tracking safer for all cases (tracked internally at b/127764622) but it may take some more time to be completed.

@swillsea I would like to ask couple details that will help us to fix the this particular case:
1. Is the crash reproducible 100% times? 
2. If you have a simple app where the crash is reproducible? 

cc @visumickey

**Comment by swillsea** [comment]
@maksymmalyhin Thank you for both workarounds! We are making some changes to our WKWebView's cookie handling, so this may still be helpful for us even though we removed the specific implementation that declares `URLSessionTaskDelegate` conformance. 

As for your questions, it was definitely reproducible 100% of the time. I don't have a simple app ready for you at the moment, but I could try to put something together if you think it would help.

**Comment by maksymmalyhin** [comment]
@swillsea The app will definitely save us some time on additional questions because we will have everything we need to debug the issue and test fixes, so it is highly appreciated.

**Comment by swillsea** [comment]
@maksymmalyhin I've been unable to reproduce the issue on a sample app, somewhat frustratingly. If you do decide to close the ticket out, I understand. At least having the discussion here may help other users in the future (assuming it wasn't specific to our app only)

**Comment by maksymmalyhin** [comment]
@swillsea Thank you for the update. Let's close the ticket so far. Feel free to reopen it with more details.
