### ISSUE TITLE
Is the latest release version wrong?

### ISSUE THREAD

**Issue by filipealva** [firebase/firebase-ios-sdk#3827]
Guys, I'm trying to get all my pods on the latest version and I'm suffering to understand how versioning semantics work for Firebase. 

Let me give one example, the latest release on Cocoapods and on GitHub is `6.8.1` as seen below:

![Screen Shot 2019-09-11 at 15 35 06](https://user-images.githubusercontent.com/6117280/64725147-5cebd900-d4aa-11e9-8281-ffb11af7a7be.png)

On this release you guys refer to the Firebase iOS Release notes, but when I go there the latest version is `6.7.1`

![Screen Shot 2019-09-11 at 15 40 20](https://user-images.githubusercontent.com/6117280/64725194-7bea6b00-d4aa-11e9-979c-801d6b6eb89b.png)

Cocoapods couldn't even find a reference for `6.7.1`, btw. 

To make things even more confuse, the latest release note for `6.7.1` is about Cloud Firestore, but the latest version of `Firestore` for iOS is actually `1.5.0`. 

I'm struggling to update everything here and I'm sure I'll get to a point where everything works, but the issue is: it doesn't makes sense for me at all.

Am I missing something? There's a place that states the current version for each "sub" framework of Firebase? 

Thanks in advance!

**Comment by ryanwilson** [comment]
Hi @filipealva - sorry for the confusion. This stems from a variety of factors, let me try to break each one down:

> On this release you guys refer to the Firebase iOS Release notes, but when I go there the latest version is 6.7.1

This appears to be a bug with publishing our release notes - there are a few releases missing (including `6.8.1`). We noticed it earlier today and it should be resolved shortly, hopefully!

> Cocoapods couldn't even find a reference for 6.7.1, btw.

> To make things even more confuse, the latest release note for 6.7.1 is about Cloud Firestore, but the latest version of Firestore for iOS is actually 1.5.0.

Both of these stem our CocoaPods setup: we have an "umbrella" [Firebase Pod](https://cocoapods.org/pods/Firebase) that has subspecs for each part of Firebase. This way you can set your Podfile up with `Firebase/Firestore`, `Firebase/Storage`, etc meaning the `Firestore` subspec and `Storage` subspec of the same `Firebase` pod.

We do this for a couple of reasons, but the primary reason is to encapsulate that all versions defined in the podspec are validated to play nicely together, and have appropriate versions.  For example, `Firebase 6.8.1` includes [`Firestore 1.5.0` and all patch bumps](https://github.com/CocoaPods/Specs/blob/5809715b757e74c237b0a81ffe4d2caa39103049/Specs/0/3/5/Firebase/6.8.1/Firebase.podspec.json#L251).

Re: not finding a CocoaPods reference for 6.7.1 - another interesting side-effect. We deploy the Firebase SDKs via CocoaPods, a Zip file, and with Carthage (experimentally). Firestore needed a fix, so we pushed a new version of the `FirebaseFirestore` pod (`1.4.4` -> `1.4.5`) *but* because of the way the [`Firebase 6.7.0` pod is set up](https://github.com/CocoaPods/Specs/blob/84b500e066374f22a67eb0f87b4155d87ffea9e6/Specs/0/3/5/Firebase/6.7.0/Firebase.podspec.json#L275), `Firestore 1.4.5` is picked up when you run `pod update`, even locking Firebase to `6.7.0`. This allows us to ship patch updates to individual SDKs must faster without having to do a "full" release.

This is great for CocoaPods, but we thought it was unreasonable to change the Zip file shipped as `6.7.0`.  The reason `6.7.1` is mentioned is because it's a Zip and Carthage update, including the new `FirebaseFirestore 1.4.5` pod.

Overall, we should document this better on the iOS releases site (if it's a Zip/Carthage only update), and make sure it's fully up to date. 

> There's a place that states the current version for each "sub" framework of Firebase?

Using the latest version from CocoaPods should automatically pull in all the latest Firebase frameworks.

Apologies for the trouble, and please let me know if that helps explain things!

**Comment by ryanwilson** [comment]
I'm going to close this, but if you have further questions or any feedback on the versioning please do share :)
