### ISSUE TITLE
FR: Distribute Firebase as an XCFramework

### ISSUE THREAD

**Issue by rhysforyou** [firebase/firebase-ios-sdk#3902]
## Environment

  * Xcode version: 11.0
  * Firebase SDK version: 6.9.0
  * Firebase Component: All of them
  * Component version: N/A

## Issue

The current recommended approach for installing Firebase is via CocoaPods, which is a good fit for frameworks distributed as a precompiled binary. But with Xcode 11 and Swift 5.1, we have a new way to distribute precompiled frameworks in the form of XCFramework bundles. I think this format would be a good fit for Firebase, and a simpler way to include Firebase in a project than setting up CocoaPods.

In my own projects, I'm trying as much as possible to move towards Swift Package Manager, and while there's an open issue (#3136) to add support for this, there's currently a lot of roadblocks for distributing binary frameworks. In my mind, releasing Firebase as an XCFramework would be the next best thing, and allow me to easily consume Firebase without the need for third-party dependency managers.

**Comment by paulb777** [comment]
There is some relevant discussion about xcframeworks in the context of Catalyst support at #3144

**Comment by ryanwilson** [comment]
It's also worth noting that Firebase currently does release a zip file containing all `.framework` files which seems to be the request here, no CocoaPods or third party package managers needed.

The XCFrameworks come in when we have full Catalyst support since we can't package a single `.framework` file that also supports Catalyst.

You can find the latest zip file at https://github.com/firebase/firebase-ios-sdk/releases/latest as well as [the Firebase site](https://firebase.google.com/docs/ios/setup#frameworks) with instructions there as well.

**Comment by paulb777** [comment]
Work in progress at https://github.com/firebase/firebase-ios-sdk/tree/xcframework-master

**Comment by morganchen12** [comment]
Firebase zip is now distributed as a bundle of .xcframeworks, except for libraries that do not support Catalyst (Analytics and ML Kit). See the [release notes](https://firebase.google.com/support/release-notes/ios) for more details.
