### ISSUE TITLE
Firestore start after date issue

### ISSUE THREAD

**Issue by min-hwang** [firebase/firebase-ios-sdk#4010]
* Xcode version: 11.0
  * Firebase SDK version: _____
  * Firebase Component: Firestore
  * Component version: 1.5.1
  
The firestore getDocument function seems to include the date it is specified to start after.

#### Steps to reproduce:

  1. Define firestore.
  2. Use .start(after:[]) function to get next page.
  
#### Observed Results:

The last element from last read was included in new read. I solved temporarily by adding 0.01 to the date, but it is not very helpful. Anyway, I believe that function should work as it is described.
  
#### Expected Results:

  * What did you expect to happen?
I believe the result should exclude the value in parameter. 
As the comment in the file says, 

> "Creates and returns a new `FIRQuery` that starts after the provided fields relative to the order of the query"

  
#### Relevant Code:
// The lastDt variable is from previous page read. It is the mdate of last object in previous read.
```
db.collection("templates").whereField("muserid", isEqualTo: uid)
                    .whereField("blocking", isEqualTo: false)
                    .order(by: "mdate", descending: true)
                    .start(after: [lastDt])
                    .limit(to: pageSize)
                    .getDocuments { (snapshot, error) in
...
}
```

If this was addressed earlier, though I could not find, thanks if I can get the post.

**Comment by wilhuff** [comment]
Hi!

This has been reported previously, though [not on github](https://groups.google.com/d/topic/google-cloud-firestore-discuss/9_Vq21PAgbY/discussion).

The issue is that `NSDate` and `Date` on iOS are represented as a double precision floating point number and that's insufficiently precise to represent all possible dates. What you're seeing is a rounding error where converting a Date to a Firestore native Timestamp rounds slightly back in time.

This is solved by using `Timestamp` to represent your dates, especially for paging purposes. `Timestamp` has a method to convert itself to a `Date` for display purposes or whatever other use you might have. However, especially for this case of reading a date value for use as a query parameter, always use `Timestamp`.
