### ISSUE TITLE
Integrating Crashlytics into Mac OS application from scratch

### ISSUE THREAD

**Issue by leandrodemarco** [firebase/firebase-ios-sdk#4048]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1
  * Firebase SDK version: 6.3.0 (FirebaseCore)
  * Firebase Component: Crashlytics
  * Component version: 3.10.7

### [REQUIRED] Step 3: Describe the problem
We are evaluating changing our crash reporting tool for a Mac OS app and have considered Firebase Crashlytics as one of the alternatives. While I know that Mac OS is not officially supported, I've seen [here in this issue](https://github.com/firebase/firebase-ios-sdk/issues/2149#issuecomment-537113289) that integration should be possible by adding this two pods:

> pod 'Crashlytics'
> pod 'FirebaseCore'

and then following instructions here: https://firebase.google.com/docs/crashlytics/get-started?platform=ios
I took on from step 3 on above link but in the end it seemed as if the online Console still thinks we haven't connected the app to the SDK. I ran the app with -FIRDebugEnabled flag and all logs seemed to indicate normal functioning of the app.

In the end what it finally ended up working for me was to setup the app with Fabric's Mac OS app and then migrate it to Firebase through a web browser. This meant that my run script was not just 

> $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

but it had included the Fabric api key and secret (inserted by Fabric's Mac OS App). It also had some modifications on the app's plist also made by the Fabric app and I ended up with this code in my app delegate:

```
[FIRApp configure];
[Fabric with:@[[Crashlytics class]]];
```
With this changes the dashboard is shown and I can see the test crashes. 
But my concern is how to make this work in 2020 after Fabric shutdowns and migration through the browser is no longer possbile?

**Comment by ryanfrancesconi** [comment]
Why is the macOS installation so convoluted?

**Comment by samedson** [comment]
Apologies this was confusing - it should work using the same instructions as iOS (except for using those pods as mentioned).

A couple things that I sometimes forget to do are:

1) Including the run script `"${PODS_ROOT}/Fabric/run"`. This is the most important part so that symbols are uploaded before the app runs.

2) Making sure "Outgoing Connections (Client)" is checked in the Signing & Capabilities tab of Xcode so that crash reports can be uploaded and onboarding can happen

I went ahead and onboarded a new macOS test app and got it up and running. It's surprising to me that the Fabric-linked way worked, but Firebase onboarding didn't, as they share most of the same underlying infrastructure. The main difference is that the API Key is needed for the `run` script for Fabric linked mode, but the `run` script gets the GoogleService-info.plist file automatically for Firebase onboarding. It will use the GoogleService file from your "Copy Bundle Resources" Build Phase
