### ISSUE TITLE
additionalUserInfo nil when login through Phone number

### ISSUE THREAD

**Issue by rsekharAppyog** [firebase/firebase-ios-sdk#4133]
additionalUserInfo value is nil which is present inside AuthDataResult, when logging through phone number, so in that case not able to find out the providerID whether the user is logging through google/phone or any other services.

**Comment by rizafran** [comment]
Hi @rsekharAppyog thanks for filing this report. I tried replicating the issue by signing in using phone number, but I was able to get a value in `additionalUserInfo.providerID`.

Could you provide the following info to see what's going on here:

1. SDK version used / Podlock file
2. [Minimal repro](https://stackoverflow.com/help/mcve) / Relevant code
3. Detailed steps to reproduce the issue

**Comment by rsekharAppyog** [comment]
Hi @rizafran ,

1)SDK version used - GoogleSignIn (4.4.0)
2)Relevant code:
 `let authUI: FUIAuth? = FUIAuth.defaultAuthUI()
   let firebaseauthController = self.authUI!.authViewController()
   self.present(firebaseauthController, animated: true, completion: nil)`

and implemented the FUIAuthDelegate to the controller where above code called as below,
 `func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) {
          print(result.additionalUserInfo?.providerID)
   }`
3)Steps to reproduce
Log in using phone provider and also give the **new phone number** (if you already used that number to sign in then delete from the Authentication tab in firebase).
You will get the additionalUserInfo value as nil.

**Comment by rsekharAppyog** [comment]
Hi @rizafran ,

1)SDK version used - GoogleSignIn (4.4.0)
2)Relevant code:
let authUI: FUIAuth? = FUIAuth.defaultAuthUI() let firebaseauthController = self.authUI!.authViewController() self.present(firebaseauthController, animated: true, completion: nil)

and implemented the FUIAuthDelegate to the controller where above code called as below,
func authUI(_ authUI: FUIAuth, didSignInWith authDataResult: AuthDataResult?, error: Error?) { print(result.additionalUserInfo?.providerID) }
3)Steps to reproduce
Log in using phone provider and also give the new phone number (if you already used that number to sign in then delete from the Authentication tab in firebase).
You will get the additionalUserInfo value as nil.

**Comment by rizafran** [comment]
Hi @rsekharAppyog thanks for the info. I can't seem to replicate the issue either using [Firebase SDK](https://github.com/firebase/firebase-ios-sdk) or [FirebaseUI](https://github.com/firebase/FirebaseUI-iOS/tree/master/samples/swift/FirebaseUI-demo-swift/Samples/Auth). The `authDataResult.additionalUserInfo?.providerID` returns a "phone" value on my end when I tried to sign in a new phone number (following the steps to reproduce).

Can you provide a [minimal repro](https://stackoverflow.com/help/mcve) that I can run locally in order to replicate the issue, as well as your Podfile.lock file to check the sdk versions used. You may also try the [Auth quickstart](https://github.com/firebase/quickstart-ios/tree/master/authentication) to see if the issue is reproducible.
