### ISSUE TITLE
App crashes for invalid googleApId

### ISSUE THREAD

**Issue by maipalr** [firebase/firebase-ios-sdk#4155]
Fatal Exception: com.firebase.core
Configuration fails. It may be caused by an invalid GOOGLE_APP_ID in GoogleService-Info.plist or set in the customized options.

FirebaseApp.configure(options: secondaryOptions)
Why doesn't this function throws a exception so that we can gracefully handle this instead of crashing the app.

**Comment by ryanwilson** [comment]
Hi @maipalr, thanks for the report.

There are a few reasons for this:

- `googleAppID` is required for all Firebase functionality and cannot continue without it
-  We expect a specific format for `googleAppID`s, and this validation is what's causing a failure. We have no way to validate server side that the appID is valid during startup (without making a network request) so this is the best we can do to tell developers that the configuration is incorrect
-  Based on the two comments above, we do not expect developers passing in remotely configured `googleAppID` or generating them at all. These are string constants that should be used in a non-modified `GoogleService-Info.plist` file downloaded from the Firebase console, or copied directly without modification from the console
- FirebaseCore is written in Objective-C so we cannot mark a call as `throws`, the only thing we can do is raise an `NSException` (link below for where this code is) and unfortunately that can't be wrapped in a Swift `do`/`catch` block. We raise an exception because we consider this a programming error and want to let the developer know right away instead of silently failing

https://github.com/firebase/firebase-ios-sdk/blob/8b23a3266d96859fad3d7d3fa83bc2aeeab192b0/Firebase/Core/FIRApp.m#L278

I hope that helps, let us know if there's any confusion over this. Thanks again!

**Comment by maipalr** [comment]
is there any function to check for the format validity of googleAppID so that we can check before initializing the sdk?

**Comment by ryanwilson** [comment]
There is no public API for this. May I ask what your use case is? This will help us evaluate if this is functionality missing that we want to support in the future.

**Comment by maipalr** [comment]
use case is this params are configured from backend api, the reason for this we have different firebase projects and in future this projects may change. Sometimes if we get wrong data there is no way to revert back this the app keep crashes whenever it opened users has to delete the app and reinstall it.

**Comment by morganchen12** [comment]
It's unlikely we'll add support for this use case since we don't want people to be dynamically provisioning Google app IDs at runtime.
