### ISSUE TITLE
Only display firebase in-app messaging in a specific View

### ISSUE THREAD

**Issue by professorbk** [firebase/firebase-ios-sdk#4287]
### [REQUIRED] Describe the problem
My iOS app is organized as follow:

- Main menu screen which has many buttons

- Each button redirects to a specific view/screen

I want to display in-app message in Main menu screen only; but currently it can be shown in both Main screen and other screens.

How can I limit the display of in-app to a specific screen only?
#### Steps to reproduce:

I did use firebase event to trigger the display of in-app message **after** main menu screen is opened; but if I open the main menu screen, then quickly open another screen called A, then in-app message is still shown in screen A.

**Comment by christibbs** [comment]
@rizafran thanks for the question.

There are a few ways you could accomplish this.

1.) There is a flag called [`messageDisplaySuppressed`](https://firebase.google.com/docs/reference/swift/firebaseinappmessaging/api/reference/Classes/InAppMessaging#messagedisplaysuppressed) that can be set on the [`InAppMessaging`](https://firebase.google.com/docs/reference/swift/firebaseinappmessaging/api/reference/Classes/InAppMessaging) singleton that can be used to prevent in-app messages from appearing. You could, for example, set this flag to `false` when the main menu screen appears and set it to `true` when it disappears.

2.) You could programmatically trigger the message using a [custom event trigger](https://firebase.google.com/docs/reference/swift/firebaseinappmessaging/api/reference/Classes/InAppMessaging#triggerevent_:) in the main menu screen. In this case, the message wouldn't show in another screen because you wouldn't trigger in those other screens.

**Comment by professorbk** [comment]
thanks for the rapid support!
I should've read the docs more carefully before asking this question :)
