### ISSUE TITLE
minimum watchOS support for GoogleDataTransport

### ISSUE THREAD

**Issue by chliangGoogle** [firebase/firebase-ios-sdk#4292]
GoogleDataTransport is used by FirebaseCore and many other Firebase products. Would be great to have watchOS support so unlock messaging support on #4016.

- Reachability needs #ifdefs because some parts don't work on watchOS
- Background tasks might be different on watchOS
- SystemConfiguration framework is not available

**Comment by mikehaney24** [comment]
@chliangGoogle  Can you enumerate the specific requirements? I might not remember them all:

- Reachability needs #ifdefs because some parts don't work on watchOS
- Background tasks might be different on watchOS
- SystemConfiguration framework is not available

**Comment by chliangGoogle** [comment]
That is right! @mikehaney24 I've updated the description and I think you've listed all the summary we talked about.

**Comment by chliangGoogle** [comment]
@mikehaney24 Looks like we can unblock #4016 soon. Once I submit the PR, you can fine tune on top of it.

**Comment by mikehaney24** [comment]
Sounds good!

**Comment by doudounan** [comment]
Expand fully watchOS support for GoogleDataTransport in https://github.com/firebase/firebase-ios-sdk/pull/5443

- Always assume network connection on watchOS, since SystemConfiguration is not available on watchOS.

- Protect background tasks with `performExpiringActivityWithReason:usingBlock:` and semaphores.

- Support Notification Service Extension on watchOS
