### ISSUE TITLE
Pointing to a carthage framework version

### ISSUE THREAD

**Issue by agustr** [firebase/firebase-ios-sdk#4401]
* Xcode version: not applicable
  * Firebase SDK version: not applicable
  * Firebase Component: googlesignin
  * Component version: not applicable

I wish to install a specific version of google sign in framework through Carthage. The following page has a good explanation on how to go about installing the framework.

https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

But I can not figure out how to choose a specific version of google sign in framework. I do understand that preferably all frameworks should be on the same firebase version but I want to take one step at a time and first install and then update.

**Comment by paulb777** [comment]
The Firebase Carthage distribution is not designed for mixing and matching from different versions, even though it will often work.  You can see the versions available by looking at the associated json file for each library.  You could then examine the [Firebase podspec](https://github.com/CocoaPods/Specs/tree/master/Specs/0/3/5/Firebase) to see the corresponding library version for any specific library.  Unfortunately that won't work for `GoogleSignIn` since it is not a part of Firebase and included in the binary distributions as a courtesy since it is often used with Firebase and a compatible binary distribution is not otherwise available.

**Comment by paulb777** [comment]
Going to close this, since there's no obvious actions for us.  Feel free to follow-up if you have more questions.
