### ISSUE TITLE
Crashlytics looking for wrong dSYM file?

### ISSUE THREAD

**Issue by fosterbrereton** [firebase/firebase-ios-sdk#4425]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.1
  * Firebase SDK version: 6.13.0
  * Firebase Component: Crashlytics
  * Component version: 3.14.0

### [REQUIRED] Step 3: Describe the problem

The short answer is that none of my crashes are symbolicating, so I am seeing no crash reports in Firebase Crashlytics. As for the long answer...

I have Firebase/Crashlytics integrated into my iPad app, and can successfully test-crash. Upon reboot of the application I can see my Crashlytics delegate firing, indicating that a crash was received. I call the completion handler back, and see in the console output of the application that the issue is being uploaded to Firebase/Crashlytics. Finally, I can see a "missing dSYM" warning in the Firebase console incrementing every time I do this. The UUID that is missing is `0DB1D2BA-6CAA-3D30-AF74-0B3AB0DCBFB1`:

<img width="961" alt="Missing dSYMs" src="https://user-images.githubusercontent.com/1664117/70027806-d51ce480-1557-11ea-81f9-07d785bfe61a.png">

During a build, I am calling `upload-symbols` explicitly (so not via `run`.) I have several reasons why I want to do this, one of them being so I can get more verbose output. When I run `upload-symbols` as the last phase of my build in Xcode, I get the following output:

```
upload-symbols 2.1 build 17
Running upload-symbols in Build Phase mode
Validating build environment for Crashlytics...
Arguments:
Debug mode enabled
API Key: X
Platform: ios
DSYM Paths: ["/path/to/dSYM"]
Sending Crashlytics build event...
App was already onboarded
Processing dSYMs...
Checking dSYM size above zero at path "/path/to/dSYM/Contents/Resources/DWARF/app"
Checking dSYM size 2150962710 bytes at path "/path/to/dSYM/Contents/Resources/DWARF/app"
Checking dSYM size 2150962710 bytes at path "/path/to/dSYM/Contents/Resources/DWARF/app"
Inspecting next path: /path/to/dSYM
Found dSYM at path: /path/to/dSYM
Begin processing dSYM at /path/to/dSYM
Zipping csym for uuid 0495cb5f8ba53dc2afab894ecc32658c, architecture: arm64
Zipping csym succeeded for uuid 0495cb5f8ba53dc2afab894ecc32658c, architecture arm64... getting compressed data
Deleting file at path: /path/to/temp/file1.csym
Deleted file at path /path/to/temp/file1.csym
Deleting file at path: /path/to/temp/file2.zip
Deleted file at path /path/to/temp/file2.zip
Uploading cSYM for uuid 0495cb5f8ba53dc2afab894ecc32658c, architecture arm64
Successfully submitted symbols for architecture arm64 with UUID 0495cb5f8ba53dc2afab894ecc32658c in dSYM: /path/to/dSYM
dSYM upload complete
Successfully uploaded Crashlytics build event and symbols
```

(I am using the `google-service-plist` flag to pass the plist file to `upload-symbols`, not the old Fabric API key.)

When I navigate to `/path/to/dSYM/` and use Get Info from the Finder, I can confirm that the UUID for the dSYM is in fact `0495CB5F-8BA5-3DC2-AFAB-894ECC32658C`. Note this is the _same_ UUID reported by `upload-symbols`, but is _not_ the same expected by Crashlytics in the Firebase console.

I can also attest that the build on my iPad generating crashes came from the same build that generated the above `upload-symbols` output.

As a result, none of my crashes are getting symbolicated, presumably because the dSYM getting uploaded is different than the one Firebase/Crashlytics is expecting.

What am I missing?

#### Relevant Code:

My code is the same as when I reported Issue#4407.

**Comment by samedson** [comment]
Hey @fosterbrereton, I'm wondering if maybe there's another dSYM in your app that needs to be uploaded (aside from the main app dSYM). Sometimes Xcode can generate more than one dSYM for your app's build.

Can you try to locate the `0DB1D2BA-6CAA-3D30-AF74-0B3AB0DCBFB1` dSYM on your computer? Sometimes running `mdfind 0DB1D2BA-6CAA-3D30-AF74-0B3AB0DCBFB1` in the terminal will work.

If you've run a clean and made a code change since this bug was reported, you may need to repeat the process of building, uploading a crash, and finding the UUID for the missing dSYM. Put that UUID into `mdfind` and see if it finds it on your computer.

**Comment by willbattel** [comment]
We've encountered this recently as well. I downloaded the DSYMs directly from App Store Connect and 2 out of 5 requested DSYMs did not exist.

This had never happened to us until our most recent build last week.

**Comment by bonkey** [comment]
I can confirm similar behavior for last weeks as well. Files downloaded from App Store and uploaded via fastlane don't appear in Crashlytics. The same files uploaded manually work perfectly. Can look for details if needed but AFAIR output looked pretty similar to @fosterbrereton's one.

**Comment by samedson** [comment]
Has anything changed recently with your build processes? Updated Xcode or Crashlytics SDK versions?

**Comment by willbattel** [comment]
This started happening for us when we updated Xcode to start building against iOS 13- everything else stayed the same. In every case we have downloaded the symbol files directly from the App Store, not those held locally by Xcode.

**Comment by lilyngabichtranADBE** [comment]
I am also experiencing issue with crashlog not showing symbols on Firebase console as well.  My issue is a little slight different since I am seeing the crash count on dSYM Crashlytics console, but I am not getting any crash data for these crash. I am using the same as environment as Foster:

    Xcode version: 11.1
    Firebase SDK version: 6.13.0
    Firebase Component: Crashlytics
    Component version: 3.14.0
I am uploading the screenshot of what is showing up on Firebase console for my application.

<img width="1360" alt="Screen Shot 2019-12-06 at 11 41 45 AM" src="https://user-images.githubusercontent.com/9659108/70351272-6cff2480-181d-11ea-8f71-66af428675aa.png">
<img width="1352" alt="Screen Shot 2019-12-06 at 11 41 33 AM" src="https://user-images.githubusercontent.com/9659108/70351274-6cff2480-181d-11ea-9c3f-ed323fcf04a4.png">

NOTE: When I was incorporating Firebase/Crashlytics, I have to make an adjustment to the Crashlytics in order to build Acrobat iOS.  Here is the change that I have to made to the Crashlytics pod file, crashlytics.h to change the following line:
 
@property (nonatomic, assign, nullable) id <CrashlyticsDelegate> delegate;
 
To:
@property (nonatomic, unsafe_unretained, nullable) id <CrashlyticsDelegate> delegate;
 
Since it complaints about ‘assign”.  Not sure if this change could cause the crash symbols to not show up on firebase console.

**Comment by fosterbrereton** [comment]
My Crashlytics integration went to our master branch several days ago, despite this still being an issue. As it turns out, the build variant that our QE team is primarily testing on seems to work just fine. The dSYM was uploaded by the build system, and crashes are being recorded and reported to Firebase successfully. However, the build variant developers use to build features locally fails to report any crashes on the service, even after verifying the dSYM is being built and uploaded successfully. Since this is only problematic when building and debugging the integration of Crashlytics into our product, we're continuing to move forward with things. We'd like to resolve this issue still, though, as it would increase our general confidence in Crashlytics' ability to catch and report all the crashes our users might hit/report in the wild.

**Comment by fosterbrereton** [comment]
I just discovered the build QE is testing against doesn't strip its symbols, so it's very likely what's going up to Crashlytics is already symbolicated. So it would appear none of our integrations have demonstrated a successful workflow.

**Comment by samedson** [comment]
The core issue seems to be that Crashlytics is uploading crashes for UUIDs that don't match what you're uploading with the build tools. I think there's a few possible reasons this could be happening:

1. dSYMs are being generated in different locations than what's expected and / or more than one dSYM is being generated for the build
2. dSYMs are being sent to the wrong Crashlytics app (eg. because a different GoogleService file is being passed to upload-symbols) - this seems unlikely given we've identified that there's a different missing dSYM UUID being reported, but still worth checking out
3. These apps have Bitcode enabled or the dSYMs are just in the archive
4. Something changed with how Xcode generates dSYMs

To rule out 1. It also seems like something changed in macOS so that you can't just run `mdfind <uuid>` anymore. 

Here's a new command to print out all your dSYMs' UUIDs on your machine:
```
mdfind -name .dSYM | xargs -n1 dwarfdump -u
```

For the missing dSYM uuids, can you try running that above command and searching for them? I want to make sure they aren't just being placed somewhere else on your system.

For 2. Can you double check the GoogleService-info.plist you're passing to upload-symbols has the same GOOGLE_APP_ID value as the app in the Firebase Project (in the console, settings gear > "Project Settings" > list of apps - look for the App ID field).

For 3.
 - Open up your xcarchive by right clicking and choosing "Show package contents", and look for a "dSYMs" folder. Try `dwarfdump -u <dsym>` on all of those dSYMs to see their UUIDs, and upload all of them with `upload-symbols`
 - If you have bitcode enabled, download the dSYMs from the archive by opening the Organizer and clicking "Download Debug Symbols"
 - If you've released to iTunesConnect and have bitcode enabled, go to the Build Details for that version of your app and click "Download dSYMs"
    - sometimes Apple will recompile the app with bitcode enabled

For 4. If possible, can you try this on an earlier Xcode? I'm able to successfully upload symbols using this version but maybe there's something about my test apps that's different.

**Comment by rizafran** [comment]
Hi @fosterbrereton, may I know if you're still encountering issues even after following the solutions on the above comment?

**Comment by dorw123** [comment]
Issue still happening.

**Comment by paulb777** [comment]
@dorw123 Please review the solutions described above and if you cannot resolve, open another issue with your details
