### ISSUE TITLE
Query limited to last doesn't work when = (toLast: 50)

### ISSUE THREAD

**Issue by JStevens127** [firebase/firebase-ios-sdk#4447]
Reopening an issue reported by @maximkhatskevich https://github.com/firebase/firebase-ios-sdk/issues/814

When I use queryLimited(toLast: 50), my query only fetches 1 result, despite having over 50 items in the DB.

**Environment**
- Xcode version: 11.2.1
- Firebase Component: Realtime Database
- Version: 6.1.2

```
let ref: DatabaseReference = Database.database().reference().child("table1")
let query = ref.queryOrdered(byChild: "timestamp").queryLimited(toLast: 50)

query.observeSingleEvent(of: .value, with: { (snapshot) in

print(snapshot)

})
```

Print statement shows 1 item in DB, despite having over 50 items. Any help would be greatly appreciated.

**Comment by JStevens127** [comment]
The issue appears to have something to do with offlinePersistance. When I set isPersistanceEnabled = false, I no longer experience the issue.

**Comment by rizafran** [comment]
Hi @JStevens127 Is the issue happen consistently? Have you also tried to set the `isPersistanceEnabled` back to `= true `? If so, is the issue still happening? Make sure also that you have a good network connection though I'm not sure if this is an expected behavior of enabling of offline persistence.
