### ISSUE TITLE
FIRUser photoURL gives expired url

### ISSUE THREAD

**Issue by papikkar** [firebase/firebase-ios-sdk#453]
* Xcode version: 9.1
  * Firebase SDK version: 4.5
  * Firebase Component: Auth
  * Component version: 4.3.1

It seems Facebook profile picture has expired and [[FIRAuth auth] does not get updated profile picture url, it returns the old one. What you will get when trying to use the url is "URL signature expired".

And sign out and sign in again with Firebase does not help, profile picture url is still 'expired'

**Comment by protocol86** [comment]
@papikkar 

I haven't been able to reproduce this issue, but it does seem reasonable that Facebook's Photo URL would expire over time.  We are investigating why signing out and back in would not update the expired URL, but I don't think forcing the user to sign out and back is the best work around for this issue.

In the mean time may I suggest either querying the photoURL from Facebook directly or storing the photo and using your own URL instead of Facebook's public URL, in both case you can update the Photo URL of you Firebase User by following the steps on [this linkl](https://firebase.google.com/docs/auth/ios/manage-users) under the **Update a user's profile** section.
