### ISSUE TITLE
Can't build after update: cstddef file not found

### ISSUE THREAD

**Issue by rostopira** [firebase/firebase-ios-sdk#4537]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Firestore
  * Component version: 1.8.3

### [REQUIRED] Step 3: Describe the problem

After updating Firestore to version that includes "abseil" as a dependency builds are broken.
I'm getting error in `Pods/abseil/types/compare/compare.h` on line `#include <cstddef>`: 'cstddef' file not found

#### Steps to reproduce:

I'm not sure, but as a guess, it maybe related to Objective-C++ usage in project or to `libyuv` pod dependency.

**Comment by rizafran** [comment]
Thanks for reporting this, @rostopira. Could you provide complete error logs / stack trace of the issue you're having?

**Comment by rostopira** [comment]
@rizafran I can't build project, how I'm supposed to post logs or stack trace?

**Comment by rizafran** [comment]
@rostopira Like screenshot of error encountered. I'll try to run this on my end to see if it's reproducible, and I'll let you know with my findings.

**Comment by rizafran** [comment]
@rostopira I wasn't able to reproduce the issue. I can run the app ([iOS quickstart](https://github.com/firebase/quickstart-ios/tree/master/firestore)) without errors. Could you share your Podfile and Podfile.lock to see if the Podfile will make it reproducible?

**Comment by wilhuff** [comment]
Also [within the build log](https://stackoverflow.com/questions/30060898/xcode-how-to-see-build-command-and-log/30084344) in xcode you can get a detailed description of the compiler error, including the path through the headers.

**Comment by wilhuff** [comment]
Actually I figured it out without a build log. This is essentially a repeat of #4035 except the conflict is now between the `libyuv` pod and the `abseil` pod.

The underlying issue is that Xcode or CocoaPods (I'm not sure which) ends up constructing a global header map from basename to path, but it does not account for the fact multiple pods can include filenames with the same basenames.

In this case, both libyuv and abseil include a `compare.h`. The problem you're seeing is because `libyuv.h` includes its `compare.h` unqualified: https://github.com/waitingsnow/libyuv-iOS/blob/66865379ba5b85fcdc0faccac3cb3be80ba7ce17/headers/libyuv.h#L15. This goes through the header map for resolution which can pull in conflicting headers depending on which package won. Abseil's compare.h is a C++ header which depends on the `cstddef` C++ system header, but that header isn't available when compiling from C or Objective-C.

Unlike #4035, this isn't a conflict between a Firestore header and the other package so this isn't something we can fix directly. The fix is for one or both of these projects to disable the header map for themselves, similar to the way it's done in [gRPC](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec#L92) or possibly exclude headers from CocoaPod's public header treatment as done in [Firestore](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFirestore.podspec#L35).

Likely we can get Abseil to change their pod; it's not intended there that you would ever use their headers unqualified.

In the meantime if you need both Firestore and libyuv you're stuck until one or both of these packages resolve this conflict.

**Comment by wilhuff** [comment]
Note that since libyuv ships as a prebuilt binary, this is likely a compilation error within your own project and you may be able to work around this by disabling the header map in your project. You can do this by setting `USE_HEADERMAP` to `NO` in your Xcode Build Settings. This may trigger other build problems though.

I've been trying to reproduce this to make concrete recommendations but haven't been able to do so with this `Podfile`:

```ruby
platform :ios, '9.0'

target 'libyuv-test' do
  use_frameworks!

  # Pods for libyuv-test
  pod 'libyuv-iOS'
  pod 'Firebase/Firestore'
end
```

I suspect it's random which pod actually wins so I'll keep trying.

**Comment by MrAlek** [comment]
I'm experiencing the same problem being dependent on libyuv too through the `flutter-webrtc` pod. Would love some help. Will try to downgrade meanwhile.

**Comment by LinusU** [comment]
Applying the following patch to the libyuv project fixes the problem:

```patch
diff --git a/libyuv-iOS/headers/libyuv.h b/libyuv-iOS/headers/libyuv.h
index f371698..aeffd5e 100644
--- a/libyuv-iOS/headers/libyuv.h
+++ b/libyuv-iOS/headers/libyuv.h
@@ -11,22 +11,22 @@
 #ifndef INCLUDE_LIBYUV_H_
 #define INCLUDE_LIBYUV_H_
 
-#include "basic_types.h"
+#include "libyuv/basic_types.h"
-#include "compare.h"
+#include "libyuv/compare.h"
-#include "convert.h"
+#include "libyuv/convert.h"
-#include "convert_argb.h"
+#include "libyuv/convert_argb.h"
-#include "convert_from.h"
+#include "libyuv/convert_from.h"
-#include "convert_from_argb.h"
+#include "libyuv/convert_from_argb.h"
-#include "cpu_id.h"
+#include "libyuv/cpu_id.h"
-#include "mjpeg_decoder.h"
+#include "libyuv/mjpeg_decoder.h"
-#include "planar_functions.h"
+#include "libyuv/planar_functions.h"
-#include "rotate.h"
+#include "libyuv/rotate.h"
-#include "rotate_argb.h"
+#include "libyuv/rotate_argb.h"
-#include "row.h"
+#include "libyuv/row.h"
-#include "scale.h"
+#include "libyuv/scale.h"
-#include "scale_argb.h"
+#include "libyuv/scale_argb.h"
-#include "scale_row.h"
+#include "libyuv/scale_row.h"
-#include "version.h"
+#include "libyuv/version.h"
-#include "video_common.h"
+#include "libyuv/video_common.h"
 
 #endif  // INCLUDE_LIBYUV_H_
```

I have no idea how to submit a pull request to them though 😅 

ping @wilhuff, any idea if we could upstream this to libyuv?

**Comment by wilhuff** [comment]
The best way to do so is to fork their repository, apply and commit your change locally, and then [create a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) in the standard way. Good luck!

**Comment by MrAlek** [comment]
@wilhuff Problem is that libyuv is on Google Git and not on GitHub and as far as I can see, there is no open pull request mechanic there.

**Comment by wilhuff** [comment]
The mainline libyuv actually has the shape you want: https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/master/include/libyuv.h.

The trouble is that the CocoaPod packaging has changed this (or not kept up with its upstream): https://github.com/waitingsnow/libyuv-iOS/blob/master/headers/libyuv.h. The pull request would be against waitingsnow/libyuv-iOS.

Note, however, that CocoaPods flattens headers paths by default, so it's likely that this change was made to make the project compile that way. Some additional work with `preserve_paths` or similar would be required.

**Comment by MrAlek** [comment]
Oh, that is right. The `waitingsnow` fork hasn't been updated for two years so I guess a more active mirror is needed anyhow. We'll open an issue with cloudwebrtc/flutter-webrtc .

Thanks for the information @wilhuff. 🙏
