### ISSUE TITLE
Unreleased Resource: Database

### ISSUE THREAD

**Issue by gopalchinnadurai** [firebase/firebase-ios-sdk#4552]
We have used FirebaseRemoteConfig 4.4.0 as per our need. Some VAPT points are mentioned in below picture. Kindly help us asap. 

**Issue Summary:**

The function insertMainTableWithValues:fromSource:() in RCNConfigDBManager.m sometimes fails to release a database resource allocated by prepareSQL:() on line 427.The program can potentially fail to release a database resource.

**Issue Screenshot:**

<img width="511" alt="Screenshot 2019-12-24 at 4 57 33 PM" src="https://user-images.githubusercontent.com/55129685/71411224-8651fe80-266e-11ea-97f2-ae64e71404dd.png">

**Comment by morganchen12** [comment]
Looks like the line it's referring to is [this early exit](https://github.com/firebase/firebase-ios-sdk/blob/865e2896141808b30dba0f776ec69a33eb8f9a21/FirebaseRemoteConfig/Sources/RCNConfigDBManager.m#L428), which only happens if statement fails to materialize. Closing this as a non-issue since the statement cannot be released if it is nil.

If you are able to profile this section of code and share an Instruments trace demonstrating a memory leak, please comment here and we'll re-open the issue.
