### ISSUE TITLE
FirebaseInstallations and Carthage

### ISSUE THREAD

**Issue by PolitieRool** [firebase/firebase-ios-sdk#4696]
This is to help anyone updating Firebase to 6.15 using Carthage.

To solve the  **Undefined symbol: _OBJC_CLASS_$_FIRInstallations**,   **Undefined symbol: _FBLPromiseErrorDomain** and the **Undefined symbol: _OBJC_CLASS_$_FBLPromise** I needed to link the  FirebaseInstallations.framework and PromisesObjc.framework from the Carthage build iOS directory to the app frameworks.

**Comment by ryanwilson** [comment]
Thanks for the note @PolitieRool - we did add a new dependency and the frameworks were included with the `FirebaseAnalytics` artifacts. It's always best to ensure you're bringing in all frameworks that get pulled in from Carthage!

I'll close this now since there's no action necessary, but others can still find it for reference when searching.

**Comment by chamitha** [comment]
Life saver! Figured out including the FirebaseInstallations.framework but PromisesObjc might have been a while longer yet
