### ISSUE TITLE
Firebase/Performance logs "Dispatching 25 gauge metrics" every second until app is killed

### ISSUE THREAD

**Issue by ImanuelChen** [firebase/firebase-ios-sdk#4898]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.14.0
  * Firebase Component: Performance
  * Component version: 6.14.0
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

On occasion, Firebase/Performance will immediately start logging "Dispatching 25 gauge metrics." on app launch every second and will not stop until the app is terminated. It's happened to me twice so far in approximately 50 launches.

#### Steps to reproduce:

No clue how to consistently reproduce this.

At the very least, I would like to know what exactly firebase is doing when it is logging this message.

**Comment by visumickey** [comment]
@ImanuelChen Firebase Performance has a feature to give the developer a detailed input on how a specific instance of the trace is performing [Refer(https://firebase.google.com/docs/perf-mon/custom_traces-metrics#more-detail-trace-samples)]. 

The above mentioned logging message arises because of the same. We do not collect such detailed performance details all the time. We collect them on a small percentage of the instance runs. This explains why you don't see these messages consistently.

We also hope that you have the logging level set to be verbose to see these messages. To avoid such log spam, consider changing the logging level to error.

**Comment by ImanuelChen** [comment]
Ohh okay got it. Thanks!
