### ISSUE TITLE
Firebase dynamic links don't detect url

### ISSUE THREAD

**Issue by pajtimid** [firebase/firebase-ios-sdk#4999]
* Xcode version: __11.3.1___
  * Firebase SDK version: __4.8.2___
  * Firebase Component: _DynamicLinks____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)
  * Component version: _2.3.2____
  * Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem

I implemented dynamic links months before. They works well. 
But now cant detect dynamicLink.url, userActivity.webpageURL is coming as it should.

Also dynamicLink is not nil also don't have error

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
- (BOOL)application:(UIApplication *)application
continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:
#if defined(__IPHONE_12_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_12_0)
(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> *_Nullable))restorationHandler {
#else
    (nonnull void (^)(NSArray *_Nullable))restorationHandler {
#endif  // __IPHONE_12_0
        
        NSURL *incomingUrl = userActivity.webpageURL;
        NSLog(@"Incoming url is: %@", incomingUrl);
        BOOL handled = [[FIRDynamicLinks dynamicLinks] handleUniversalLink:userActivity.webpageURL
                                                                completion:^(FIRDynamicLink * _Nullable dynamicLink,
                                                                             NSError * _Nullable error) {
            if (error != nil) {
                NSLog(@"Error: %@",error.localizedDescription);
                return;
            }
            if (dynamicLink != nil) {
                [self handleIncomingDynamicLink:dynamicLink];
            }
        }];
        return handled;
    }
```

But, after installing the app for the first time, it opens the dynamic link

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    
    FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
}
```

**Comment by ryanwilson** [comment]
Hey @pajtimid  - thanks for the report.

That version of Dynamic Links (& Firebase) is over 2 years old and there have been many revisions since, along with changes to handle new iOS versions. Can you please update to the latest version of Firebase (6.18.0) and DynamicLinks (4.0.7) and see if that solves your issue? You may need to follow the getting started guide to accommodate new methods in the `AppDelegate`.

**Comment by pajtimid** [comment]
Thanks for your recommendation @ryanwilson.
This solved my issue. But I'm little bit confused, how it can happened. Because days before it works perfectly. But now not.

**Comment by morganchen12** [comment]
It's difficult to tell why dynamic links stopped working without investigating, but dynamic links by nature is a relatively fragile feature since it must match a link click to an app install without collecting too much data.

I'm going to close this issue since it's been resolved, but if you have more questions feel free to continue commenting here.
