### ISSUE TITLE
FR: Get Download URL in a single call

### ISSUE THREAD

**Issue by akhilpothana** [firebase/firebase-ios-sdk#5044]
### Feature proposal

* Firebase Component: Storage

Currently, you can obtain the download URL of an image you know already exists in the bucket in one call. In my scenario, I'm uploading a new image, and then immediately making another call to obtain its new download URL to send elsewhere. I wonder if it's possible to obtain the image URL as a part of the upload tasks callback, and make everything happen in one call?

**Comment by schmidt-sebastian** [comment]
@akhilpothana Thanks for the feature request!

This is actually how Storage used to work, but we had to change the behavior so that we could add support for `StorageReference.list()`. Generating download URLs is now a separate step, and while I understand that this is not ideal, this separation allows us to better balance SDK traffic across our backends. Sorry!

**Comment by akhilpothana** [comment]
Fair enough. Thanks for the reply!
