### ISSUE TITLE
`-[FIRRemoteConfig ensureInitializedWithCompletionHandler:]` doesn't fail when RCNConfigDBManager fails to open the DB

### ISSUE THREAD

**Issue by nikolaykasyanov** [firebase/firebase-ios-sdk#5085]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3.1
  * Firebase SDK version: 6.17.0
  * Firebase Component: Remote Config
  * Component version: 4.4.7
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

When `RCNConfigDBManager` can't open the database for whatever reason (device being locked for one), no error is propagated to the callback of `-ensureInitializedWithCompletionHandler:`.

It all boils down to how `-[RCNConfigDBManager loadMainWithBundleIdentifier:completionHandler:]` is implemented: it always invokes its callback with `success: YES` even when some of the dictionariese couldn't be read (due to DB not being open etc.)

https://github.com/firebase/firebase-ios-sdk/blob/31385e0f6fd183704b39a49e582ad6c7b057e5e7/FirebaseRemoteConfig/Sources/RCNConfigDBManager.m#L854

#### Steps to reproduce:

1. Create an iOS app using Firebase Remote Config and having a background launch trigger (significant location change, background refresh etc.).
2. Invoke `-[FIRRemoteConfig ensureInitialized]` early in app lifecycle (see the relevant code).
3. Trigger the app start event from 1. while device is locked.

Expected result: the app logs remote config initialization error.
Actual result: the app logs no error.

#### Relevant Code:

```objc
@implementation AppDelegate {
    FIRRemoteConfig *_remoteConfig;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> *)launchOptions
{
    [_remoteConfig ensureInitializedWithCompletionHandler:^(NSError *initializationError) {
        if (initializationError != nil) {
            NSLog("Firebase Remote Config initialization failed: %@", initializationError)
        }
    }];

    // window setup etc.

    [window makeKeyAndVisible];

    return YES;
}

@end
```

**Comment by ncooke3** [comment]
Hi @nikolaykasyanov,

Thank you for reaching out! After reviewing the provided code, it is possible that since the `_remoteConfig` instance variable is still not initialized (and thus `_remoteConfig = nil`) when `ensureInitializedWithCompletionHandler` is called, the method call is being sent to `nil` which means we won't ever be able to print a potential `initializationError` in the completion handler as the completion handler will never be called in the first place.

Within the **`didFinishLaunchingWithOptions:`**  method, try to first configure a firebase app and then assign the shared Remote Config instance to your ivar:

```objc
// Configure the firebase app so you can access 
// the app's associated remote config store 
[FIRApp configure];

// Assign your ivar to the shared remote config object
 _remoteConfig = [FIRRemoteConfig remoteConfig]; 

// Then ensure _remoteConfig is initialized
[_remoteConfig ensureInitializedWithCompletionHandler:^(NSError *initializationError) {
        if (initializationError != nil) {
            NSLog("Firebase Remote Config initialization failed: %@", initializationError)
        }
    }];
```

If you are still having issues after taking these these troubleshooting tips into consideration, please update your code sample and we can try to better reproduce the issue.

**Comment by nikolaykasyanov** [comment]
Hi @ncooke3, thanks for the suggestion. I'm pretty sure that I stepped through `FIRRemoteConfig` internals before submitting this bug, meaning it couldn't have been `nil`. Let me double check.
