### ISSUE TITLE
Password Management: Hardcoded Password

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5311]
We have used the Firebase podfile as per our need. Here we have attached the screenshots for your reference . kindly help us asap.

**Step 1: Describe your environment**

  * Xcode version: 11.3.1
  * Firebase SDK version:  6.2.1
  * Firebase Component:  FirbaseinstanceID:4.2.3
  * Installation method: `CocoaPods '

 **Step 2: Describe the problem**
Hardcoded passwords may compromise system security in a way that cannot be easily remedied.Hardcoded passwords may compromise system security in a way that cannot be easily remedied.

<img width="1023" alt="Screenshot 2020-04-08 at 10 31 13 AM" src="https://user-images.githubusercontent.com/63187061/78746310-1731b900-7984-11ea-8e68-f519082b60c0.png">

<img width="1030" alt="Screenshot 2020-04-08 at 10 31 41 AM" src="https://user-images.githubusercontent.com/63187061/78746347-27e22f00-7984-11ea-948b-ec7c41245062.png">

**Comment by maksymmalyhin** [comment]
@divyaKalusulingam It looks like a flake or a bug of the tool your are using for analysis, because the provided code has never been a part of Firebase especially in `FIRApp.m` file. 

Another recommendation is to update Firebase in your app if it is possible. There were several stability and security improvements implemented in recent versions that you may benefit from.

I am closing the issue for now but feel free to reopen with relevant code references. Thanks.
