### ISSUE TITLE
Latency-compensated listener returns are marked as non-cached, but they are cached.

### ISSUE THREAD

**Issue by bsod88** [firebase/firebase-ios-sdk#5346]
### Feature proposal

* Firebase Component: Firestore

**Problem:** Latency-compensated snapshot listener returns are marked as not from cache but they are from cache.

**Solution:** Mark latency-compensated returns as from cache.

**Discussion:** The `isFromCache` property in the snapshot's metadata is `true` if the snapshot was created from cached data rather than guaranteed up-to-date server data. Latency-compensated returns, however, are marked not from cache despite the fact that not all of their data has made it to the server yet and may ultimately never. `hasPendingWrites`, to compensate, returns `true` if the snapshot contains the result of local writes that have not yet been committed to the server. Therefore, it should be impossible for `isFromCache` to be `false` and `hasPendingWrites` to be `true` in the same return because data cannot be not from cache _and_ not written to the database—they are contradictory—but that is the state of latency-compensated returns.

**Comment by rafikhan** [comment]
@bsod88 - Thanks for taking the time to write this feature request.

Our documentation could do a better job explaining these properties but we intended `isFromCache` to signal _read_ state so when it's `true` it means the document might be stale. This is useful for conveying offline state in the UI.  In the case of a newly created document, it's `false` because you just made it.  `hasPendingWrites` signals _write_ state and when it's `true` it means the SDK will attempt to save the document. This is useful to drive a 'saving spinner' in the UI. If you want to indicate the dirtiness of a document you can simply `or` them together. 

We reviewed your suggestion today and realized if we implemented this idea it would break a lot of apps that rely on the current behavior.

Sorry for any confusion or frustration this may have caused. Hopefully this explanation above will help you build your app.
