### ISSUE TITLE
Firebase Crashlytics: Upload symbols fail

### ISSUE THREAD

**Issue by IceFloe** [firebase/firebase-ios-sdk#5440]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.6.7
  * Firebase Component: Crashlytics
  * Component version: 4.0.0
  * Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem

When I am running command to upload file I am receiving an error which I can't understand, could you please explain to me what to do? Should I pass something else as parameter?

/***/Pods/FirebaseCrashlytics/upload-symbols -ai 1:905277975039:ios:da94a76797aaec6c859fca -p ios /***/MyApp.app.dSYM.zip -d

upload-symbols 3.3 build 22

Arguments:
Debug mode enabled
Google App ID: 1:905277975039:ios:da94a76797aaec6c859fca
Platform: ios
DSYM Paths: ["/***/MyApp.app.dSYM.zip"]

Fetching upload-symbols settings...
error: Could not fetch upload-symbols settings: An unknown error occurred fetching settings.

**Comment by samedson** [comment]
I believe the issue is you're passing a Google Service file to the `-ai` parameter. You want to use `-gsp` instead.

**Comment by IceFloe** [comment]
Sure, I did upload the build to firebase distribution already

**Comment by IceFloe** [comment]
I upload two builds already, I have two targets in the project both of them have their gsp file, but as documentation said If I am passing the -ai parameter it should upload dsym directly to the project, but it is not working.

**Comment by samedson** [comment]
Ah so I think the confusion is App Distribution and Crashlytics are separate. The upload can't complete because Crashlytics hasn't started the onboarding process for your app. We require you to go to the Crashlytics dashboard and get started in case customers need to set up their app some other way (eg. linking over from Fabric).

To fix, go to the Crashlytics dashboard, and click the "Next" button:
![Screen Shot 2020-04-22 at 2 12 46 PM](https://user-images.githubusercontent.com/555046/80017960-59d6b380-84a3-11ea-82de-98d40e7c4ea4.png)

**Comment by IceFloe** [comment]
You are right thank you, please provide better description in the error if you can. I am happy that it is working now :)
