### ISSUE TITLE
[FirebaseCrashlytics] Run script not packaged correctly

### ISSUE THREAD

**Issue by Blackjacx** [firebase/firebase-ios-sdk#5465]
### Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.23
  * Firebase Component: Crashlytics
  * Component version: 6.23
  * Installation method: Carthage

#### Steps to reproduce:

When I run `carthage update FirebaseCrashlytics` it does install the framework but it doesn't put the run script and the upload-symbols script inside the framework (like it is with Fabric and many other frameworks installed via carthge). I think the framwwork is packaged the wrong way in the [ZIP](https://dl.google.com/dl/firebase/ios/carthage/6.23.0/FirebaseCrashlytics-1ff9deb6fda17005.zip). The scripts should be in the `.framwork` folder otherwise they don't get installed by carthage.

**Comment by ryanwilson** [comment]
cc @TKBurner 

Thanks for the report. If I recall correctly (and as reported in #4720) there are some limitations we face and require extra steps - see the Crashlytics section at the bottom of https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage for the steps.

The reasoning for this can be found at https://github.com/firebase/firebase-ios-sdk/issues/4720#issuecomment-577213858

If you believe there is a workaround that addresses these issues, please let us know and re-open the issue! Otherwise the extra steps are the way to work around this. I wasn't aware of official Carthage support for Fabric but I could be missing something there.

**Comment by samedson** [comment]
Yeah just want to add to the rationale for why we pulled them out of the .frameworks. We had to resolve a bug a while back where Xcode (one of the 10.x versions) would automatically add `upload-symbols` as a swift library, and then fail to build apps as a result (because it's a command line tool).

**Comment by Blackjacx** [comment]
Okay I'm fine with that - sorry for duplicating this issue 👍
