### ISSUE TITLE
Every CI-built binary that runs unit tests is listed in our Firebase Crashlytics dashboard

### ISSUE THREAD

**Issue by jvannoord** [firebase/firebase-ios-sdk#5502]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4
  * Firebase SDK version: 6.23.0
  * Firebase Component: Crashlytics
  * Component version: _____
  * Installation method: `Zip file`

### [REQUIRED] Step 2: Describe the problem

It seems like the act of running the app once is causing the app version to be uploaded to the Firebase Crashlytics dashboard, *including* when running automated unit tests in an iOS simulator.

#### Steps to reproduce:

1. Build the code using Jenkins.
2. Run the unit tests in an iOS simulator using Fastlane `scan`

Every one of our CI-built binaries that executes a unit test appears to add itself to the Firebase Crashlytics dashboard. I've disabled as much of Firebase and Firebase Crashlytics as seems possible without completely unlinking the SDK, and each CI build still appears in our Crashlytics versions list.

This appears to be a behavior change from the Fabric-based Crashlytics sdk; this change muddies our dashboard UI with builds that no one will ever install. I noticed the behavior when we moved from Firebase 6.11.0 (+ Fabric Crashlytics) to 6.22.0, and it continues with 6.23.0.

More possibly pertinent info:
- There is no XCode build phase in the project where we execute `FirebaseCrashlytics/run`. (We manage symbol upload in a Jenkins Promotion.)
- FirebaseAnalytics is linked, but it is not explicitly initialized when executing tests.
- No behavior change when setting `FirebaseScreenReportingEnabled` to `NO` in the Info.plist.
- When testing, I call `Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(false)` in `application(_:, didFinishLaunchingWithOptions:)`
- app bundle id: com.faithlife.mobile

It seems like the act of running the app once is causing the app version to be uploaded to the Firebase Crashlytics dashboard. I would like the ability to opt out of this, if at all possible, which we would likely use in the case of non-public/non-beta binaries.

<img width="271" alt="Screen Shot 2020-04-29 at 9 01 23 AM" src="https://user-images.githubusercontent.com/1034121/80618330-0fe85300-89f8-11ea-90f4-7b1a91222298.png">

**Comment by samedson** [comment]
Hey thanks for reaching out @jvannoord.

Crashlytics gets versions when the app is first run with the Crashlytics SDK installed. Because this happens at startup, calling `setCrashlyticsCollectionEnabled(false)` won't prevent it (because you can't call methods until the SDK starts up).

To disable Crashlytics for the first run, we recommend setting the Info.plist value `FirebaseCrashlyticsCollectionEnabled` to false. Then, on versions / builds of your app where you want Crashlytics to start up, call `setCrashlyticsCollectionEnabled(true)`

Some more information here: https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#setcrashlyticscollectionenabled_:

**Comment by jvannoord** [comment]
Roger that. I'll give it a try and report back.

**Comment by jvannoord** [comment]
Setting the plist value to `NO` and changing the setting to `true` in the code gave me the behavior I wanted. Thanks a bunch!
