### ISSUE TITLE
Sign in with Apple doesn't throw accountExistsWithDifferentCredential

### ISSUE THREAD

**Issue by juniorklein** [firebase/firebase-ios-sdk#5545]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.2.1
  * Firebase SDK version: 6.15.0
  * Firebase Component: Auth
  * Component version: 6.15.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When I try to log with Facebook, for example, and user already has registered with same e-mail, the SDK throw an error with code 17012 (accountExistsWithDifferentCredential), but, for "Apple Sign In" no one error are throwing and the account, in Firebase Console no longer shows the e-mail option. After that, the user will no longer be able to login with e-mail and password.

#### Steps to reproduce:

1 - Create account with e-mail and password
2 - Logout
3 - Try to Login with Apple
4 - Login are complete with success (the problem ir here)

#### Relevant Code:

```

        let credential = OAuthProvider.credential(withProviderID: "apple.com", idToken: token, rawNonce: nonce)
        Auth.auth().signIn(with: credential) { (authResult, error) in
            if let error = error {
                NSLog("Log: signWithApple ERROR: %@", error.localizedDescription) // Error 17007
                fail?(error)
            }
            
            let user = Auth.auth().currentUser
            guard let uid = user?.uid else { return }
            
            ...
        }

```

**Comment by MeghaB** [comment]
Hey @juniorklein - in the case of Apple, as it guarantees that the email is verified, we're able to link the two accounts - which is why there's no error thrown for 'account exists.' Facebook doesn't provide the same guarantees around email verification, so we can't be sure that the person attempting to login owns that email account. So, we can't link them automatically, and throw the error that this account already exists. 

If the email/password login didn't have a verified email, we remove the previous path to login to avoid the following scenario:

Alice owns alice@email.com. Bob knows this, and signs in via email/password using 'alice@email.com' as his email address. Alice then signs in with Apple Sign In with alice@email.com. Alice then continues to access her account, and adds her shipping address to her in-app profile. Bob uses email/password login using alice@email.com, and now has access to Alice's shipping address, because he *claimed* to have access to alice@email.com, but that was never verified.
