### ISSUE TITLE
 Insecure IPC: Missing Sender Verification  

### ISSUE THREAD

**Issue by divyaKalusulingam** [firebase/firebase-ios-sdk#5578]
**Summary**
The application fails to verify the sender of a URL-based Inter-Procedure Communication (IPC) call.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.3
  * Firebase SDK version: 6.6.7
  * Firebase Component:Core, Messaging
  * Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem
**Explanation**
When a third party application or webview uses a URL to communicate with your application, the receiving application should verify that the sender matches a whitelist of applications that are expected to communicate with it. The receiving application has the option to verify the origin of the calling URL using the UIApplicationDelegate application:openURL:options: or UIApplicationDelegate application:openURL:sourceApplication:annotation: delegate methods.

**Comment by morganchen12** [comment]
Hey @divyaKalusulingam, verifying the URLs passed into your application is the responsibility of the implementer of the AppDelegate, not the responsibility of Firebase (since Firebase is a library and cannot account for every URL that should be verified across all of the apps that adopt it). If you feel that there's something Firebase can do to help in this regard, please let us know.
