### ISSUE TITLE
157240724: match message: One pre-install link matched for this device.

### ISSUE THREAD

**Issue by tapashR** [firebase/firebase-ios-sdk#5630]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.4.1 
  * Firebase SDK version: 6.21.0 
  * Firebase Component: Dynamic link
  * Component version: 4.0.8
  * Installation method: CocoaPods 

### [REQUIRED] Step 2: Describe the problem

The app opens dynamic link content a second time following app uninstall
 

#### Steps to reproduce:
**1. We have clicked the dynamic link when the app was not installed.
2. Installed the App.
3. Open the dynamic link  url in safari -> navigate to app from dynamic link -> it opens the target screen in the app—> dismiss the target screen —> uninstall the app —> Open the dynamic link  url in safari again -> navigate to AppStore from dynamic link -> Close Appstore -> Install fresh (from TF) —> open app —> it directly takes back to Target screen which was opened before.**

What happened? How can we make the problem occur?
following the reproduction step.

This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

**(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary *)options**
it always returns the link for share when I removed and install the app again. Getting the  match message: One pre-install link matched for this device  in FIRDynamicLink object every time I install the [application.]

This is the object I am getting **<FIRDynamicLink: 0x283ea7f80, url [https://stg.my.domain.com/1025672?type=profile&screenType=0&id=1623], match type: default, minimumAppVersion: N/A, match message: One pre-install link matched for this device.>**

"App still receiver the content of link shared. " , It is not normal behaviour.
**- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {    
    FIRDynamicLink *dynamicLink = [[FIRDynamicLinks dynamicLinks] dynamicLinkFromCustomSchemeURL:url];
    if (dynamicLink != nil) {
    [self handleIncomingDynamicLink:dynamicLink];
    return YES;
    }
}**

**Comment by tapashR** [comment]
@eldhosembabu  could you please update me on this, as this is urgent. Thanks.

**Comment by eldhosembabu** [comment]
Regarding the flow: 
**Open the dynamic link url in safari again -> navigate to AppStore from dynamic link -> Close Appstore -> Install fresh (from TF) —> open app —> it directly takes back to Target screen which was opened before.**

Does your FDL uses AppPreview page?

When you click the FDL when the app is not installed

**With App Preview Page:**
The App preview page is opened and when you click open button there(with the checkbox checked to copy the link; otherwise it would work similar to **Without App Preview Page** case), it will copies the actual dynamic link to pasteboard and navigates to the AppStore to install the app.
Regardless of whether the app is installed from app-store or not when you last clicked on the FDL, the link would stay in pasteboard and when you install the App from TF at a later point of time, the FDL SDK will retrieve the old copied link from pasteboard.

**Without App Preview Page:** 
A device fingerprint (DP) will be generated for that device and the link will be saved as a map of DP->Link in the server and then the user will be navigated to Appstore for installing the app. Regardless of whether the app is installed or not, the mapping DP-> Link will stay in server for **1 hour**. So if you install the app from TF within 1 hour, the FDL SDK will retrieve the link from server.

So to answer your question, this is intended behavior and we don't have a way to figure out whether user has installed the app in continuation with an FDL click or not.
