### ISSUE TITLE
C++ driver support

### ISSUE THREAD

**Issue by Natarajan77** [firebase/firebase-ios-sdk#5673]
Can you please tell me for firestore do you have driver support for c++ ? 

or if we have to use c++ it has to go thru from firebase SDK?

**Comment by dconeybe** [comment]
Hi @Natarajan77. Could you explain your use case more clearly? I'm not sure that I understand what you mean by "driver support". Are you referring to writing an OS-level device driver and using Firestore from there?

**Comment by Natarajan77** [comment]
For example if you take mongodb it has driver available for c++...like that does firestore has driver available to program with C++...we are developing in house application and planning to use firestore as nosql db....

**Comment by dconeybe** [comment]
Is the Firebase C++ API what you're looking for: https://firebase.google.com/docs/cpp/setup?

**Comment by Natarajan77** [comment]
This looks more specific to iOS and android 

Looking for web apps support to firestore using c++ driver

**Comment by dconeybe** [comment]
What about the "Set up a desktop workflow" section of https://firebase.google.com/docs/cpp/setup? This documents how to use the C++ SDK in a command-line app on a desktop.

**Comment by morganchen12** [comment]
@Natarajan77 if you mean a server-side Firestore C++ SDK, we currently don't provide one. We do provide [various other server SDKs](https://firebase.google.com/docs/firestore/client/libraries#server_client_libraries).

**Comment by Natarajan77** [comment]
Example like if u take mongodb nosql db it has c++ drivers to interact with db...it is more server side sdk ...looks from the last post u don’t Similar  one 

So in case for web apps (C++) for server side sdk to access firestore, can they use fire base?

**Comment by Natarajan77** [comment]
> What about the "Set up a desktop workflow" section of https://firebase.google.com/docs/cpp/setup? This documents how to use the C++ SDK in a command-line app on a desktop.


We are going to develop for web apps and run it from k8 will the desktop version will help??

**Comment by wilhuff** [comment]
We don't have a server-side SDK for Firestore in C++.

The desktop C++ SDK is not optimized for use on a server. Server SDKs assume a low-latency, reliable connection to the backend, are designed to maximize throughput, and assume every thread is working independently. This is comparable to the way the MongoDB C++ Driver works.

The mobile/web/desktop SDKs are optimized for high-latency, potentially unreliable connections to the backend, are designed to maximize consistency for a single user, and assume every thread is working toward presenting a unified view for that user. These SDKs work on a principle of buffering changes locally and eventually synchronizing in the background. Using one of these SDKs in a server is _possible_, but it will be difficult because you're working against the assumptions built into the SDK.

As @morganchen12 notes, there are server SDKs in other languages. Your best bet will be using one of the Firebase Admin SDKs (in Java, Python, Node.js, or Go). Close behind are the Google Cloud SDKs (which additionally include C#, PHP, and Ruby).
