### ISSUE TITLE
fetchAndActivate ignores minimumFetchInterval value

### ISSUE THREAD

**Issue by jhandguy** [firebase/firebase-ios-sdk#5762]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 11.5 (11E608c)
  * Firebase SDK version: 6.26.0
  * Firebase Component: RemoteConfig
  * Component version: 6.26.0
  * Installation method: `Carthage`

### [REQUIRED] Step 2: Describe the problem

RemoteConfig.remoteConfig().fetchAndActivate completion's status is .successUsingPreFetchedData even though minimumFetchInterval was set to 0

#### Steps to reproduce:
```
let configDefaults = ["foo": false as NSObject]
RemoteConfig.remoteConfig().setDefaults(configDefaults)

let settings = RemoteConfigSettings()
#if DEBUG
settings.minimumFetchInterval = 0
#else
settings.minimumFetchInterval = 120
#endif
RemoteConfig.remoteConfig().configSettings = settings

RemoteConfig.remoteConfig().fetchAndActivate { status, error in
    assert(status == .successFetchedFromRemote) // this assertion fails
}
```

**Comment by ncooke3** [comment]
Hi @jhandguy,  

After exploring the issue, I wanted to provide some info about what is likely going on!

When remote config values are updated, there is a timestamp [`lastETagUpdateTime`](https://github.com/firebase/firebase-ios-sdk/blob/851b0390f6739725c5aa04108046f9339b7d3455/FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h#L80) that is recorded to mark the time of the update. When these values are pulled from the server into your app, they are applied and the [`lastApplyTimeInterval`](https://github.com/firebase/firebase-ios-sdk/blob/851b0390f6739725c5aa04108046f9339b7d3455/FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h#L74) is recorded. When `minumumFetchInterval` is set to zero, you can fetch to remote config with no minimum time between fetches. If the remote config values haven’t changed from one fetch to the next, then we know the `lastETagUpdateTime` remains the same. If this is the first time these values have been pulled into your app, the `lastApplyTimeInterval` is updated to now, if not, then `lastApplyTimeInterval` was already set when the values were first fetched and applied in your app. Either way, since the fetched remote config values are the same and not newer, then we say that the “Most recent fetched config is already activated.” and return the `.successUsingPreFetchedData` since the `fetchAndActivate` was successful and we ended up using the same data that had been prefetched. 

Let me know if this helps!

**Comment by jhandguy** [comment]
Hi @ncooke3,
After doing some testing as you suggested, you're right, the Remote Configs are indeed getting updated when a change is actually published. We might want to consider renaming the `.successUsingPreFetchedData` which is I think a bit misleading then.
Either way, I'm closing this issue, thanks for the swift reply!
