### ISSUE TITLE
[Firestore] No way to get subcollections (unknown path) from a DocumentReference

### ISSUE THREAD

**Issue by thecoffeehog** [firebase/firebase-ios-sdk#5818]
Via https://github.com/FirebaseExtended/flutterfire/issues/2739

**Problem**
It's frustrating to change the architecture of a Firestore DB just because there is no DIRECT way to get a list of subcollections present in a document.

**Proposed Solution**
A method to get names/references of subcollections in the `DocumentReference` Class, just like we have a way to get `CollectionReference` for a known Collection.

**Comment by schmidt-sebastian** [comment]
(Response copied from https://github.com/firebase/firebase-android-sdk/issues/1664)

@thecoffeehog Thanks for taking the time to file this issue!

The Firestore backend supports listing of subcollections via the ListCollections RPC. This method, however, is considered a metadata operation and only exposed via our Server SDKs (e.g. https://googleapis.dev/nodejs/firestore/latest/Firestore.html). Listing arbitrary collections via Firebase third-party credentials (the credentials used by the Mobile SDKs and enforced by Firebase Security Rules) is currently not possible due to its security implications.

While we will likely not expose this functionality in our Mobile SDKs soon, you can file a public feature request of against the Firestore product here: https://issuetracker.google.com/savedsearches/5337669
