### ISSUE TITLE
About:blank - the phone verification reCaptcha

### ISSUE THREAD

**Issue by kutakmir** [firebase/firebase-ios-sdk#591]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 9.2
Using FirebaseABTesting (1.0.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseAuth (4.4.1)
Using FirebaseCore (4.0.13)
Using FirebaseDatabase (4.1.3)

### [REQUIRED] Step 3: Describe the problem

When logging in with phone number on a device I am getting "invalid token" upon verification.

#### Steps to reproduce:

Run the project with phone auth, log in with a phone number. 

#### Relevant Code:

```
            PhoneAuthProvider.provider().verifyPhoneNumber(phoneNumber, uiDelegate: nil) { (verificationID, error) in
                if let error = error {
                    // This line prints out the "Invalid token"
                    print(error.localizedDescription)
                    return
                }
                
            }
```

**Comment by ryanwilson** [comment]
Hi @kutakmir, sorry to hear you're having issues.

Can you check the error code from [this header](https://github.com/firebase/firebase-ios-sdk/blob/cb5f3efd3ab53561afd7de625d16d014d14374dd/Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h#L64) in order to figure out what the error is? My guess is `FIRAuthErrorCodeMissingAppToken`. Do you have push notifications (APNS) set up?

There are instructions on the [Firebase Auth](https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification) site to set up both silent push notifications and reCAPTCHA verification.

cc @protocol86 - are both the push notifications and reCAPTCHA necessary or is it possible to only use one verification method?

**Comment by protocol86** [comment]
Both push notifications and reCAPTCHA are strongly advised, the library enforces reCAPTCHA be set up.

@kutakmir I would also like to know the exact error that you are encountering here.

**Comment by morganchen12** [comment]
@kutakmir please re-open if this is still an issue.

**Comment by viniciusfont** [comment]
Hi, did you solve the problem? My application was working normally, but out of nowhere, it started to return white page from recaptcha.

**Comment by handu** [comment]
@viniciusfont Mine too. Have you figured out what the problem is?

**Comment by viniciusfont** [comment]
@handu Not yet. As I'm using react-native, I opened an issue on react-native-firebase repository, in the hope of getting an awnser. [https://github.com/invertase/react-native-firebase/issues/1363](https://github.com/invertase/react-native-firebase/issues/1363)

**Comment by viniciusfont** [comment]
It worked, apparently it was a temporary problem.
