### ISSUE TITLE
FIRComponentContainer.h not found on runtime

### ISSUE THREAD

**Issue by bukanriko** [firebase/firebase-ios-sdk#5983]
#### Relevant Code:
<img width="819" alt="Screen Shot 2020-07-07 at 10 03 53" src="https://user-images.githubusercontent.com/30143182/86689061-3b5f6d80-c039-11ea-9ed8-192935d4cb39.png">

This is my Podfile
<img width="758" alt="Screen Shot 2020-07-07 at 10 04 58" src="https://user-images.githubusercontent.com/30143182/86689342-79f52800-c039-11ea-9935-2137e7fe6e94.png">

**Comment by ryanwilson** [comment]
Hey @bukanriko - sorry for the troubles. Typically this is a bad state with CocoaPods or Xcode. Can you try running `pod update`, cleaning your derived data and the build folder, and try again?

If that doesn't help, it's worth trying in a new project or our quickstarts to see if it reproduces there as well. If we have a reproduction we'll be able to track it down further, otherwise there may not be a ton we can do on our end. Thanks!
