### ISSUE TITLE
 Error installing GoogleDataTransportCCTSupport

### ISSUE THREAD

**Issue by guitorioadar** [firebase/firebase-ios-sdk#5991]
## Description of  environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.27.0
  * Firebase Component: Messaging, GoogleDataTransportCCTSupport
  * Component version: (3.2.0)
  * Installation method: `CocoaPods`

## Description of the problem
<img width="1098" alt="Screenshot 2020-07-07 at 10 36 00 PM" src="https://user-images.githubusercontent.com/13439371/86814254-f5d78a80-c0a2-11ea-8e86-10f29d9b6998.png">

I am facing this problem when I write `pod install` on terminal

I couldn't find what is wrong am I doing?

**Comment by morganchen12** [comment]
When pod install fails like this, it outputs the command it was running that failed. In your case it's 

```
git clone https://github.com/firebase/firebase-ios-sdk.git ...
```

You can try re-running this command in isolation to see if it's an intermittent network failure. If the error persists you'll need to debug it on your machine.

Closing this issue since it's not an issue with Firebase. You may also be able to find help on StackOverflow.
