### ISSUE TITLE
impliment firebase iOS ml vision bundle ressource (.tflite .pb) with FirebaseMLVision

### ISSUE THREAD

**Issue by soufianee** [firebase/firebase-ios-sdk#6038]
Hi,

i have worked with firebase iOS in device FirebaseMLVisionFaceModel and FirebaseMLVisionTextModel using Carthage. nevertheless those two libs increase the app size tremendously.

So I ask if there a way to do our implimentation directly of the models ressource bundles (.tflite .pb) with FirebaseMLVision or other idea without adding FirebaseMLVisionFaceModel and FirebaseMLVisionTextModel frameworks.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/11293769/87417715-7ed15300-c5c8-11ea-9d76-0e02a10527d9.png">

thanks in advance.

**Comment by soufianee** [comment]
hi,

is there any method in swift  to impliment the models in ressource bundles (.tflite .pb).

**Comment by morganchen12** [comment]
The Carthage libraries are a lot larger than they will be in your final app bundle due to each framework being packaged as a fat static binary with multiple architecture slices. You can get a better picture of your full app download size by downloading your app through TestFlight.

The tflite models used by MLVision are not available for direct consumption.
