### ISSUE TITLE
FIRRemoteConfigValue doubleValue never returns nil

### ISSUE THREAD

**Issue by jacobp100** [firebase/firebase-ios-sdk#6188]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: `11.6`
  * Firebase SDK version: `6.6.7`
  * Firebase Component: `RemoteConfig`
  * Component version: `6.23.0`
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Get the config value for a non existent key with no default. Read `numberValue` from the config value. I expect this to return `nil`, but it always returns `0`.

From the [source](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseRemoteConfig/Sources/FIRConfigValue.m#L50), this value cannot return `nil`.

If `stringValue` is `nil`, `stringValue.numberValue` will return `nil`, which will be implicitly casted to the double `0`.

If `stringValue` is not `nil` and not a valid number, `stringValue.numberValue` will return the double `0`, as per Apple's documentation.

#### Relevant Code:

```swift
remoteConfig.configValue(forKey: "non-existent-key-with-no-defaults").numberValue == nil // fails
```

**Comment by morganchen12** [comment]
#6192 may not be submitted since it would make iOS's implementation of remote config deviate from other platforms. It's possible we just change the nullability annotation instead to make `numberValue` return a nonnull number instead, though this is still pending some discussion.

If you want to check for the absence of a value in the config payload, you can do so by looking at the [`source` property](https://firebase.google.com/docs/reference/swift/firebaseremoteconfig/api/reference/Classes/RemoteConfigValue#declaration_5).

**Comment by paulb777** [comment]
Marking for Firebase 7 major release, since we should resolve this either of the two ways described above by then.
