### ISSUE TITLE
FR: Add GoogleTagManager to Carthage installation

### ISSUE THREAD

**Issue by JuLink** [firebase/firebase-ios-sdk#6200]
### Feature proposal

* Firebase Component: GoogleTagManager

I would like to be able to install GoogleTagManager framework via Carthage. I did not find any documentation on how to install it like this.

**Comment by joshuapoq** [comment]
Agreed. The docs for GTM are awful and its name conflicts with "Google Toolbox for Mac". Who comes up with naming at Google? Also SwiftPM support and documentation wouldn't go amiss.

**Comment by paulb777** [comment]
Since Google Tag Manager is not part of Firebase, I'm going to close. Please follow up at the [Google Tag Manager support site](https://support.google.com/tagmanager?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fsupport%2F&hl=en#topic=3441530).
