### ISSUE TITLE
Wrong object type on FIRCLSURLSessionConfiguration creation

### ISSUE THREAD

**Issue by makadaw** [firebase/firebase-ios-sdk#6210]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.29.0
  * Firebase Component: Crashlytics
  * Component version: 4.3.1
  * Installation method: `CocoaPods`

### [REQUIRED] Step 2: Describe the problem

`+ (NSURLSessionConfiguration *)defaultSessionConfiguration` and `+ (NSURLSessionConfiguration *)ephemeralSessionConfiguration` method of `FIRCLSURLSessionConfiguration` class required return type to be `NSURLSessionConfiguration`. 
https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/FIRCLSURLSession/FIRCLSURLSessionConfiguration.m#L34
But in some cases it returns instance of FIRCLSURLSessionConfiguration (`return [self new];`). `FIRCLSURLSessionConfiguration` is not subclass of the NSURLSessionConfiguration https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/FIRCLSURLSession/FIRCLSURLSessionConfiguration.h#L21.
During the build, Xcode complained that types are mismatched. This can be suppressed by explicit cast to `NSURLSessionConfiguration`.

#### Steps to reproduce:

Build with Xcode and check warnings

**Comment by morganchen12** [comment]
Based on [this code](https://github.com/firebase/firebase-ios-sdk/blob/031814cecd4145b88237db3813e7c999623d2296/Crashlytics/Crashlytics/FIRCLSURLSession/FIRCLSURLSession.m#L44) that method should always return a valid NSURLSessionConfiguration object on iOS versions that have NSURLSession support (8+).

@samedson can we get rid of FIRCLSURLSessionConfiguration since our support floor is above iOS 8, or does it need to remain for legacy reasons?

**Comment by samedson** [comment]
I believe we can get rid of FIRCLSURLSessionConfiguration now - we are following Firebase's support floor.
