### ISSUE TITLE
Demo App Firebase SDK in custom swift static library

### ISSUE THREAD

**Issue by soufianee** [firebase/firebase-ios-sdk#6222]
hi everyone,

I work in a swift static library including firebase libraries and I get lot of issues within. I don't find a clear documentation or project samples about it.

please can someone share with us some useful documentation or project samples.

**Comment by maksymmalyhin** [comment]
Hi @soufianee, thank you for the request. In general, Firebase SDK was not originally designed to be used in another SDK, that's why there are no examples or documentation for it.

I think, working through your specific issues will be a faster approach to unblock you. Would you mind creating a sample project demonstrating the Firebase features you would like to use and the issues you encounter? If you post it to a separate GitHub repo we can work together on resolving the issues.

Thank you for your contribution!

**Comment by soufianee** [comment]
hi,

here is a GitHub repo for a demo project to create a static lib wrapping firebase ML vision text recognition :

https://github.com/soufianee/DemoFireBaseStaticLib

for information, I work with carthage. So you must add the binaries related to firebase ML vision text recognition.

thank you for you interest to my topic.

**Comment by maksymmalyhin** [comment]
@soufianee Thank you for sharing the sample project. We will take a look at it in more details. So far I noticed that you would like to use on device MLKit methods that are being deprecated. I suggest to use the new Google ML Kit SDK instead for on-device processing. You can find more details on it at [ML Kit Migrating for iOS guide](https://developers.google.com/ml-kit/migration/ios). Could you please try the new SDK and let us know if you still experience the issues?

**Comment by soufianee** [comment]
@maksymmalyhin thank you for your interest, is a big need the integration of using firebase in another SDK. it aims to module reusing and optimise development time. 

i m always on it, I have found some solutions here.

https://medium.com/@yuliiasynytsia/link-static-c-library-to-swift-framework-as-a-private-module-97eae2fec75e

any update I will share it in the demo project.

please if you have any solution in your side or documentation that will be helpful.

**Comment by paulb777** [comment]
I'm going to close this one since there are no clear next steps on our side. We can continue the conversation though.
