### ISSUE TITLE
Documentation Issue: Parameter 'selected_port[out]' not found in the function declaration 6.31.0

### ISSUE THREAD

**Issue by gilrodar** [firebase/firebase-ios-sdk#6340]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.6
  * Firebase SDK version: 6.31.0
  * Firebase Component: Firestore
  * Component version: 1.17.0
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

When you run the application, this message appears

"Parameter 'selected_port[out]' not found in the function declaration"
"Did you mean 'selected_port'?"

<img width="486" alt="Captura de Pantalla 2020-08-26 a la(s) 15 17 05" src="https://user-images.githubusercontent.com/13817108/91352497-8e3ee100-e7af-11ea-926f-ce946f8b7aea.png">

<img width="273" alt="Captura de Pantalla 2020-08-26 a la(s) 15 19 51" src="https://user-images.githubusercontent.com/13817108/91352530-9860df80-e7af-11ea-8454-a059c758ea6f.png">

**Comment by paulb777** [comment]
Might be worth another try to remove this `--allow-warnings`?  Since it catches this problem - https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/firestore.yml#L186

**Comment by dconeybe** [comment]
Hi @gilrodar! The warning about `selected_port` is actually from one of Firestore's dependencies, specifically grpc. Here is where it comes from:

https://github.com/grpc/grpc/blob/dca24b8de56272111365a2a3521f59734da9990e/include/grpcpp/server_builder.h#L131

Please open an issue in the grpc repository so that the appropriate people can prioritize and address it. Since there is no action in this repository, I'm going to close this ticket. Feel free to re-open if you feel that this resolution is inadequate.

**Comment by dconeybe** [comment]
Actually, my colleague @wilhuff pointed out to me that we *can* suppress this warning in Firestore using `SUPPRESS_DOCUMENTATION_WARNINGS_BEGIN` from https://github.com/firebase/firebase-ios-sdk/blob/bdf84c0a7ba928fa1e98658a90b8775f0ef96c95/Firestore/core/src/util/warnings.h#L72

I'll open a PR to make the required change to suppress the warning.
