### ISSUE TITLE
Add strongly typed query, sort and updates in Firestore

### ISSUE THREAD

**Issue by lorenzofiamingo** [firebase/firebase-ios-sdk#6351]
### Feature proposal

* Firebase Component: Firestore

I hope this is not duplicate, and I think you already thought about this.
I think would be great to add these strong methods to FirestoreSwift, and use comparison operators.

I thought and tried by myself different approaches:

## Convert `KeyPath` to `String`
This as two problems: 

1. `KeyPath` can be converted to `String` only if its Root is an `NSObject` and its property are marked with `@objc`

2. If the `Codable` conformance is obtained specifying custom `CodingKeys` the converted string won't match the server field name.

## Custom `Encoder`
I wrote a custom encoder that converted the `Codable` struct to a dictionary of type `[String: Any]` where String was the path to the node. Then I could use the keypath to retrieve the node and use the node to find the correct string key.
This required the value of the dictionary to be `Equatable` and also has the problem that multiples values can be in the dict and multiple keys could be the correct ones.

## Custom Protocol
Instead of `Codable`, these new methods could be requiring a Protocol like that

    protocol CodingKeysCodable: Codable {
        associatedtype CodingKeys: CodingKey
    }

this will remove the compiler magic autogenerated CodingKeys, but we'll do this:

    struct Person: CodingKeysCodable {
        
        let name: String
        
        enum CodingKeys: String, CodingKey {
            case name = "name"
        }
    }

    func update<T>(key: T.CodingKeys, of model: T) where T: CodingKeysCodable {
        let key = key.stringValue
        // Update the single field
    }

A problem with this is that you can't access to nested CodingKeys

**Comment by dconeybe** [comment]
Hi @lorenzofiamingo! Thank you for taking the time to open a feature request with Firestore. This sounds like a good idea, but it's unclear to me what change to Firestore you are suggesting. Could you provide some or all of the following information to help me understand?

1. What class or classes would be affected?
1. What change would you like to see in these classes?
1. As a consumer of Firestore, could you provide some code samples of what code would look like with the current Firestore API and what it would look like with your suggested feature?
1. Do you have an immediate use case in mind for this feature? If yes, could you provide it?
1. What other use cases for yourself or others can you think of?
1. If you have specific changes to the code base in mind, could you open a PR or attach a patch?

Thank you!

**Comment by lorenzofiamingo** [comment]
Hi, thanks for the reply!

> 1. What class or classes would be affected?

Query, Document Reference

> 2. What change would you like to see in these classes?

New methods that avoid using raw strings

> 3. As a consumer of Firestore, could you provide some code samples of what code would look like with the current Firestore API and what it would look like with your suggested feature?

**Example 1**

    Firestore.firestore().collection("users").whereField("name", isEqualTo: "Sam")

will become

    Firestore.firestore().collection("users").query(User.self, where: \.name == "Sam")

or

    Firestore.firestore().collection("users", of: User.self).query(\.name == "Sam")

**Example 2**

    Firestore.firestore().collection("users").order(by: "name")

will become

    Firestore.firestore().collection("users").sort(User.self, by: \.name)

or

    Firestore.firestore().collection("users", of: User.self).sort(by: \.name)

**Example 3**

    Firestore.firestore().collection("users").updateData(["name": "Johnny", "tickets": 1])

will become

    let editedUser = User(name: "Johnny", surname: "Stecchino", tickets: 1)
    Firestore.firestore().document("users/userid").update([\.name, \.tickets], from: editedUser)

> 4. Do you have an immediate use case in mind for this feature? If yes, could you provide it?

Who is using FirestoreSwift will be able to make strong typed queries, updates, and sortings

> 5. What other use cases for yourself or others can you think of?

I saw in your roadmap you would like to implement Combine publishers, would be great to see KeyPath in those pubs.

> 6. If you have specific changes to the code base in mind, could you open a PR or attach a patch?

In my opinion, until Codable will not expose the autogenerated CodingKeys, will be impossible to do that without a custom protocol. If I'll code something I will add this here.

**Comment by dconeybe** [comment]
Hi @lorenzofiamingo. We will be discussing and considering this feature request internally. Thank you for taking the time to write it up. I have no ETA but I will update this issue once I have an update (in the next 2-3 weeks).

**Comment by dconeybe** [comment]
Hi @lorenzofiamingo. We have discussed internally and decided not to pursue this feature. Thank you for making the request, though, and doing the up-front research. It was very thorough and well thought-out. Our decision was reached because the limitations of the feature detract from its usefulness to a degree that the benefits do not justify the work involved.

Using `KeyPath` would be ideal; however, there is no way to get the name of a property from a `KeyPath` object. Without the name of the property we cannot form a query that can be executed or determine which field to update. For example, in `Firestore.firestore().collection("users").sort(User.self, by: \.name)` there is no way for the implementation of `sort()` to go from the `KeyPath` object to which the compiler will convert `\.name` to the string `"name"`.

You proposed the idea of `CodingKeysCodable` that data classes would need to adopt in order to work with the proposed API. Requiring class authors to manually write their own `CodingKeys` is error-prone and cannot be enforced to be a `String enum`. And, as you mentioned, even if classes did implement this property then it would only support accessing the top-level members of the class, and not any of the nested members.

For these reasons we've decided not to implement this feature. So I am going to close this issue. Perhaps future versions of Swift will provide the necessary language support and we can re-visit. If you disagree with our conclusion then please feel free to reply with your comments. Thanks again!
