### ISSUE TITLE
Upgrading Firebase/Crashlytics past 6.31 causes error: 'FirebaseCore/FirebaseCore.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by aaronbrethorst** [firebase/firebase-ios-sdk#6479]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.7 or 12.0 (repros on both)
  * Firebase SDK version: 6.32.2 (`Firebase/Crashlytics (6.32.2)`)
  * Firebase Component: Core
  * Component version: 6.10.2
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

Building my Swift/Objective-C mixed app with the latest version of 'Firebase/Crashlytics' results in the error:

```
'FirebaseCore/FirebaseCore.h' file not found with <angled> include; use "quotes" instead
```

However, resetting my Podfile to include:

```
pod 'Firebase/Crashlytics', '=6.31.0'
```

fixes the error. I have a hunch that the problem stems from https://github.com/firebase/firebase-ios-sdk/pull/6367

<img width="922" alt="image" src="https://user-images.githubusercontent.com/2254/93408200-d4381380-f848-11ea-95a7-de58572e1763.png">

#### Steps to reproduce:

In my case, the problem is reproducible when I upgrade `pod 'Firebase/Crashlytics'` past 6.31.0.

#### Relevant Code:

See above. If a full sample project is necessary to repro, please let me know and I'll do what I can to provide one.

**Comment by ryanwilson** [comment]
Hi @aaronbrethorst - sorry for the troubles you're seeing.

I'm unable to reproduce this with the quickstarts, and I'd be surprised if this wasn't an issue with the state of Xcode or the project. Although that line did change recently, prior to version 6.28 we've had Firebase.h import FirebaseCore like that for years with no issues. We only modified it in June (#5884) for Swift Package Manager support before we fixed the file structure to allow SwiftPM to use angled brackets for includes instead of quotes, but CocoaPods should have always been using the angled bracket imports.

It may be helpful to run through deleting derived data, potentially even running `pod deintegrate` and then `pod install` as well to try to clear out any CocoaPods state. If the issue still persists, a sample project or repro in the quickstart would be necessary for us to make further progress.

Thanks!

**Comment by maksymmalyhin** [comment]
@aaronbrethorst Sorry you encountered the issue. A sample project will be really helpful.

**Comment by paulb777** [comment]
This problem might be addressed with CocoaPods 1.10

**Comment by aaronbrethorst** [comment]
@ryanwilson Thanks for the recommendations. I'd tried cleaning derived data, `deintegrate`ing and `installing before opening this issue. I'm going to stick with 6.31.0 for the time being as it is working for me, and I need to ship products. I'll revisit this in the future if it doesn't simply work itself out through tooling changes in the future. Thanks!

**Comment by azizimarouan** [comment]
This happened to me also when I updated the pods! 
<img width="925" alt="Screen Shot 2020-10-15 at 6 21 28 PM" src="https://user-images.githubusercontent.com/36233629/96164582-503e7d80-0f13-11eb-9f69-95b5f4bb5f52.png">
