### ISSUE TITLE
FR: Remove gRPC and BoringSSL from Package.swift

### ISSUE THREAD

**Issue by andlang** [firebase/firebase-ios-sdk#6532]
### Feature proposal

* Firebase Component: SPM

First, I want to thank you for the SPM version. That makes dependency management a lot easier.

But would it be possible to remove gRPC and BoringSSL from that version? In my project I included only FirebaseAnalytics and the package dependencies resolving went up from 40 seconds to 240 seconds, because those are both huge repositories and count for 80% checked out data in my project.

Are they necessary at all as SPM dependencies and if so, could they also be included as binary dependencies?

**Comment by paulb777** [comment]
@andlang Thanks for the request. We'll investigate solutions as we progress in the beta.

Some initial ideas:
 - Avoid binary dependencies because they're more challenging to provide platform coverage and the SPM binary implementation is early and somewhat fragile.
 - Make more minimal forks of the gRPC and BoringSSL repos since they include many files that have nothing to do with Apple platform support.

**Comment by paulb777** [comment]
Closing this to consolidate the conversation at #6606
