### ISSUE TITLE
XCode 12 Preview Crashes when adding Firebase SDK Swift UI 2.0

### ISSUE THREAD

**Issue by StanfordLin** [firebase/firebase-ios-sdk#6574]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: latest (I just use 'pod' Firebase)
  * Firebase Component:  Core
  * Component version: n/a
  * Installation method: CocoaPods

### [REQUIRED] Step 2: Describe the problem

https://stackoverflow.com/questions/64038620/xcode-12-swiftui-cannot-preview-in-this-file-failed-to-update-preview/64076332#64076332

After I create a new swift UI  project and attempt to add Firebase SDK particularly, the configuration step, the Preview doesn't work and states “failed to update preview”… review to stack overflow post above

Tbh, not sure if this is a Firebase-specific problem or XCode problem but I think it's still important if someone can look into this. After adding UIApplicationDelegate in the new swift ui app, the previews stop working. The build succeeds and the app can be ran without a hitch on a simulator, just not preview.

#### Steps to reproduce:

What happened? How can we make the problem occur?
Preview just fails

1. Create new XCode SwiftUI iOS app project
2. pod init
3. Add Firebase and pod install
4. Add Google-Info.plist file
5. Make UIApplicationDelegate based off the new SwiftUI, speaking of which documentation needs to be updated
6. Try to run XCode preview

#### Relevant Code:

Breaking code: In your @main struct class, this is what it would look like with the new config code for Firebase using the SwiftUI:
```



import SwiftUI
import Firebase

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        print("Setting up firebase")
        FirebaseApp.configure()
        return true
    }
}


@main
struct TestApp: App {
    

    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}


```
The problem goes away but then I can't use Firebase on preview:
```

import SwiftUI
import Firebase

class AppDelegate: NSObject, UIApplicationDelegate {
//    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
//        print("Setting up firebase")
//        FirebaseApp.configure()
//        return true
//    }
}


@main
struct TestApp: App {
    

//    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

```

**Comment by StanfordLin** [comment]
I've also tried using Peter Friese's new way of configuring firebase and it still doesn't work

https://github.com/peterfriese/JewelCase/blob/main/code/JewelCase/App/JewelCaseApp.swift

I get this error:

`MessageSendingError: Connection interrupted: send previewInstances message to agent`

**Comment by ppoh71** [comment]
I am having the same issue:

`System Integrity Protection: enabled

Crashed Thread:        3  Dispatch queue: com.google.GDTCORFlatFileStorage

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager enumeratorAtURL:includingPropertiesForKeys:options:errorHandler:]: URL is nil'
terminating with uncaught exception of type NSException
`

Something wrong with GoogleDataTransport/GDTCORLibrary ?

**Comment by ryanwilson** [comment]
@StanfordLin I was able to get the original error message only when my `GoogleService-Info.plist` wasn't available. 

After adding my `GoogleService-Info.plist` I was able to get the same error that @ppoh71 received. This was a recent change so I think there's something different in the SwiftUI Preview environment that isn't being picked up - I'll take a look and see what I can find.

Thanks for the reports!

**Comment by maksymmalyhin** [comment]
The issue may be related to #6540. Let me take a look in more details.

**Comment by maksymmalyhin** [comment]
The issue mentioned in the  [comment](https://github.com/firebase/firebase-ios-sdk/issues/6574#issuecomment-699651985) should be fixed by #6580.

**Comment by ppoh71** [comment]
yes, downgrading GoogleDataTransport to 7.4.0 to  7.3.0
pod 'GoogleDataTransport', '7.3.0'
fixes the problem

**Comment by maksymmalyhin** [comment]
The fix #6580 is scheduled for the next release. As a temporary workaround, a previous version of `GoogleDataTransport` may be used (as @ppoh71 [mentioned](https://github.com/firebase/firebase-ios-sdk/issues/6574#issuecomment-700055390)).

Thank you everyone for the information and sorry for the troubles.

**Comment by rbevans-ugh** [comment]
When I run `pod 'GoogleDataTransport', '7.3.0'` from terminal I'm getting an error,

```
[!] Unknown command: `GoogleDataTransport,`
Did you mean: deintegrate?
```

**Comment by maksymmalyhin** [comment]
@rbevans-ugh The line `pod 'GoogleDataTransport', '7.3.0'` should be added to the `Podfile` near to other Firebase pods definitions. If you use Firebase 6.33.0 this will not work unfortunately because version `GoogleDataTransport` 7.4 version was locked in Firebase Core podspec. In this case you may temporary lock on unreleased GoogleDataTransport version with the fix:
```
pod 'GoogleDataTransport', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :commit=>'38be2cc'
```

Could you please try it an let know if you still have issues?

**Comment by rbevans-ugh** [comment]
Thanks @maksymmalyhin.  I probably should not have deleted my comment, but after some searching that's what I realized that's what I was supposed to do(new to Pods).  I was also running `Pod install` and should have been running `Pod update`.  Thanks for the help!

**Comment by aweiner42** [comment]
Also thanks @maksymmalyhin though I am still seeing the crash with the modified pod line while trying to preview.
Could it be related tot he app name is XCPreviewAgent.app/XCPreviewAgent but the GoogleService-Info.plist refers to my targets app name?

**Comment by maksymmalyhin** [comment]
@aweiner42 There is some basic validation of `GoogleService-Info.plist` but the name mismatch should not lead to the crash. 

I would suggest to get the exact crash from the Swift UI diagnostics report and update the current issue with your discovery or create a new one if the crash is in Firebase code but doesn't look related to the current issue. 

To get the report you may follow the steps from the screenshot:
<img width="1003" alt="Screen Shot 2020-10-05 at 5 19 40 PM" src="https://user-images.githubusercontent.com/1841926/95133541-7acc5180-072f-11eb-8e4c-109558e60aa3.png">

Then `CrashLogs` folder should contain recent relevant crash logs.

**Comment by aweiner42** [comment]
@maksymmalyhin thanks, I have been living in that diagnostic file trying a few things as I think I am chasing something different. for me when I try previewing a working apps controller I can't get past  FirebaseApp.configure(). With the FirebaseApp.configure()  I get
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
terminating with uncaught exception of type NSException
abort() called

Tnd when substitute to code in ICMSViewController below to see if it is getting the code from the bundle (which also the app runs with fine) I get the error below which leads me to think its not finding the plist in the right bundle. (so close too):
         let filePath = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist")!
         let options = FirebaseOptions(contentsOfFile: filePath)
        FirebaseApp.configure(options: options!)
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file ICMSArt_PreviewReplacement_ICMSViewController_2/ICMSViewController.swift, line 232

thanks again for any thoughts...
