### ISSUE TITLE
Avoid Xcode 12 warnings

### ISSUE THREAD

**Issue by tbechtum** [firebase/firebase-ios-sdk#6595]
### Usage 

Using latest version in Swift project
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'

Facing Xcode 12.x warnings in the following pods

1. Firebase
2. FirebaseAnalytics
3. FirebaseCore
4. FirebaseCoreDiagnostics
5. FirebaseCrashlytics
6. FirebaseInstallations
7. GoogleDataTransport
8. GoogleUtilities
9. GoogleAppMeasurement
10. nanopb

The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### Usage Details
  - Language: Swift
  - Platform: iPhone
  - iOS Version: iOS 9 - 14

### Feature proposal
Better support Xcode 12 and avoid 10 warnings related to iOS 8. Move the target of the related projects to iOS 9, thanks.

**Comment by ryanwilson** [comment]
Hi @tbechtum - thanks for the report.

Since it's a breaking change to bump the minimum iOS version (we'd be removing support for an iOS version) it's going to have to wait for a breaking change, but the good news is that it's not far off and we've already implemented the fix in https://github.com/firebase/firebase-ios-sdk/pull/6517. You can keep an eye on the [Firebase 7 Milestone](https://github.com/firebase/firebase-ios-sdk/milestone/37) to see as things get closer to launch, but this issue will be resolved soon enough. Since the code has already landed I'll close this, thanks for the report!
