### ISSUE TITLE
FR: SPM support for GoogleTagManager and libGoogleAnalytics.a

### ISSUE THREAD

**Issue by joshuapoq** [firebase/firebase-ios-sdk#6663]
### Feature status request

* ~Firebase~ Google Component: GoogleTagManager, GoogleAnalytics (libGoogleAnalytics.a)

I am raising this issue here with knowledge that this is not part of your team but that you are able to contact the Google team. We have not had a reply on [our ticket](https://support.google.com/tagmanager/thread/68379278) for over a month and there has never been any indication or any real support for these Google libraries on the Apple ecosystem.

We run a large-scale AppCommerce platform where a number of our clients pay for GA360 or use GTM. We would like to move away from all the pain caused by Carthage and Cocoapods to SwiftPackageManager. Apologies for raising this here but we are looking for any sort of acknowledgement or status for this issue from the Google team.

**Comment by morganchen12** [comment]
Hey, thanks for submitting this issue. In the past, for issues that are related to Tag Manager, we've been able to directly resolve them even though they're not part of Firebase because the Analytics team happens to jointly own the Tag Manager codebase (though this could change in the future). As far as I know we've also had exactly one Google Analytics issue that we resolved by submitting a bug fix to their codebase.

This issue is differs from the previous examples because it's a feature request with a significant scope, and even if I were able to get the Google Analytics team to respond to your ticket it's likely they do not have the bandwidth to add SPM support within the next year. Similarly, it's not something we can address by submitting a concise bug fix patch to their codebase. Instead of contacting them on your behalf, I think it would be more productive and on-topic to help you move off of the Google Analytics SDK to Firebase Analytics instead.

I'm not aware of any features Google Analytics' client SDK has that Firebase Analytics does not, and you can use Google Analytics console with Firebase Analytics data by [linking your Google Analytics account to Firebase](https://support.google.com/analytics/answer/9289234). Is there anything blocking you from moving off of Google Analytics?

**Comment by joshuapoq** [comment]
Thank you for such a quick and concise response!

With regards to GA I will check in with the team tomorrow, but I suspect the only blockers may be around knowledge sharing with those clients (I believe there are only a few clients that have not yet moved to Firebase).

However, many of our clients do actively use GTM, which has a dependency on GA, amongst a number of legacy libraries. I don't believe Firebase offers any replacement for GTM?

**Comment by morganchen12** [comment]
Tag Manager's hard dependency on Google Analytics means you're stuck. The only way to migrate to SPM from there would be to integrate Google Analytics and Tag Manager manually and do everything else through SPM, but that comes with its own caveats. 

I know it's not what you want to hear, but unfortunately there isn't a better solution for your use case. If you need help manually integrating TagManager + GoogleAnalytics, feel free to ask in this issue thread as well.

**Comment by chrispoq** [comment]
Just to leave a little feedback on this issue before closing it off(I'm a Product Manager at Josh's company), we have migrated our clients to Firebase whilst continuing to support GA for the clients we have that pay for 360. The issue here is that there is a big reluctance from clients to use Firebase for analytics. The console is really poor for retail clients. GA surfaces eCommerce data extremely well, including information on products, orders etc. Even understanding version adoption and devices statistics seems more difficult in Firebase. Firebase makes it really difficult to see your data in meaningful ways, the console needs a lot of improvement for retailers to want to use.

**Comment by morganchen12** [comment]
Hey Chris, have your users tried the [account linking](https://support.google.com/analytics/answer/9289234) I mentioned above? It will let you view your Firebase Analytics data in Google Analytics console.

**Comment by jsorge** [comment]
@morganchen12 Are you saying that if we make this link then apps don't need to install the Google Tag Manager SDK?

**Comment by morganchen12** [comment]
It depends on what you're using GoogleTagManager for. If you're deploying and managing tag containers and expect to see tags from FirebaseAnalytics-integrated apps, you will still need to use Tag Manager. Otherwise you're probably able to drop it without issue.

**Comment by jsorge** [comment]
I'm still unclear on how Tag Manager works overall, but I think my particular use case is using containers. That there are no installation instructions beyond "use Cocoapods" is super disappointing to me. Do you know of any manual-install directions to get the GTM SDK into an iOS app's codebase @morganchen12?

**Comment by morganchen12** [comment]
I do not. There is a binary TagManager SDK download on their website, but it has not been updated since 2016. You can try to grab the binary from the download url in the TagManager podspec and then manually integrate that instead. Note that if you do this you will need to also manually install GoogleAnalytics.

**Comment by jsorge** [comment]
Thanks @morganchen12. I notice that the Google Analytics library that's depended on by the GTM pod has the GTM symbols inside as well so I'm getting duplicate symbol errors. Is it safe to just not use the GTM binary and use the linked analytics one? (The analytics podspec is the one at https://github.com/CocoaPods/Specs/blob/9543734012238c33ea018af5a4381459c13f0916/Specs/3/2/c/GoogleAnalytics-iOS-SDK/3.12/GoogleAnalytics-iOS-SDK.podspec.json)

**Comment by morganchen12** [comment]
That's the wrong podspec. The correct podspec is this one: https://github.com/CocoaPods/Specs/blob/master/Specs/4/9/c/GoogleAnalytics/3.17.0/GoogleAnalytics.podspec.json

**Comment by paulb777** [comment]
Filed internal issue b/182790221

**Comment by davepaul0** [comment]
What's the recommended channel for putting pressure on GTM/GA teams to provide support?

**Comment by jamesyoon11** [comment]
Same as @joshuapoq's situation, we have to support the clients who pay GA360. They really get used to the universal GA property and don't want to move to "GA for Firebase" (GA4 App+Web) property. Whenever we have an issue regarding the legacy GA SDK, we contact our 360 reseller but they cannot help much by suggesting to switch to Firebase. Please ask the GA team to support the legacy SDK if it has an issue especially for security. (Ex. We have an security scanning issue (https://github.com/firebase/firebase-ios-sdk/issues/6217) but there is no fix).

**Comment by paulb777** [comment]
We've asked the GA team to add support and they've added it to their backlog. I'd encourage any paying GA360 customers to also request on their support channels.

In the meantime, a workaround could be to wrap the binary installed by CocoaPods into a local Swift Package.

**Comment by ThePragmaticArt** [comment]
@paulb777 noting that I'll likely have someone reach out on their support channels, has there been any known movement on this front. It's been quite some time and there's a bit of a cultural knowledge that the GA team doesn't necessarily iterate in much of a prioritized fashion for GA on iOS (which has to be a large customer base right?). It's just a bit confusing on how these products are so heavily used in mobile but don't receive the same TLC as say... Firebase. Especially in the mist of the ARM transitions happening right now.

**Comment by gscalzo** [comment]
Any news?

**Comment by dungi** [comment]
Are there any news on integrating google tag manager to SPM?

**Comment by Nonnus** [comment]
Same issue here, GTM and GA are my company single blockers for full SPM adoption and causing us to have an overly complicated workaround to be able to deal with it, is it that hard for management at google to understand how much you are impacting our work and prioritise some sort of solution for this problem?

**Comment by Nonnus** [comment]
No replies at all since April 7??? This is highly unprofessional and disrespectful towards paying customers and their associated developers, is there really no one that cares about this kind of behaviour in such a bit company?

**Comment by Nonnus** [comment]
No replies at all since April 7??? This is highly unprofessional and disrespectful towards paying customers and their associated developers, is there really no one that cares about this kind of behaviour in such a big company?

**Comment by ThePragmaticArt** [comment]
> No replies at all since April 7??? This is highly unprofessional and disrespectful towards paying customers and their associated developers, is there really no one that cares about this kind of behaviour in such a big company?

Our Google representative basically told us that GTM is deprecated on iOS and should be abandoned as a framework.

**Comment by Nonnus** [comment]
> Our Google representative basically told us that GTM is deprecated on iOS and should be abandoned as a framework.

I wish we could do the same on my company, sadly we still use gtm along with firebase...
Next year we will move to GA4 which should remove any need to use GTM library anymore but until then we are stuck with this problem

**Comment by tsunghung** [comment]
Please check [the GTM doc](https://developers.google.com/tag-platform/tag-manager/ios/v5#1_add_tag_manager_to_your_project), Google Tag Manager supports Swift Package Manager now. Please make sure to add `-ObjC` linker flag.

**Comment by ThePragmaticArt** [comment]
> Please check [the GTM doc](https://developers.google.com/tag-platform/tag-manager/ios/v5#1_add_tag_manager_to_your_project), Google Tag Manager supports Swift Package Manager now. Please make sure to add `-ObjC` linker flag.
> 
> 

Wait, so why was a Google representative telling us gtm was no longer supported?

**Comment by jmaffre** [comment]
I do agree that, beside SPM support, some clarification should be made on the product itself for iOS. Can we rely on GTM for the future?

**Comment by dungi** [comment]
Nice to see that GTM works with SPM. But after switching from the static framework to the SPM framework I can't find

TAGManager, TAGContainer or TAGContainerOpenerNotifier

anymore. I imported "GoogleTagManager" at the top of the file. Someone with same issue?

**Comment by tsunghung** [comment]
[GTM v3](https://developers.google.com/tag-manager/ios/v3) is deprecated, but [GTM v5](https://developers.google.com/tag-platform/tag-manager/ios/v5) is not deprecated.

TAGManager, TAGContainer, and TAGContainerOpenerNotifier are GTM v3 APIs. They are not GTM v5 APIs.
