### ISSUE TITLE
Buffer over flow 

### ISSUE THREAD

**Issue by Shakihassan** [firebase/firebase-ios-sdk#6820]
The function IsDirectory() in filesystem_posix.cc writes outside the bounds of st_qspare on line 133, which could corrupt data, cause the program to crash, or lead to the execution of malicious code.The program writes outside the bounds of allocated memory, which could corrupt data, crash the program, or lead to the execution of malicious code. 

The function FileSize() in filesystem_posix.cc writes outside the bounds of st_qspare on line 169, which could corrupt data, cause the program to crash, or lead to the execution of malicious code.The program writes outside the bounds of allocated memory, which could corrupt data, crash the program, or lead to the execution of malicious code.

Note : Issue is reported by vulnerability team (Fortify on demand)

**Comment by wilhuff** [comment]
`st_qspare` is not referenced in this code--it's a reserved field defined if you compile with the `_DARWIN_FEATURE_64_BIT_INODE` macro set. I strongly suspect your security scanning tool is misconfigured or otherwise misinterpreting this code. In any case, the `stat` API is used correctly in both cases.

Feel free to comment further if you have clarifications on this report.
