### ISSUE TITLE
How to check if FIRApp is alive and set up correctly?

### ISSUE THREAD

**Issue by lolgear** [firebase/firebase-ios-sdk#6856]
### Feature proposal

* Firebase Component: FIRApp/Crashlytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)

I would like to check app lifecycle via FIRApp ( FirebaseApp in Swift ) interface. Or it would nice to have the following information in README.md in repository.
For example, I have different settings files which are based on configuration. I would like to show information about Firebase app ( is it alive? ) to a beta-tester/user.

**Comment by ryanwilson** [comment]
Hi @lolgear - thanks for the request. You should be able to determine the state locally since `FirebaseApp.app()` is only configured if you call `FirebaseApp.configure()` (or one of the variants). If that's not feasible with your project structure, it's safe to do something with the default app like this:

```
if let app = FirebaseApp.app() {
  // Firebase is configured, use `app.options` to get access to options.
} else {
  // Firebase is not configured.
}
```

You'll see a warning printed to Xcode's console if Firebase is not configured ([found here](https://github.com/firebase/firebase-ios-sdk/blob/6a627007da0f2715a18575c913b512265c7271b5/FirebaseCore/Sources/FIRApp.m#L246-L255) but you can safely ignore that, it's exclusively for your own knowledge as a developer.

**Comment by lolgear** [comment]
@ryanwilson 
Could you add this information to README?
Thanks!

**Comment by ryanwilson** [comment]
Thank you for the suggestion, although I'm not sure that this belongs in the README. It's a pretty unique use case and the warning could be confusing - also this is entirely in the control of the developer calling `FirebaseApp.configure()` in order to configure an app. The recommendation is to call `FirebaseApp.configure()` as soon as possible in order to make sure things work as expected and early lifecycle events are caught.
