### ISSUE TITLE
CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer

### ISSUE THREAD

**Issue by jyounus** [firebase/firebase-ios-sdk#6893]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.0.1
  * Firebase SDK version: 7.0.0
  * Installation method: `CocoaPods`
  * Firebase Component: Core/Analytics/Google Tag Manager?

### [REQUIRED] Step 2: Describe the problem

We're seeing the following logs in our app, which we are unable to turn off or hide:
```
CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.
```

Our podfile has the following Google related pods:
```
pod 'Firebase', '7.0.0'
pod 'Firebase/Core'
pod 'Firebase/Crashlytics'
pod 'GoogleMaps', '3.10.0'
pod 'GoogleTagManager', '7.2.0'
pod 'GoogleIDFASupport', '3.14.0'
pod 'GoogleSignIn', '5.0.2'`
pod 'GoogleAnalytics', '3.17.0'
```

#### Steps to reproduce:
Create a new project with the above mentioned pods.

#### Relevant Code:
Call `Analytics.logEvent("", parameters: nil)`

Someone reported a similar problem in August, which was then marked as fixed/closed. https://github.com/firebase/firebase-ios-sdk/issues/6217

However, even after using the latest version of Firebase/Google Tag Manager, we're still seeing the issue. The above linked issue has an internal change number attached: https://github.com/firebase/firebase-ios-sdk/issues/6217#issuecomment-670665861

Could someone please check out the internal ticket and share if it was fixed? Ideally we'd like to stop seeing these issues in the logs.

**Comment by morganchen12** [comment]
This was fixed in https://github.com/firebase/firebase-ios-sdk/issues/6217, but unfortunately GoogleAnalytics has not made a new release containing the fix. If you're unable to wait for GoogleAnalytics to make a release, you'll have to migrate to FirebaseAnalytics or just ignore the warning produced by GoogleAnalytics.

Closing since this is no longer actionable by the Firebase team. We unfortunately do not have control over the GoogleAnalytics SDK release cycle. If you'd like help migrating to FirebaseAnalytics or have any further questions, feel free to continue commenting in this thread.
