### ISSUE TITLE
FR: Carthage support for GoogleTagManager and libGoogleAnalytics.a 

### ISSUE THREAD

**Issue by jesusmateos1234** [firebase/firebase-ios-sdk#6934]
We love if you add binary support for GoogleTagManager as you have already done for other frameworks.
This request is similar to SPM Feature request.

Thanks for all

**Comment by paulb777** [comment]
I'm going to close since GoogleTagManager is not part of Firebase and this isn't something that we're likely to add. 

Note that it continues to be possible to extract the binary from the [CocoaPods published podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/6/GoogleTagManager/7.2.0/GoogleTagManager.podspec.json#L35).
