### ISSUE TITLE
Trying to use the source pod integration

### ISSUE THREAD

**Issue by nico75005** [firebase/firebase-ios-sdk#702]
* Xcode version: 9.2 (9C40b)
  * Firebase SDK version: 4.8.1
  * Firebase Component: Firestore
  * Component version: 0.10.0

I am trying to use the source pod integration but once I do and try to compile I get an error.

So here are my pods:
```
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
```

Now I can see the sources that have replaced the binary framework.
But when I try to compile it, I get the following error:

```
MyProject/Pods/FirebaseFirestore/Firestore/core/src/firebase/firestore/util/comparison.h:32:10: 'absl/strings/string_view.h' file not found
```

**Comment by wilhuff** [comment]
We've been making a lot of changes in this area lately so it's possible this has been broken. Was this working previously or are you trying for the first time?

Meanwhile I'll look at reproducing this. Our own development runs in-repo which may mean that our HEADER_SEARCH_PATHS are broken.

**Comment by wilhuff** [comment]
The header paths weren't broken but we weren't properly including the abseil sources in the podspec.

This is a start on a PR to fix those:
https://github.com/firebase/firebase-ios-sdk/compare/wilhuff/podspec?expand=1

However, we're still stuck on this because it appears that the binary release doesn't include all the private headers required to make this work:

```
#import <FirebaseCore/FIRLogger.h>
```

However, if you change your Podfile to also include FirebaseCore from source this works.

```
  pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
  pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', branch: 'wilhuff/podspec'
```

I'll get the PR in so that you can pull Firestore without the branch and we'll have to look into how to change the release process so that the necessary private headers are included (if that's at all possible).

**Comment by wilhuff** [comment]
Okay, discussing internally, it's clear that the FirebaseCore we publish won't include these headers. If you want to use any components from source you'll need to get FirestoreCore from source too.

Once #704 lands you should be good to go.

**Comment by wilhuff** [comment]
Submitted. The podspec changes are now in master and you should be able to build from source.
