### ISSUE TITLE
FirestoreSwift Codable support for update

### ISSUE THREAD

**Issue by nidegen** [firebase/firebase-ios-sdk#7029]
### Feature proposal

* Firebase Component: Firestore

Currently, FirestoreSwift only supports `set` and `delete`, but no `update`. The reason is probably that the SDK would need to diff between the current document and the new Codable Object. And I am not sure if that is solvable.

One solution would be to have a generic way to find diffs in fields of a codable object. Or maybe there is a way to diff between NSDicts, but I have not figured out how.

Any other ideas how to implement that or reasons why it is not there?

**Comment by dconeybe** [comment]
Hi @nidegen. Thank you for the feature request! I'll bring this up with the team and reply back. Since it's the long weekend in the US, it may take a week or two to reply. In the meantime, I was wondering if specifying merge=true to [setData()](https://github.com/firebase/firebase-ios-sdk/blob/eb21690b803cbbad83a8ad2fa51d43fd1f3fa2b4/Firestore/Swift/Source/Codable/DocumentReference%2BWriteEncodable.swift#L56) would meet your use case?

**Comment by nidegen** [comment]
Yes, i am using that for now. The basic issue I have though is that I am not fully sure how the merging happens with persisted offline updates that are synced after a change happend on the server. Do you maybe know the details there? 

I.e. does a field that does not change in a merge locally overwirte a server change once it gets synced online? I would hope it should not, but don't now what if the diff is persisted after a merge or before a merge..

**Comment by dconeybe** [comment]
That's a good question. I'll look into it and reply, hopefully tomorrow.

**Comment by dconeybe** [comment]
@nidegen, Regarding your question in https://github.com/firebase/firebase-ios-sdk/issues/7029#issuecomment-734475697, here is how it works.

The merging of the document data specified to setData() with merge=true is done server-side. Therefore, when the device reconnects and goes back online then the entire document that was specified to setData() is sent to the server, which merges it into the existing document on the server.

> I.e. does a field that does not change in a merge locally overwirte a server change once it gets synced online?

Yes. Because the entire document data that was specified to setData() is sent to the server, it will overwrite any changes that occurred to those fields while the device was offline.

If you want to limit the impact of this behavior, you can specify `mergeFields` to setData() so that only certain fields are clobbered.

**Comment by nidegen** [comment]
Ok, that's what I was expecting. Thanks!

So `set()` with `mergeFields` is then equivalent to `update` with the same fields, or am I missing something?

**Comment by dconeybe** [comment]
Yes,  `set()` with `mergeFields=true` is equivalent to `update()` with the only difference being that `set()` will create the document if it does not exist whereas `update()` will fail if the document does not exist.

**Comment by nidegen** [comment]
Ok. It would still be nice to have an update function for Codables. As the entire document is getting passed when setting a Codable, it would need a separate parameter with `mergeFields`, similar to `set()`.

I will try to implement that and open a PR.

**Comment by nidegen** [comment]
@dconeybe I am not supposed to do API changes in a PR. Does that also apply to firestore swift?

**Comment by dconeybe** [comment]
You can still open a PR. But internally it will need to go through API Council review (a Google-internal process), which I will drive, and that will take a few weeks usually. Once approved, the PR can be merged. Having a PR as a "proof-of-concept" can be quite helpful, actually.

**Comment by nidegen** [comment]
As discussed in #7078 it won't be possible soon

**Comment by dconeybe** [comment]
To summarize, adding "update" support to FirestoreSwift is something that we would like to do in the future; however, we have no concrete plans at this point. The feature request is being tracked internally as b/174699780.
