### ISSUE TITLE
177468179: Parameters are removed from dynamic link after opening from browser in iOS platform

### ISSUE THREAD

**Issue by Shashank123sprive** [firebase/firebase-ios-sdk#7085]
Hi Team,

I'm using email verification strategy for login/register feature in my app, and the verification email contains a dynamic link(consist of destination screen, and verification token), which is used to navigate to a screen within the app installed in the user's phone.

Now the scenarios are , 

1. If a user simply clicks on the dynamic link from email, it opens the app, with no issue. In this case the links consistent and I can see following resolved dynamic link the app's listener code is : 

**https://links.sprive.com/sprive?screen=verification&verification_token=euasdasdZHDHH$qw132**

2. Whereas if the user copies and paste the dynamic link in browser(Safari) then the token & screen are lost from the that, as the dynamic link is not consistent. And I can see following resolved dynamic link in the app's listener code is : 

**https://links.sprive.com/sprive**

Would you please let me why the dynamic link is behaving in a different way when it is being copied-pasted on the browser.

Please help me to resolve this issue as soon as possible, because the register/login are the core features of my app and that  depends on the dynamic link only, we don't have a backup strategy at this point. And without workable dynamic link, my  app will be of no use.

Looking forward to get the resolution on this.

**Comment by Shashank123sprive** [comment]
Hi  @morganchen12 /Team, 

Any update on my query?

**Comment by morganchen12** [comment]
@eldhosembabu can you take a look?

**Comment by eldhosembabu** [comment]
Created internal bug : b/177468179. Will prioritize on this.

**Comment by eldhosembabu** [comment]
Can you please confirm the link that you have is short dynamic link and you are trying to append the params "screen" and "verification_token" afterwards? If thats the case, then when the link is pasted in browser, it will get redirected and the additional params that you have added will get lost since its not embeded in the Firebase Dynamic Link during its creation.

But in the case when you click on it, the universal linking kicks in and opens up the app and there you will get the whole link clicked.

So could you please try creating the Firebase Dynamic Link with these parameters embeded while creating the link rather than appending to an already created Dynamic link? Let me know if that works.
