### ISSUE TITLE
App store binary warning received due to use of private API transform: by GoogleTransport

### ISSUE THREAD

**Issue by arobertn** [firebase/firebase-ios-sdk#7177]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: ___12.2__
  * Firebase SDK version: __20201104 download, said to have GoogleTransport 8.0.0___
  * Installation method: Zip file from https://firebase.google.com/docs/ios/setup#frameworks
  * Firebase Component: __GoogleTransport (required for Analytics)___ 

#### Steps to reproduce:

1. Incorporate frameworks needed for Analytics to project as described in README.md in the zip.
2. Invoke the functionality by `#import "Firebase.h"` and  `[FIRApp configure]` in AppDelegate.m
3. Build the project for Generic iOS Device and submit to App Store from Xcode
4. Binary is accepted and can be used for TestFlight, but warning "app references non-public selectors in Payload: transform:" is popped up and stored in the upload load.
5. I have every expectation that this will result in rejection of the binary at app review stage, at which point I'll have no choice but to remove the Analytics functionality completely from my app.

#### Relevant Code:

The 'transform:' use is in the GoogleTransport framework which is said by the README to be required for Analytics functionality.

There is an earlier closed and uncommentable issue here:

https://github.com/firebase/firebase-ios-sdk/issues/5568

There it says this use of transform: is not just a chance reuse of the same name, but an actual call to Apple's private API, which is indeed wrong. The issue was closed saying Apple seemed to stop checking for this, however I can confirm that as of December 8, 2020, they had apparently started again. In any case this use is a violation of Apple's rules and should not be present in a public SDK intended for app developer use.

**Comment by arobertn** [comment]
OK thanks. Sorry I did not read the previous issue thoroughly. I'll appeal with this info if necessary. Still, given that this keeps coming up it might be a net time savings to rename the method as you suggest.

**Comment by paulb777** [comment]
Thanks @arobertn. Since this has recurred, I'll keep the issue open to see if we can do the rename in the next GDT major version update to avoid appeals in the future.

**Comment by androidparth90** [comment]
@ryanwilson : Is it possible to push a minor update to the FCM with this fix for this issue please. Since it would just involve a method change for 'transform', I am guessing it should be pretty straightforward.

A release with this minor update would help a lot since our App is currently being rejected by Apple stores due to this warning

**Comment by ryanwilson** [comment]
Thanks for the report @androidparth90 - and sorry for the troubles.

Unfortunately it has to be a major version change since we're breaking an existing public API (removing the `transform:` call), so there's a bit more work in migrating all usages of it, bumping the dependencies, and making sure nothing breaks in the process. This should be a bit simpler than when it was reported since we moved GDT to its own repo: https://github.com/google/GoogleDataTransport

That being said, I'll see if we can work on this shortly to stop this from happening. In the meantime it's worth appealing to Apple and pointing at the code (linked below) since this will take some coordination on our end.

https://github.com/google/GoogleDataTransport/blob/c654af7fa7a4b50df690ea9adc53f68e893c87ff/GoogleDataTransport/GDTCORLibrary/Public/GoogleDataTransport/GDTCOREventTransformer.h#L34

**Comment by androidparth90** [comment]
@ryanwilson : Well noted and thanks for your feedback.

**Comment by maksymmalyhin** [comment]
We still need to update SDKs like Firebase Performance to use the updates GDT version.
