### ISSUE TITLE
Is there any way for getting universal framework instead of xcframework

### ISSUE THREAD

**Issue by ukmunnithan** [firebase/firebase-ios-sdk#7189]
We are creating the Air native extension of Firebase analytics and we are using the SDK version 6.1 for the last 2 years.  When trying to upgrade the SDK we are facing some issues. We could not able to find the universal frameworks of FirebaseCore.xcframework
FirebaseCoreDiagnostics.xcframework
FirebaseInstallations.xcframework
GoogleDataTransport.xcframework
GoogleUtilities.xcframework
nanopb.xcframework
PromisesObjC.xcframework

We could not able to use the XCframeworks to create the native extension
Is there any way to get universal framework instead of xcframeworks

**Comment by ryanwilson** [comment]
Hi @ukmunnithan - it depends what you're looking for! XCFrameworks are required for a few things: Catalyst, and arm64 simulator support for Apple silicon Macs. Regular frameworks can only hold one architecture slice, which is why XCFrameworks were introduced.

If this is for your own use and you don't need to support Apple silicon or Catalyst, you should be able to write a relatively short script that can generate exactly what you're looking for. If you open up a `.xcframework` you'll see it's an `Info.plist` along with a few directories that contain regular `.framework`s. You could grab the architecture slices you need out of those binaries using the `lipo` command and assemble a `.framework` yourself.

That being said, based on the Catalyst and Apple silicon requirements, Air native extensions will eventually need to support XCFrameworks anyways so it's probably worth filing a feature request where appropriate on their end. I'll close this for now since there's no action for us but feel free to continue the discussion here. Thanks!

**Comment by ukmunnithan** [comment]
I have taken the framework inside the ios-arm64_armv7 then it was not a universal framework.
Could you please share the script for generating the universal framework. Please help

**Comment by paulb777** [comment]
@ukmunnithan One option to access the old style frameworks would be to use the [Carthage distribution](https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md).

**Comment by ukmunnithan** [comment]
@paulb777 Thank you.. I will check and send you an update
