### ISSUE TITLE
[CocoaPods] "signal SIGSEGV" error when compile

### ISSUE THREAD

**Issue by Blurzschyter** [firebase/firebase-ios-sdk#7206]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 6.34.0
  * Installation method: CocoaPods
  * Firebase Component: Core, Analytic

### [REQUIRED] Step 2: Describe the problem

Before doing the pod install for the firebase/analytic, i managed to compiled the code on real ios devices succesfully. However, after doing pod install on my project, i encountered this "signal SIGSEGV" error when trying to compiled it using the real ios devices. It never reach the starting of the project page.

<img width="1129" alt="Screenshot 2020-12-22 at 8 03 11 PM" src="https://user-images.githubusercontent.com/23515008/102887370-c7ebd400-4491-11eb-91eb-08c2d3756b4a.png">

Appreciate anyone that familiar with the issues to assist me on this.

#### Steps to reproduce:

1. You may clone the sample project from here : https://bitbucket.org/Blurzschyter/projectabc/src/master/
2. Uncomment the firebase pod line on podfile.
3. Run pod install
4. Make sure you compile it on real ios devices since my 3rd party library currently not support any ios simulator at the moment.
Thank you in advance ^_^

**Comment by paulb777** [comment]
@Blurzschyter Sorry about the trouble.  There is nothing about the crash that indicates Firebase is the problem since it looks to be in some other constructor.  It's not safe for us to run binaries on our devices, but the issue might be related to the several build problems like:

`ld: warning: direct access in function 'M3U8Parse::isMp3u8()' from file '/Users/p/Documents/projectabc/ProjectABC/EXTSDK/libs/libViewRightWebiOS.a(libViewRightWebiOS.a.bc.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/Users/p/Documents/projectabc/ProjectABC/EXTSDK/libs/libdmpbase.a(CDmpLicenseManager.dev.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

**Comment by Blurzschyter** [comment]
Thank you @paulb777 for your quick response.

Based on your reply, does it mean the library libViewRightWebiOS.a cause the issue for me to install firebase sdk inside my current project?

And can you share how you get this warning description ? i didn't see any warning description after hit the error.
`ld: warning: direct access in function 'M3U8Parse::isMp3u8()' from file '/Users/p/Documents/projectabc/ProjectABC/EXTSDK/libs/libViewRightWebiOS.a(libViewRightWebiOS.a.bc.o)' to global weak symbol 'std::__1::char_traits<char>::eq(char, char)' from file '/Users/p/Documents/projectabc/ProjectABC/EXTSDK/libs/libdmpbase.a(CDmpLicenseManager.dev.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

**Comment by paulb777** [comment]
@Blurzschyter I'm not sure what exactly causes the crash at load time, just that it doesn't look like a Firebase problem.  Here's a screenshot of the build log I see:

![Screen Shot 2020-12-22 at 4 58 47 PM](https://user-images.githubusercontent.com/73870/102947011-2e172d80-4477-11eb-8f0d-db43e2264522.png)
