### ISSUE TITLE
In-App Messaging Card view clipped when displayed on device

### ISSUE THREAD

**Issue by matthewdovey** [firebase/firebase-ios-sdk#7334]
**[REQUIRED] Step 1: Describe your environment**
Xcode Version: 12.2
Firebase SDK Version: 7.4.0
Installation method: CocoaPods
Firebase Component: IAM

**[REQUIRED] Step 2: Describe the problem**
The Card view that can be sent to a device using In-App Messaging seems to be coming through clipped on both real devices and simulators whilst testing. It can be seen on the device that the bottom corners are rounded but the top are not.

Reproduction Steps:
- Install Firebase In-App Messaging using CocoaPods
- Create campaign
- Test card on testing device
- Background app if currently foregrounded
- Foreground app
- Observe clipped card

<img width="330" alt="Screenshot 2021-01-20 at 23 20 54" src="https://user-images.githubusercontent.com/10790127/105252825-26ca6900-5b76-11eb-8890-bb5999bf4af4.png">
<img width="347" alt="Screenshot 2021-01-20 at 23 21 12" src="https://user-images.githubusercontent.com/10790127/105252859-30ec6780-5b76-11eb-9340-b6eb3b5719ce.png">

<img width="260" alt="Screenshot 2021-01-20 at 23 22 05" src="https://user-images.githubusercontent.com/10790127/105252915-511c2680-5b76-11eb-8ac4-b312c7fc0db6.png">

![0E5B3571-55A5-45DB-8D15-FFD051C9556C](https://user-images.githubusercontent.com/10790127/105253038-950f2b80-5b76-11eb-9ebd-e3563edbfada.jpeg)

**Comment by christibbs** [comment]
@matthewdovey thanks for the report. I sent #7399 out for review to fix the rounded corners.

The clipping of the owl image is expected though. In portrait mode, the image view fills itself with the image while retaining the image's aspect ratio (3:2). In landscape mode, the image view flips to a 1:1 aspect ratio and appears to the left of the other content. That's why you won't see the owl clipped in your message in landscape mode.

You can use two different images with different aspect ratios for portrait and landscape to avoid any clipping.
