### ISSUE TITLE
Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by OccultSlolem** [firebase/firebase-ios-sdk#7615]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.7.0
  * Installation method: `CocoaPods`
  * Firebase Component: Firestore 

#### Steps to reproduce:

Open app
Wait for error message to appear in debugger

#### Relevant Code:

```swift
final class CandidateData: ObservableObject {
    @Published var candidates: [Candidate] = fetchCandidateData()
}

func fetchCandidateData() -> [Candidate] {
    let db = Firestore.firestore()
    var candidates: [Candidate]?
    let semaphore = DispatchSemaphore(value: 0)
    
    db.collection("candidate-profiles").addSnapshotListener() { querySnapshot, err in
        defer { semaphore.signal() }
        if let err = err {
            print("Failed to get candidates: \n \(err)")
        } else {
            guard let documents = querySnapshot?.documents else {
                print("Failed to get candidates: \n No documents")
                return
            }
            
            candidates = documents.map{ queryDocumentSnapshot -> Candidate in
                let data = queryDocumentSnapshot.data()
                var name = "",age = "",occupation = "",affiliation = "",bio = "",logo = "" // Stats
                var questions = ["":""]
                var images = [""]
                var blurb = [""]
                
                if let statData = data["stats"] as? [String: Any] {
                    name = statData["name"] as? String ?? ""
                    age = statData["age"] as? String ?? ""
                    occupation = statData["occupation"] as? String ?? ""
                    affiliation = statData["affiliation"] as? String ?? ""
                    bio = statData["bio"] as? String ?? ""
                    logo = statData["campaign-logo-url"] as? String ?? ""
                }
                
                if let questionData = data["questions"] as? [String:Any] {
                    questions = questionData as? [String:String] ?? ["":""]
                }
                
                if let imageData = data["images"] as? [String] {
                    images = imageData
                }
                
                if let blurbData = data["blurb"] as? [String] {
                    blurb = blurbData
                }
                
                return Candidate(id: queryDocumentSnapshot.documentID, name: name, age:  Int(age)!, logo: logo, blurb: blurb, images: images, occupation: occupation, affiliation: affiliation, bio: bio, questions: questions)
            }
        }
    }
    
    semaphore.wait()
    
    return candidates!
}

```

Leads to the error:

```
2021-02-25 22:24:32.209251-0800 Politifi[2812:790636] 7.3.0 - [Firebase/Firestore][I-FST000001] Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
 This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```
I'm able to make reads and writes on Safari on the iPhone 8 Plus running iOS 14.4 using the Firebase Console, so connectivity is not the issue. For posterity I tried both WiFi and 4G LTE, but there was no difference made.

**Comment by ryanwilson** [comment]
Hey @OccultSlolem - sorry for the troubles you're seeing. Quick question before the Firestore folks jump in - is this by any chance in an App Clip running on device? We've seen similar issues before (#6211) and thought I'd check before the Firestore team gets to this.

**Comment by dconeybe** [comment]
Hi @OccultSlolem. I'm from the Firestore team and I'll work with you on this issue. Based on the code you provided in the OP I don't see anything that you're doing incorrectly. The error message that you're seeing is, obviously, indicating that Firestore is unable to communicate with the back end. So the question now is *why*.

To being investigation, could you provide the following:
1. Capture full debug logs, by calling `Firestore.enableLogging(true)`, reproducing the issue, and capturing and posting the entire log output in an attachment or a [gist](https://gist.github.com/).
2. Try to reproduce the issue with the Quickstart app: https://github.com/firebase/quickstart-ios/tree/master/firestore
3. Respond to the question posed by @ryanwilson about App Clip.

Hopefully we can get to the bottom of this issue that you're experiencing.

**Comment by OccultSlolem** [comment]
@ryanwilson This is not in app clip, nor does this app use the app clip functionality at all.

@dconeybe 

1.) Debug output can be found here: https://gist.github.com/OccultSlolem/0ced26ae76309fd8ae3fb884d0bbbb95
2.) I was able to reproduce this bug in the Quickstart app. Log for this can be found here: https://gist.github.com/OccultSlolem/4950fad7894bcf6760ba40f6d8142bf4

My implementation for quickstart looked like so. Note that my app uses pure SwiftUI and not UIKit, so this was the best I could do to get it to happen in a relatively similar way:

```swift
// In ResetaurantsTableViewController.swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    self.setNeedsStatusBarAppearanceUpdate()
    print(fetchCandidateData())
    observeQuery()
  }
```

**Comment by OccultSlolem** [comment]
I'm still facing this issue. I have tried simulating this exact operation in the rules playground, and it does allow it to go through. I also tried importing ``FirebaseFirestoreSwift`` and updated the fetchCandidateData() func to look like the following:

```swift
func fetchCandidateData() -> [Candidate] {
    let db = Firestore.firestore()
    var candidates: [Candidate]?
    let semaphore = DispatchSemaphore(value: 0)
    Firestore.enableLogging(true)
    
    db.collection("candidate-profiles").addSnapshotListener() { querySnapshot, err in
        defer { semaphore.signal() }
        if let err = err {
            print("Failed to get candidates: \n \(err)")
        } else {
            guard let documents = querySnapshot?.documents else {
                print("Failed to get candidates: \n No documents")
                return
            }
            
            candidates = documents.compactMap { document in
                try? document.data(as: Candidate.self)
            }
        }
    }
    
    semaphore.wait()
    return candidates!
}
```
Same result, though

**Comment by dconeybe** [comment]
@OccultSlolem Thank you for the additional logs and information. I'm not seeing anything particularly telling in the logs or code that you provided.

For posterity, could you move the call to `Firestore.enableLogging(true)` to *before* the call to `Firestore.firestore()` (instead of *after*)? I want to make sure that any debug logs produced by the call to `firestore()` itself get captured.

There must be something with your specific environment that is causing issues. One idea that my teammate had was to set the `GRPC_VERBOSITY` environment variable to `DEBUG` (as documented here: https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) to get more information on the network error; however, I tried setting it and didn't see any additional output. I'm going to keep looking into this tomorrow but I thought I'd post this comment in case you have some curiosity to try to get the debug GRPC logs and post them.

**Comment by dconeybe** [comment]
@OccultSlolem Can you set *both* of the following environment variables in Xcode, reproduce the bug, and post the logs:

- GRPC_VERBOSITY=DEBUG
- GRPC_TRACE=all

To do this, go to "Edit Scheme" -> Run and click the "+" button under the "environment variables" section (see screenshot below).

The resulting logs may provide greater detail into why the "Could not reach Cloud Firestore backend" error is occurring in your environment.

![GrpcDebugEnvVarsScreenshot](https://user-images.githubusercontent.com/61283819/109835885-9f125880-7c11-11eb-91cd-f3717cb6284f.png)

**Comment by OccultSlolem** [comment]
I set the variables and moved the ``Firestore.enableLogging(true)`` call to before I call ``var db = Firestore.firestore()`` but there didn't seem to be many changes in the output. The output can be found here: https://gist.github.com/OccultSlolem/7078231d477c2d5f133b74b3e029db38

A couple notes about the way this works

- The db rules should allow this transaction to occur, but for posterity I set it to allow all read operations
- This happens on app startup (it doesn't allow the app to progress past the startup screen, actually, even if I remove the semaphore)
- My app uses pure SwiftUI (ie there is no AppDelegate class. I do however inject a UIApplicationDelegate in App.swift to call ``FirebaseApp.configure()``)
- There isn't any code in the app that specifically calls for ``fetchCandidateData()`` to happen, rather it simply executes because it is an ObservableObject that needs to be initialized

**Comment by OccultSlolem** [comment]
Technically, ``fetchCandidateData()`` is called here:
```swift
@main
struct PolitifiApp: App {
    @StateObject private var candidateData = CandidateData() // <- When this StateObject is initialized

    var body: some Scene {
        ...
    }
    ...
    }
}

```

**Comment by dconeybe** [comment]
Hmm that's surprising that there was no additional logging produced when the `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=all` environment variables were set. Can you confirm that you're using a "debug" build of your app; that is, "Build Configuration" is set to "Debug"? These GRPC_ environment variables have no effect in release builds.
![DebugBuildConfigScreenshot](https://user-images.githubusercontent.com/61283819/110009252-c1c47000-7cea-11eb-80a0-81e6a332823c.png)

Since you were able to reproduce the bug in the quickstart app, I don't think that your application's structure (e.g. the fact that it uses pure SwiftUI) is a factor.

**Comment by OccultSlolem** [comment]
Tried it again, got some more output this time: https://gist.github.com/OccultSlolem/aa46eed31c400c6da7aba9a3f0bcd08f

Don't think it quite saved when I did it the first time :/

**Comment by dconeybe** [comment]
Sadly, those logs are surprisingly absent of useful hints. I'm assuming that you captured those logs with your app... could you also capture them with the quickstart app (you mentioned that you were able to reproduce with the quickstart app) with `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=all` set? Those logs will be more directly comparable to logs that I've been capturing with the quickstart app. If I can find a divergence then that will at least provide a starting point for investigation.

**Comment by OccultSlolem** [comment]
Yep, got the gist here: https://gist.github.com/OccultSlolem/e7e4db7176ae9ea9bcd75caa0af8d889

Weirdly, peeking at network activity on the debugger in my app shows zero activity, even though my device is very much connected to the internet and is able to communicate on other apps. The quickstart only does a tiny amount of communication (4.4 Kb in), which may be for other things the quickstart does, not sure. But on my app, there seems to be no communication before Firestore times out.

**Comment by OccultSlolem** [comment]
OK, looking through the profiler shows us that there seems to be very little network activity taking place. Around when the app first starts up, it communicates 349 bytes to an IPV6 address somewhere and takes in 444 bytes, of which only 264 are marked as going out over wifi (the rest being marked as going through an ethernet adapter, weirdly enough). Whether this is actually related to the issue at hand or something completely irrelevant, there seems to be little or no communication to Firestore before it times out. FWIW, I can access the web and do other things through this device, and when I disable this code, auth and other APIs work perfectly fine on this app.

(This profiler session was all on my app btw)
![Screen Shot 2021-03-04 at 11 46 41 PM](https://user-images.githubusercontent.com/10332740/110083693-e00a8a00-7d43-11eb-8b65-f0f0d65e4e49.png)

**Comment by dconeybe** [comment]
@OccultSlolem Can you re-capture the logs from the quickstart app with the environment variables `GRPC_VERBOSITY=DEBUG` and `GRPC_TRACE=all` set? It looks like the logs you posted 2 comments above do not have the grpc logging enabled.

That's very interesting about the network profiler. I'm not sure what to make of the lack of network communication. It may indicate that there is a deadlock or something in Firestore's code.

You mentioned that "when I disable this code, auth and other APIs work perfectly fine on this app"... which "code" are you referring to? What do you observe on the device when you launch the quickstart app? Are you able to log in? Could you post a video/screenshot of what the quickstart app looks like when you experience this issue? This will help isolate where things might be going wrong. Thanks!

**Comment by OccultSlolem** [comment]
Those logs did have grpc logging enabled and the build config set to debug.

I have an older version of my app which pulls the data from a json file in the app for debug purposes. When I use that version of the code, I don't get this behavior. I'm even able to use other APIs from Firebase and other third party APIs.

I took this video of the quickstart app behavior. The associated log can be found here: https://gist.github.com/OccultSlolem/cea9190930bbe8af8499e657b31e4b3c


https://user-images.githubusercontent.com/10332740/110155800-00b1fe80-7d9b-11eb-89b4-b5cc07c15f95.mp4

**Comment by OccultSlolem** [comment]
I accidentally had GRPC_TRACE set to ALL with allcaps, my bad! 😓 

I have an older version of the code on my app that pulls the info from a JSON file on the device for testing purposes (ie doesn't make a call to Firestore). That version of the app works as expected, and does calls to auth and other Firebase and third party APIs just fine.

I took the following video of the quickstart app, the associated log can be found here: https://gist.github.com/OccultSlolem/5198be0c62b4d366d2e68f147622d523

https://user-images.githubusercontent.com/10332740/110156479-dd3b8380-7d9b-11eb-8458-d729d2c18083.mp4

**Comment by dconeybe** [comment]
Ahh those logs looks better! It still doesn't point to a particular problem but it's suspicious that the grpc logs just stop at some point. It's as if Firestore isn't even attempting to create any outbound network connection after initializing grpc. For comparison, here is what the logs look like when I run the quickstart app on my computer: https://gist.github.com/dconeybe/5b341cd3b6b06b9938ab351a2f08b832. As you can see, there is a large volume of grpc logging produced that is notably absent from your logs.

The video you posted was helpful too, even just to give more context about what you're observing and how the problem is manifesting.

Next, I'd like to check out what the threads are doing both *before* the 10-second timeout and *after* it. Could you do the following:

1. Launch the FriendlyEats app.
2. Wait for the `TIMER CHECK BEGIN` logs to begin.
3. Press the "pause" button in Xcode to pause the application and enter the debugger.
4. Run the following command in the lldb debug console: `thread backtrace all`
5. Capture the thread dump and post it in a gist.
6. Resume the application.
7. Wait for the `Could not reach Cloud Firestore backend` error to occur.
8. Pause the debugger again, run `thread backtrace all`, capture the output, and post it in a gist.

It could be telling to see if one of Firestore's threads is stuck somewhere.

**Comment by OccultSlolem** [comment]
Alrighty, here's the backtrace from prior to the Firestore timeout: https://gist.github.com/OccultSlolem/052132f8810ddfde26d438fa2e6b5582

And the backtrace from after it times out: https://gist.github.com/OccultSlolem/3ff0bcf1eef38ca8896cdb17bbcc1d86

And here's the full log: https://gist.github.com/OccultSlolem/db7a9118ce1a5921ac00abb381bcff3c

**Comment by dconeybe** [comment]
Something that stands out right away from those thread backtraces is that `semaphore.wait()` is being called on the main thread. The main thread should never be blocked like this because it effectively "freezes" the entire application. Can you remove the call to `semaphore.wait()` and see what happens? It's *possible* that the `Could not reach Cloud Firestore backend` error is because some work is being scheduled on the main thread and the main thread is blocked, causing deadlock and leading to the timeout.

**Comment by dconeybe** [comment]
Update: I've confirmed that blocking the main thread is the root cause of this issue. Removing the call to `semaphore.wait()` (and tweaking the code so that it compiles) fixes the `Could not reach Cloud Firestore backend` error. I'll look into improving the error message to report this scenario more clearly, but you will need to find a non-blocking way to "wait" for the results to come back from Firestore.

**Comment by OccultSlolem** [comment]
Man, I feel like a dunce. Removing that fixed everything. Thanks for all your help! 🥳 🥳

**Comment by dconeybe** [comment]
Fantastic! I love it when fixes are that easy. Thanks for your help as well during the investigation. All the best with your app.
