### ISSUE TITLE
FR: Kids category app rejection "-[APMIdentity retrieveAdTrackingConsentStatus]"

### ISSUE THREAD

**Issue by AlexNay-iOS** [firebase/firebase-ios-sdk#7695]
We've updated Firebase 7.8.0 but got the rejection again.
Apple said they detected the "-[APMIdentity retrieveAdTrackingConsentStatus]" which can be a part of Tracking Transparency framework, which is used when apps collect data about users and share it with third-parties for tracking purposes.

```
  - FirebaseAnalytics (7.8.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
```

We noticed that the it could be inside the GoogleAppMeasurement:

```
`grep -ir retrieveAdTrackingConsentStatus .`
`Binary file ./Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_i386_x86_64-simulator/GoogleAppMeasurement.framework/GoogleAppMeasurement matches`
`Binary file ./Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.framework/GoogleAppMeasurement matches`
```

**_Do you have any solution fo this situation?_** 🙏

Related message: https://github.com/firebase/firebase-ios-sdk/issues/7652#issuecomment-793140578

**Comment by haydarKarkin** [comment]
Is there any progress about this issue? We got rejection too for the same reason after we've updated Firebase 7.8.0.

**Comment by ryanwilson** [comment]
Hey folks, sincere apologies for the trouble you're seeing here. I'll escalate this immediately and we'll report back ASAP. Note that a lot of the folks involved are in California so it'll be a couple of hours before they're up and online, but this is a top priority for us to unblock everyone.

**Comment by Seleznov** [comment]
Hi there. @ryanwilson thank you for _priority 0_ reaction on this.

Writing here just to pay more attantion on this problem but from Unity SDK side - we are in trouble there too.

**Comment by ryanwilson** [comment]
Hi everyone,

We just release Firebase 7.8.1 on CocoaPods and Swift Package Manager and this hopefully fixes the issue. Please update and let us know if you face the rejection again and we'll re-open this bug. Thanks for your patience!

**Comment by Seleznov** [comment]
Hi! Does anyone tried to validate an app in Apple with the latest 7.8.1 pod? 
@AlexNay-iOS, @haydarKarkin

**Comment by thienphuoc** [comment]
we also got rejection from Apple, please see here https://github.com/firebase/quickstart-unity/issues/989

**Comment by haydarKarkin** [comment]
Hi @Seleznov , we got rejection again with Firebase Analytics 7.8.1 and now I don't know which 'grep' command that should I search for in the source code?

**Comment by AlexNay-iOS** [comment]
Hello, @haydarKarkin , you can directly ask Apple what part of code seems wrong for them. Please let us know their response if it possible. We've not tried the 7.8.1 version, just temporarily switched off the Firebase services till situation will be solved.

**Comment by haydarKarkin** [comment]
Hello @AlexNay-iOS , I've asked them many times but they've responded me same answer:

----------------------------------------------------------------------------------------
Guideline 1.3 - Safety - Kids Category

We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. Specifically:

- Your app implements the App Tracking Transparency framework, which is used when apps collect data about users and share it with third-parties for tracking purposes. Since Kids Category apps are not allowed to collect, transmit or share identifiable information with third-parties, you should not implement App Tracking Transparency in your app.

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.

Resources
Learn more about our policies for Kids Category apps in App Store Review Guideline 1.3.
----------------------------------------------------------------------------------------

We had to remove Firebase Analytics because of that, and we finally released our app. I have been trying several grep commands for finding this issue but there is no process for now.
