### ISSUE TITLE
Why Carthage FirebaseAnalytics only is stopped at v7.4.0 ?

### ISSUE THREAD

**Issue by koichi5115** [firebase/firebase-ios-sdk#7698]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4
  * Firebase SDK version: 7.8.0
  * Installation method: Carthage
  * Carthage version: 0.37.0

### [REQUIRED] Step 2: Describe the problem
https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md
As above mentioned, Firebase Carthage distribution may be discontinued, but FirebaseFirestore and other components is still updated. (Today, I noticed can use v7.8.0 components at Carthage distribution.)

But only FirebaseAnalytics is still stopped at v7.4.0.

Will FirebaseAnalyticsBinary be update in the future?
Otherwise, should we stop use Firebase SDK by Carthage distribution?

Bellow is my project Cartfile.resolved and Xcode console result.

<img width="705" alt="スクリーンショット 2021-03-12 3 23 23" src="https://user-images.githubusercontent.com/58302938/110835819-a3f69c80-82e2-11eb-9aba-9df2a545346f.png">

<img width="1182" alt="スクリーンショット 2021-03-12 3 24 27" src="https://user-images.githubusercontent.com/58302938/110835782-98a37100-82e2-11eb-84f1-6a1fc369d473.png">

**Comment by paulb777** [comment]
@koichi5115 Sorry about the trouble. We haven't updated Analytics in the Carthage distribution since 7.4.0 because Analytics switched to a distributing its binary via xcframeworks and Carthage does not yet support xcframeworks. The implementations is in progress at https://github.com/Carthage/Carthage/pull/3123

In the meantime, a workaround is to integrate Analytics from the [zip distribution](https://github.com/firebase/firebase-ios-sdk/releases/tag/7.8.1)

**Comment by paulb777** [comment]
I'm going to close, since this can be tracked and will be solved along with #7039

**Comment by icedice** [comment]
Thank you for explaining. I will stick with 7.4.0 until Carthage 0.38.0 is out which seems to be very soon.
