### ISSUE TITLE
[Bug] Unable to receive scheduled Cloud Messaging for iOS devices 

### ISSUE THREAD

**Issue by adityathoutam** [firebase/firebase-ios-sdk#7706]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.6f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: Cloud Messaging 
  * Other Firebase Components in use: Auth, Storage, Database 
  * Additional SDKs you are using: AppsFlyer, Revenuecat 
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: iOS/Android 
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
iOS users are getting notifications if I use their device token and send a notification, but when I use the console dashboard to target iOS users, iOS users are not receiving push notifications. What am I missing?

**Comment by morganchen12** [comment]
Scheduled notifications rely on silent notifications, which may be throttled by the OS. You can get more reliable scheduled notifications by scheduling them on your backend (for example via [appengine cron](https://cloud.google.com/appengine/docs/flexible/nodejs/scheduling-jobs-with-cron-yaml)) and sending display notifications instead of silent notifications.

**Comment by rizafran** [comment]
It looks like the bug for this has been fixed. I'll be closing this ticket for now, but feel free to reopen if you still encounter the issue in order to investigate further. Thanks.
