### ISSUE TITLE
Firebase Auth: integration tests failures

### ISSUE THREAD

**Issue by maksymmalyhin** [firebase/firebase-ios-sdk#7718]
Nightly integration tests failures:
- [most recent run](https://github.com/firebase/firebase-ios-sdk/runs/2113104827?check_suite_focus=true) 
- [report](https://github.com/firebase/firebase-ios-sdk/issues/7644#issuecomment-799407594)

**Comment by paulb777** [comment]
It seems that the project being used for the credentials in g3 `gcp-ios-test` is now labeled `Nodejs AdminSDK Testing 04k9a1`. Perhaps we should have a dedicated Firebase project for the Auth integration tests? cc: @granluo

**Comment by paulb777** [comment]
First broken on March 12 and failed each night since.

**Comment by rosalyntan** [comment]
I believe the issue was that the `deleteCurrentUser` call at https://github.com/firebase/firebase-ios-sdk/blob/1f2f5f617e6b964b8377d9f2dddf1d5225e9efe2/FirebaseAuth/Tests/Sample/ApiTests/EmailPasswordAuthTests.m#L63 must have failed in a previous test run, causing the next `createUserWithEmail` invocations for that email to fail since the user already existed. I've deleted the user from the `gcip-ios-test` project, and so the test should pass now.

**Comment by rosalyntan** [comment]
Triggered a re-run.

**Comment by granluo** [comment]
> It seems that the project being used for the credentials in g3 `gcp-ios-test` is now labeled `Nodejs AdminSDK Testing 04k9a1`. Perhaps we should have a dedicated Firebase project for the Auth integration tests? cc: @granluo

For the project, maybe we could use the quickstart testapp?

**Comment by rosalyntan** [comment]
Latest integration test run passed: https://github.com/firebase/firebase-ios-sdk/actions/runs/652811465
