### ISSUE TITLE
When will analytics support MacOS?

### ISSUE THREAD

**Issue by HeebeLee** [firebase/firebase-ios-sdk#7898]
According to the 2020 roadmap, analytics will support more apple platforms. (https://github.com/firebase/firebase-ios-sdk/blob/master/ROADMAP.md#getting-started)

Now it's April 2021. Among the support platforms I see officially, there is no one except IOS. It's a very important thing for a lot of people. I have been waiting for a full year since I saw the road map. 

What's the latest news?

**Comment by paulb777** [comment]
@HeebeLee Sorry about the confusion, but the specific reference to Analytics was in the Quickstarts section to describe that we plan to modernize other Firebase Quickstarts, like we did for [Analytics in 2020](https://github.com/firebase/quickstart-ios/tree/master/analytics).

Nonetheless, there has been progress in Analytics and a EAP was made available for Catalyst support. Otherwise, I can't comment specifically about future plans.  The ROADMAP link is specifically to talk about aspirational goals that we'd like to achieve in conjunction with the open source community and progress is tracked in this repo.  And currently Analytics is out of scope for the open source part of Firebase.

I'm going to close in favor of the existing #1732, but feel free to continue this specific discussion here.
