### ISSUE TITLE
Provide a global killswitch on FIRApp

### ISSUE THREAD

**Issue by shamilovtim** [firebase/firebase-ios-sdk#8095]
Problem: Firebase only provides an enable method (e.g. `configure`) but does not provide a disable method. This is a problem because some peer dependencies enable Firebase and Firebase child pods without the user's consent. For instance, a pod like `Segment-Firebase` could enable Firebase Analytics, but the user might want that off under certain build configurations. With all of the network swizzling Firebase does, it frequently finds itself incompatible with other pods. Having a killswitch would be extremely useful for both debugging and for build configs for disabling it and blocking peer dependencies from enabling it.

Solution: Provide a global killswitch such as `[FIRApp disable]`

**Comment by morganchen12** [comment]
While Firebase doesn't provide a unified disable button, there are more granular controls for individual things in your feature request scattered about various locations. For example:

- Swizzling can be disabled via adding `FirebaseAppDelegateProxyEnabled` to your Info.plist file and setting its value to `NO`.
- Conditionally excluding Analytics would have to be done manually and could potentially be a lot of work, but is achievable [via CocoaPods](https://stackoverflow.com/a/26074997/4158089) at the build phase rather than at runtime.

Is there a particular use case you had in mind?

**Comment by shamilovtim** [comment]
Yeah what surfaced this is that numerous people are having compatibility issues with Detox that the Detox team seems unable to fix: https://github.com/wix/Detox/issues/2706. A search of past issues revealed that several packages have experienced compatibility issues from time to time issues related to Firebase swizzling, including Kotlin Native and Detox having this bug re-appear multiple times. I attempted to put `[FIRApp configure]` behind an env var, no luck. Then I put shutting off FIRPerformance behind env vars:
```obj-c
[FIRPerformance sharedInstance].instrumentationEnabled = NO; 
[FIRPerformance sharedInstance].dataCollectionEnabled = NO;
```

Still I'm seeing network calls to firebaseinstallations.googleapis.com. I'm not seeing any way of really stopping Firebase from putting out network requests. Which prompted me to make this post asking for a global, unified killswitch. We really just need to be able to shut off Firebase during our test running but there seems to be no clear and easy way to do it. It's not as simple as not installing the Pod(s) because this would throw runtime errors all over the place in our javascript if we simply exclude the dependency from our project. We'd like the dependency to exist, but in a disabled state.

**Comment by shamilovtim** [comment]
> Swizzling can be disabled via adding FirebaseAppDelegateProxyEnabled to your Info.plist file and setting its value to NO.

Could you clarify what the ramifications of disabling swizzling are? Could we disable swizzling at runtime?

**Comment by maksymmalyhin** [comment]
In general a Firebase instance can be de-initialized with the [-[FIRApp deleteApp:]](https://firebase.google.com/docs/reference/ios/firebasecore/api/reference/Classes/FIRApp?authuser=0#-deleteapp:) method. Is it what you are looking for? 

[[FIRPerformance sharedInstance].instrumentationEnabled = NO;](https://firebase.google.com/docs/reference/ios/firebaseperformance/api/reference/Classes/FIRPerformance?authuser=0#instrumentationenabled) will disable swizzling of the instances implementing `NSURLSessionDelegate` protocol. 

Also you can disable `UIApplicationDelegate` swizzling with the `FirebaseAppDelegateProxyEnabled` flag.

Please let us know if the provided API doesn't cover your case or you have more questions.

**Comment by shamilovtim** [comment]
Hey @maksymmalyhin @morganchen12 if you have time to see what I was referring to, please see the following: https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/71

This is an example of a peer dependency calling `[FIRApp configure]` without our consent and is part of reason why we requested a killswitch. Even though we put our own `[FIRApp configure]` behind an env var, this plugin went on to call it without our authorization. I will go ahead and see if `deleteApp` could help resolve the issue.

**Comment by shamilovtim** [comment]
deleteApp doesn't resolve the issue. it still allows a peer dependency (or any other, future code) to call `[FIRApp configure]`

**Comment by morganchen12** [comment]
Thanks for the context. The crash you mentioned should be resolved by the `FirebaseAppDelegateProxyEnabled` plist value, since that disables app delegate swizzling universally. The effects of disabled app delegate swizzling are documented per-products in our docs (for example [here](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_messages_with_method_swizzling_disabled). Disabling swizzling cannot be deferred since it must run before the class is used.

As for the second issue, other SDKs that wrap Firebase should ideally not be configuring the SDK on the app's behalf. Firebase internally has mechanisms for making sure things that depend on `FIRApp` can wait until `FIRApp` is initialized by the app before taking action, but since Segment cannot publicly depend on these mechanisms, it's probably sufficient for them to simply ask the app developer to initialize the Segment integration immediately after initializing Firebase.

In the meantime, you can create a separate build configuration and then use CocoaPods to exclude the Firebase (and Firebase integration) pods from it entirely.

**Comment by paulb777** [comment]
Closing since there are workarounds and no plans to implement such a feature.
