### ISSUE TITLE
Firebase/AnalyticsWithoutAdIdSupport subspec still points to `'FirebaseAnalytics/WithoutAdIdSupport', '~> 8.0.0'`, not 8.1.0

### ISSUE THREAD

**Issue by Westacular** [firebase/firebase-ios-sdk#8179]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.1.0
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Core (Auth, Core, Database, Firestore, Messaging, Storage, etc)

#### Steps to reproduce:

1. Depend on `pod 'Firebase/AnalyticsWithoutAdIdSupport', '~> 8.1.0'` in your Podfile
2. Run `pod update`
3. Inspect Podfile.lock or run `pod outdated`, and notice that `FirebaseAnalytics/WithoutAdIdSupport (8.0.0)` was installed, even though v8.1.0 of `FirebaseAnalytics` is available.

It appears that in the most recent version bump PR (#8152), the `AnalyticsWithoutAdIdSupport` subspec in `Firebase.podspec` was missed, and it still points to v8.0.0 instead of 8.1.0:

https://github.com/firebase/firebase-ios-sdk/blob/acf106a33d50e893f85a8563a19557b3df6110d1/Firebase.podspec#L72

I'm guessing that this is probably because it's a new subspec and the corresponding version bump tooling needs to be updated?

**Comment by maksymmalyhin** [comment]
@Westacular Thank you for reporting it! Yes, the version of `FirebaseAnalytics/WithoutAdIdSupport` was not updated properly in the Firebase umbrella podspec. In this specific release it should not be an issue because Firebase Analytics didn't have any changes this release so both Firebase Analytics versions 8.0.0 and 8.1.0 are actually pointing to the same binary.

We will make sure that the Analytics versions will be updated properly next release.

**Comment by paulb777** [comment]
Assigning to @ncooke3 to fix the release tooling in advance of 8.2.0.

**Comment by Westacular** [comment]
Ah, good to know. Thanks for the quick response!
