### ISSUE TITLE
Link FirebaseCrashlytics(x86_64) error

### ISSUE THREAD

**Issue by Vanson** [firebase/firebase-ios-sdk#8183]
### Development Environment Information

Xcode Version 12.5 (12E262) on macOS Big Sur 11.4 (20F71)
Cocoapods 1.10.1

  - Firebase/Crashlytics (8.1.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 8.1.0)

Action:Build and Run for Simulator

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FIRCLSApplication.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Archive is all pass.

**Comment by rizafran** [comment]
Thanks for reporting his @Vanson. It seems like you're encountering an issue similar to issue #8137 where the dev is also getting an `Undefined symbol: OBJC_CLASS$_GULAppEnvironmentUtil` error.
I'll be closing this ticket as a duplicate for now so that we can funnel discussions through the aforementioned ticket, but please re-open this issue if you have any other questions or if your issue is different from the scenario I described. Thanks.
