### ISSUE TITLE
Firebase crashlytics failed to auto upload dSYM files through XCode run script 

### ISSUE THREAD

**Issue by HazarathReddy** [firebase/firebase-ios-sdk#8273]
### [REQUIRED] Step 1: Describe your environment

- Xcode version: 12.3
- Firebase SDK version: 8.0.0
- Installation method: pod
- Firebase Component: Crashlytics

### [REQUIRED] Step 2: Describe the problem

I am trying to upload dSYM files thorough XCode runscript, this script will execute while archiving the build. 

Here is my run scripts for Firebase 

Run Script 1:

`"${PODS_ROOT}/FirebaseCrashlytics/run"`

Input Files:

`${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}`
`$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`

Run script 2 to upload dsyms:

```
if [ ! -d ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME} ]; then
    echo "Couldn't find dsym file"
    exit 1
fi

stat -x ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}

"${PODS_ROOT}/FirebaseCrashlytics/upload-symbols" -gsp "${PROJECT_DIR}/Resources/GoogleService-Info.plist" -p ios "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```

Finally run script executed and here is my output from swift console log

![Screenshot 2021-06-18 at 3 21 47 PM](https://user-images.githubusercontent.com/24653259/122548600-324f8c80-d04f-11eb-8b96-52b6a5905c26.jpg)

But dSYM files are not reflecting in Firebase crashlytics dashboard. Dashboard showing error message like **_Upload missing dSYMs to see crashes_**

Properly setting **Debug Information Format** to **DWARF with dSYM File** for all your build types.

**Comment by elenadoty** [comment]
Hi @HazarathReddy ,
A couple questions:
- Do you have bitcode enabled for your app? (If so, are the dSYMs you're uploading with the second run script the files downloaded from Apple?)
- Are you seeing missing frames for crashes in your dashboard?

**Comment by HazarathReddy** [comment]
Hi @elenadoty 

#1 => Yes, bitcode is enabled. dSYMs are fetching from local archive not from Apple
#2 -> No, I can't see crashes in dashboard until manually upload missing dSYMs

**Comment by elenadoty** [comment]
Hi @HazarathReddy ,
Thanks for the clarification. 
Unfortunately I believe what you're experiencing is expected behavior for apps with bitcode enabled. Because of the processing that Apple performs on the uploaded app, the local dSYMs no longer match the symbols for the app. Instead, Apple provides new dSYMs to download that you can then manually uploaded to Crashlytics using the run script/CLI tool. The new dSYMs can be found either in Xcode Organizer (click on the archive version you want symbols for then the download dSYM button in the right pane) or in App Store Connect (navigate to the correct build and there should be a download dSYM button in the Build Details tab).
