### ISSUE TITLE
Firebase Cloud messaging is not working when app is killed from background in iOS(Objective C)

### ISSUE THREAD

**Issue by JIBINVARGHESE912** [firebase/firebase-ios-sdk#8303]
I am using Firebase cloud messaging to show notification in my iOS app. When fired notification, my app could not able to receive the notification when app is killed in background state. But my app could able to receive notification even if app is in background or foreground. 

We are using below Firebase pod versions

- pod 'Firebase/Analytics','~> 8.2.0'
- pod 'Firebase/Messaging','~> 8.2.0'
- XCode version used:12.2
- OS Version used : 14.3
- Device Model used: iPhone 12 Pro

Payload structure used:-
```
{
   "to":"key",
   "priority":"high",
   "content_available":true,
   "data":{
      "data1":"value1",
      "data2":"value2"
    }
}
``` 
```
{
   "to":"key"",
   "priority":"high",
   "content_available":true,
   "notification":{
      "data1":"value1",
      "data2":"value2"
   }
}
```
We have tried both "data" and "notification" keys. But it is not working.

**Comment by chliangGoogle** [comment]
You are sending a background notification and due to Apple's system limitations, it will not be delivered if app is killed.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc
"If something force quits or kills the app, the system discards the held notification."

Please reopen if you have more questions.
