### ISSUE TITLE
A crash of an any application with  Firebase/Performance.

### ISSUE THREAD

**Issue by K-Be** [firebase/firebase-ios-sdk#8321]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.3
  * Firebase SDK version: 8.2.0
  * Installation method: CocoaPods
  * Firebase Component: Performance

### [REQUIRED] Step 2: Describe the problem
An application crashes on launch.

#### Steps to reproduce:

1. Clone a code from https://github.com/firebase/quickstart-ios/tree/master/performance and install pods
2. Turn on diagnostic flags for launch scheme PerformanceExample named "Malloc Scribble", "Zombie Objects": 

<img width="644" alt="Screenshot 2021-06-30 at 10 03 51" src="https://user-images.githubusercontent.com/128474/123895720-7bc2a480-d98a-11eb-943d-7fb07ec03f6d.png">

3. Launch an application named PerformanceExample.

Application will crash with a Zombie access message: 
```
#0	0x00007fff20176876 in object_setClass ()
#1	0x00007fff2042fbd2 in -[NSObject(NSObject) __dealloc_zombie] ()
#2	0x00007fff207f34d6 in -[NSOperation dealloc] ()
#3	0x00007fff2018f834 in objc_object::sidetable_release(bool, bool) ()
#4	0x000000010cc362a1 in __destroy_helper_block_e8_32s40s ()
#5	0x00007fff2007f42f in _Block_release ()
#6	0x000000010ca468d3 in __destroy_helper_block_e8_32s ()
#7	0x00007fff2007f42f in _Block_release ()
#8	0x000000010ca467f1 in __destroy_helper_block_e8_32s40s ()
#9	0x00007fff2007f42f in _Block_release ()
#10	0x000000010ca488ff in __destroy_helper_block_e8_32s40s48s ()
#11	0x00007fff2007f42f in _Block_release ()
#12	0x000000010ce2d9c8 in _dispatch_client_callout ()
#13	0x000000010ce34440 in _dispatch_lane_serial_drain ()
#14	0x000000010ce34f67 in _dispatch_lane_invoke ()
#15	0x000000010ce40de2 in _dispatch_workloop_worker_thread ()
#16	0x00007fff60c8f45d in _pthread_wqthread ()
#17	0x00007fff60c8e42f in start_wqthread ()
Enqueued from com.google.GDTCCTUploader (Thread 5) Queue : com.google.GDTCCTUploader (serial)
#0	0x000000010ce2ee19 in dispatch_group_async ()
#1	0x000000010ca57175 in __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke at /Users/andrewromanov/Documents/work/my/quickstart-ios/performance/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:221
#2	0x000000010ca558c1 in -[FBLPromise fulfill:] at /Users/andrewromanov/Documents/work/my/quickstart-ios/performance/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:90
#3	0x000000010ca5795d in __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke at /Users/andrewromanov/Documents/work/my/quickstart-ios/performance/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:268
#4	0x000000010ca57b3d in __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.67 at /Users/andrewromanov/Documents/work/my/quickstart-ios/performance/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:274
#5	0x000000010ca5724d in __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 at /Users/andrewromanov/Documents/work/my/quickstart-ios/performance/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:226
#6	0x000000010ce2c7ec in _dispatch_call_block_and_release ()
#7	0x000000010ce2d9c8 in _dispatch_client_callout ()
#8	0x000000010ce34440 in _dispatch_lane_serial_drain ()
#9	0x000000010ce34f67 in _dispatch_lane_invoke ()
#10	0x000000010ce40de2 in _dispatch_workloop_worker_thread ()
#11	0x00007fff60c8f45d in _pthread_wqthread ()
#12	0x00007fff60c8e42f in start_wqthread ()

```

You can reproduce this bug in any application with Firebase/Performance.

**Comment by paulb777** [comment]
@K-Be Thanks for the report. I can reproduce.

**Comment by arnauddorgans** [comment]
I think it's related but maybe I'm wrong, I have a crash with the same version of firebase on performance w network trace
![image](https://user-images.githubusercontent.com/10015557/123984238-c2cd8b80-d9c4-11eb-83fb-e01c1b1d8ed2.png)

**Comment by HyunjoonKo** [comment]
Same problem as yours appears in Firebase 8.3.0. (FirebasePerformance 8.3.0)

**Comment by chub-andrey** [comment]
Hi! The Cian team faced with the same crash. We have updated from 7.10.0 to 8.3.0 and caught issue. For current time we downgraded to the stable version 7.10.0, unfortunately

<img width="1271" alt="Снимок экрана 2021-07-30 в 17 16 10" src="https://user-images.githubusercontent.com/47531029/127666496-a66552ae-11a7-4ab1-a675-5dc783b8830c.png">

**Comment by paulb777** [comment]
We're not sure that the `[FPRNetworkTrace updateTraceWithCurrentSession]` crash is the same as the zombie crash being tracked by this issue. We consider the `[FPRNetworkTrace updateTraceWithCurrentSession]` crash more urgent and are investigating that one at #8495.

**Comment by maksymmalyhin** [comment]
The most probable reason of the crash is incompatibility of Firebase ISA swizzling implementation with ISA swizzling used by the Zombie Objects diagnostic. 

Technical details:
- Firebase Performance uses ISA Swizzling (changing an instance class in runtime) to collect network request metrics. [GULObjectSwizzler](https://github.com/google/GoogleUtilities/blob/main/GoogleUtilities/ISASwizzler/GULObjectSwizzler.m) is the swizzler implementation. 
- When Zombie Objects diagnostic is enabled, most likely, any object is set with a specific class instead of complete deallocation. Apparently this class is a subclass of the original object class generated with [objc_allocateClassPair()](https://developer.apple.com/documentation/objectivec/1418559-objc_allocateclasspair)
- 'GULObjectSwizzler' tries to disposes the its own generated subclasses when the swizzled object is being deallocated by calling [objc_disposeClassPair](https://developer.apple.com/documentation/objectivec/1418912-objc_disposeclasspair) in [dealloc](https://github.com/google/GoogleUtilities/blob/2e364ff22e952c3bcb202263a9a0d26e46c1b172/GoogleUtilities/ISASwizzler/GULObjectSwizzler.m#L162) method
- most likely Zombie Objects attempts to use a generated subclass with the disposed (by `GULObjectSwizzler`) parent class which cases the crash

Workaround:
- currently the only reliable workaround is to disable instrumentation in Firebase Performance with [Performance. isDataCollectionEnabled](https://firebase.google.com/docs/reference/swift/firebaseperformance/api/reference/Classes/Performance?authuser=0#isinstrumentationenabled) property when using Zombie Objects diagnostics. In this case Firebase Performance will not swizzle any objects.

**Comment by maksymmalyhin** [comment]
Possible solutions:
- don't dispose the classes generated in `GULObjectSwizzler`. With the current implementation it will mean constantly growing amount of generated subclasses. We will need to address this issue
- try to set the class of the instance to the original class on dealloc. In this case Zombie Objects implementation _should_ use the original class as a super class so GULObjectSwizzler can safely dispose its generated classes
- introduce a flag that developers can use to disable the class disposing when needed.

cc @visumickey
