### ISSUE TITLE
Auth().auth is not recognizing silent push notification when method swizzling is not enabled

### ISSUE THREAD

**Issue by filipealva** [firebase/firebase-ios-sdk#8325]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5
  * Firebase SDK version: 8.1.1
  * Installation method: `CocoaPods` (select one)
  * Firebase Component: Auth 

### [REQUIRED] Step 2: Describe the problem

I disabled method swizzling so I have to handle push notifications and phone auth implementation manually. No problems with push notifications, they work very well, but the `Auth().auth.canHandleNotification(_ userInfo: [AnyHashable: Any]) -> Bool` method is not recognizing the silent push notification that's generated from the phone auth flow. 

I get the silent push, the contents of it states that it's an phone auth push notification, but the method I mentioned above returns `false`.

See: 

![Screen Shot 2021-06-30 at 13 27 07](https://user-images.githubusercontent.com/6117280/123998414-dae2e200-d9a7-11eb-9542-b45e8ea2786e.png)

#### Steps to reproduce:

Just try to auth with phone with method swizzling disabled.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by filipealva** [comment]
### UPDATE:

It happens with Firebase 8.2.0 too. 

The SDK does recognize the notification, the issue seems to be that the `_pendingCallbacks` variable is empty so it ignores. The point is that it shouldn't ignore since there's a phone auth operation going on. 

See the screenshot:

![Screen Shot 2021-06-30 at 13 41 37](https://user-images.githubusercontent.com/6117280/123999674-277aed00-d9a9-11eb-81ef-f1f3b3252bee.png)

**Comment by chliangGoogle** [comment]
@rosalyntan I'm guessing this is an auth problem even tho I didn't know auth can handle silent notifications?

**Comment by filipealva** [comment]
@chliangGoogle in the docs it states that auth does handle this kind of silent notifications in order to support phone auth without method swizzling.

This being broke means that we can't opt out firebase's method swizzling.

Do you guys need more information for the troubleshooting?

**Comment by chliangGoogle** [comment]
Gotcha @filipealva  Thank you for your info and I think that's good for now. I'm just confirming with my teammate to see if it's an auth or swizzling issue.

**Comment by filipealva** [comment]
Is this queued for implementation already?

**Comment by rosalyntan** [comment]
Hi @filipealva -- I just tested phone auth with swizzling disabled, and it works as expected for me.

However, I did notice that if I set a breakpoint `if ([[FIRAuth auth] canHandleNotification:notification])`, then I am able to reproduce your issue (but without the breakpoint, everything works fine). Looking into the code, I believe this is happening because there is a 1 second timeout for probing whether the `AppDelegate` has forwarded the notification to Firebase Auth, after which `_pendingCallbacks` is cleared:
https://github.com/firebase/firebase-ios-sdk/blob/b08b358ca3ea1762f1ed84e8e4cc6f9b4dc3be60/FirebaseAuth/Sources/SystemService/FIRAuthNotificationManager.m#L134

When the breakpoint is placed on `if ([[FIRAuth auth] canHandleNotification:notification])`, this delays the execution of the logic in `canHandleNotification` until after the timeout, which is why `_pendingCallbacks` shows as `nil` for you.

Please try this without a breakpoint at `if ([[FIRAuth auth] canHandleNotification:notification])` and let me know if you're still seeing this issue.
