### ISSUE TITLE
App not open when tapping on FCM notification that came in Killed mode

### ISSUE THREAD

**Issue by abdallah-gaber** [firebase/firebase-ios-sdk#8345]
### The problem
I am sending notification from console to ios in killed app state and it arrives but when I tap on it to open the app it show white screen as it tries to open the app and dissappears imidiatly, this is not happening in Android and all other states working fine and this behaviour in both notification with or without payload data.

#### Steps to reproduce:

1. Go to 'firebase cloud messaging console'
2. kill the app in your ios device by swipping it up in recent view
3. send notification from the console
4. tap on the notification when it arrives

#### Expected result:

App to be opened.

**Comment by rizafran** [comment]
Hi @abdallah-gaber, it looks like your issue is related here #8303, which mentioned that the notification will not be delivered when the app is killed due to Apple's system limitations. See also this [link](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc
) for more details.

**Comment by abdallah-gaber** [comment]
Hi @rizafran 
No it's delivered successfully but not open the app on tapping on it.

**Comment by rizafran** [comment]
Thanks for clarifying, @abdallah-gaber. Could you share what SDK version you're using? Is it also happening to other devices?

**Comment by chliangGoogle** [comment]
@abdallah-gaber not opening the app can be something wrong in the launch state of your app, unlikely related to SDK issues. Can you record a video of how the app is not opening up?
