### ISSUE TITLE
FR: Make AnalyticsWithoutAdIdSupport available as direct Framework File

### ISSUE THREAD

**Issue by sudeepdunzo** [firebase/firebase-ios-sdk#8363]
### Feature proposal

* Firebase Component: Analytics (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

Currently, AnalyticsWithoutAdIdSupport is available only via Cocoadpods v7.11.0 onwards. I have verified this with the framework zip file for the latest release  8.3.0. 

WE would prefer to use pre-compiled frameworks as SPM/cocoapods significantly impacts our compile time.

**Comment by rizafran** [comment]
Thanks for reporting this, @sudeepdunzo. It seems that your issue is related to #8201. As discussed there, you may replace GoogleAppMeasurement.xcframework with the GoogleAppMeasurementWithoutAdIdSupport.xcframework as a workaround [specified in the CocoaPods podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/e/3/b/GoogleAppMeasurement/8.1.0/GoogleAppMeasurement.podspec.json#L31).

**Comment by paulb777** [comment]
Also note that the compile time concern does not apply to AnalyticsWithoutAdIdSupport since it is only packaged a binary in both CocoaPods and SPM.  

I'll close in favor of continuing to track in #8201.
