### ISSUE TITLE
Stop running code coverage tests when Carthage is updated

### ISSUE THREAD

**Issue by ryanwilson** [firebase/firebase-ios-sdk#8418]
From #8417, it triggered `pod lib lint` and code coverage tests even though it was an update to JSON artifacts. We should be excluding this directory or these files from the code coverage file list:  https://github.com/firebase/firebase-ios-sdk/blob/master/scripts/code_coverage_report/code_coverage_file_list.json

**Comment by granluo** [comment]
That is caused by a pattern matching from the midpoint of the path. Will update the pattern for better matching the dir.
'''
=============== paths of changed files ===============
abtesting: ReleaseTooling/CarthageJSON/FirebaseABTestingBinary.json is updated under the pattern, FirebaseABTesting.*
=============== paths of changed files ===============
auth: ReleaseTooling/CarthageJSON/FirebaseAuthBinary.json is updated under the pattern, FirebaseAuth.*
=============== paths of changed files ===============
database: ReleaseTooling/CarthageJSON/FirebaseDatabaseBinary.json is updated under the pattern, FirebaseDatabase.*
=============== paths of changed files ===============
dynamiclinks: ReleaseTooling/CarthageJSON/FirebaseDynamicLinksBinary.json is updated under the pattern, FirebaseDynamicLinks.*
=============== paths of changed files ===============
functions: ReleaseTooling/CarthageJSON/FirebaseFunctionsBinary.json is updated under the pattern, Functions.*
=============== paths of changed files ===============
inappmessaging: ReleaseTooling/CarthageJSON/FirebaseInAppMessagingBinary.json is updated under the pattern, FirebaseInAppMessaging.*
=============== paths of changed files ===============
remoteconfig: ReleaseTooling/CarthageJSON/FirebaseRemoteConfigBinary.json is updated under the pattern, FirebaseRemoteConfig.*
=============== paths of changed files ===============
storage: ReleaseTooling/CarthageJSON/FirebaseStorageBinary.json is updated under the pattern, FirebaseStorage.*
'''
