### ISSUE TITLE
Cannot find 'Firestore' in scope / Swift Package Manager

### ISSUE THREAD

**Issue by GetlinN** [firebase/firebase-ios-sdk#8501]
Hello! Need some help here, please. I have Firebase/Firestore dependencies installed with Swift Package Manager. Everything worked before and now I got this message "Cannot find 'Firestore' in scope". Please, help. Thank you. 

**UPDATE:** problem resolved Xcode -> File -> Swift Packages -> Reset Package Caches

[REQUIRED] Step 1: Describe your environment
Xcode version: `Version 12.5.1 (12E507)`
Firebase SDK version: 8.5.0
Installation method: `Swift Package Manager`
Firebase Component: FirebaseFirestore

[REQUIRED] Step 2: Describe the problem
"Cannot find 'Firestore' in scope"

![Screen Shot 2021-08-05 at 11 44 15 AM](https://user-images.githubusercontent.com/43629191/128404205-c920f218-54b0-4cce-8ec7-feafc36ac16c.png)
![Screen Shot 2021-08-05 at 11 44 30 AM](https://user-images.githubusercontent.com/43629191/128404231-4be43c88-ef4e-4186-b5aa-daa73f5e0b55.png)

**Comment by paulb777** [comment]
Some ideas to try: `rm -rf ~/Library/Developer/Xcode/DerivedData/` and/or resetting the Swift Packages.

**Comment by jillerhaus** [comment]
I think I might have a related issue. I also use Swift Packages and get:
![Screenshot 2021-08-07 at 11 22 00](https://user-images.githubusercontent.com/39054152/128595631-9f771620-fd75-4cd6-90ae-dfe25f2e9cdd.png)
This started happening after I cleaned my build folder. Sometimes it happens, sometimes it goes away. The App mostly compiles fine and if it does, the function encodes the order object properly and uploads it. The errors usually show before and after compilation, but go away during. The code completion shows me DocumentReference, but then it apparently doesn't exist. If I don't instantiate an empty reference, this error also goes away. But the problem is the completely inconsistent behavior.
I have completely removed firebase and reinstalled it multiple times. I have used the suggestion by paulb777. It worked in removing the errors while compiling on the simulator, but they came back, when I compiled to a physical device about 30 minutes later. 

order is from a class that conforms to Codable.
The Imports also don't seem to make a difference. It doesn't matter if I import Firebase or the individual APIs.

**Comment by paulb777** [comment]
@jillerhaus Are these errors from the Xcode UI or a build? If from the UI, you may need to do a build to update Xcode's module cache.

**Comment by jillerhaus** [comment]
@paulb777, they are in the UI, disappear for a couple of seconds during the build, then reappear after the build is complete. Sometimes, they interrupt the build. But I can solve that by building to a different device, which causes the behavior mentioned in the first sentence. After that I can build to the device on which the build failed. The behavior is very inconsistent.
I have also reset the package caches about 3 hours ago. The errors disappeared and haven't showed up again until now, but I have done this a couple of times over the past week and they reappear after a while. Don't know what causes it. So at least it's a temporary solution.

**Comment by MohammedBadr20s** [comment]
@jillerhaus I'm on an Intel mac and this Specific issue happens with me too doesn't disappear until i reset the packages caches, idk why it happens until now I'm on Firebase V8.5

**Comment by GetlinN** [comment]
UPDATE: problem resolved Xcode -> File -> Swift Packages -> Reset Package Caches
