### ISSUE TITLE
Thanks for updating! Feel free to comment here if the issue resurfaces and we'll try to help.

### ISSUE THREAD

**Issue by rahulvyas** [firebase/firebase-ios-sdk#8547]
Thanks for updating! Feel free to comment here if the issue resurfaces and we'll try to help.

_Originally posted by @morganchen12 in https://github.com/firebase/firebase-ios-sdk/issues/5280#issuecomment-608658168_

**Comment by rahulvyas** [comment]
I'm still getting the issue in XCODE 13.5 and xcode 12.4. I'm using following pods

pod 'Firebase/Crashlytics','6.27.1'
    pod 'Firebase/Analytics','6.27.1'

**Comment by looptheloop88** [comment]
Hi @rahulvyas, thanks for the report. Since the original issue post is old, it's right to file a new one. However, we need more information from you to help with troubleshooting and find the possible cause of the issue. Would you mind updating this issue thread and follow the template provided when creating an issue? Also, it would help a lot if you could share a minimal, but complete sample of a project that we can run locally to replicate the issue.

**Comment by morganchen12** [comment]
@rahulvyas please also try updating to the latest Firebase version (8.6.0).
