### ISSUE TITLE
FirebasePerformance start trace dishonest API

### ISSUE THREAD

**Issue by nandodelauni** [firebase/firebase-ios-sdk#8583]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.5 (12E262)
  * Firebase SDK version: 8.6.0
  * Installation method: `Swift Package Manager`
  * Firebase Component: Performance

#### Steps to reproduce:

I was trying to log some traces for my network code and I found a crash when tracing certain endpoints. The crash report says that logged named cannot be nil. I struggled looking at my own code until I noticed that the problem was of at the `FirebasePerformance` side. Taking a look at the code I notice that if you [call this method](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Timer/FIRTrace.m#L63) with a `String/NSString *` larger than 100 character it will crash. The problem is that the [static method signature for this method is not being honest](https://github.com/firebase/firebase-ios-sdk/blob/bdac2b87f6d6e604deae914a970a75136b3a62b5/FirebasePerformance/Sources/FPRDataUtils.m#L22) and will assert [here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebasePerformance/Sources/Timer/FIRTrace.m#L89).

Why it's not truncating the `String/NSString *` or saying that the return type for the `FPRReservableName` is `nonnull NSString *` instead of `NSString *`?

**Comment by jeremyjiang-dev** [comment]
The reason that we did not make the method `nonnull` is because this return value is nullable and we want to check the return value in other functions.
We use `assert` to inform that the trace name is invalid for debug build. If you [enabled the log message](https://firebase.google.com/docs/perf-mon/get-started-ios), you should be able to see the reason why the name is invalid, including [the trace name length being too long](https://github.com/firebase/firebase-ios-sdk/blob/bdac2b87f6d6e604deae914a970a75136b3a62b5/FirebasePerformance/Sources/FPRDataUtils.m#L37). Note that the `assert` is disabled in release build so your app will not crash if the trace name is too long.

Closing the issue for now. Please re-open if you have any other questions.
