### ISSUE TITLE
SwiftUI switched from iOS to MacOS - Firebase is failing at compile level

### ISSUE THREAD

**Issue by pradeepb28** [firebase/firebase-ios-sdk#8707]
It looks like compiler failed to compile **getCredentialWith** method.
It throws an error 
![CleanShot 2021-09-26 at 01 14 28](https://user-images.githubusercontent.com/6823101/134784275-cdf34506-3f2d-460e-8268-0fbfb98ca2bf.png)

here is my pod file
![CleanShot 2021-09-26 at 01 14 57](https://user-images.githubusercontent.com/6823101/134784291-2b591946-79a4-459a-bafd-c14b255f83c9.png)

any help is appreciated

**Comment by ryanwilson** [comment]
Thanks for the report - this is a known limitation. Can you please add a +1 or comment to the feature request for this? https://github.com/firebase/firebase-ios-sdk/issues/7127

The biggest reason it isn't included in macOS yet is because it relies on the UI delegate. We're open to community contributions as well for this. Thanks!
