### ISSUE TITLE
iOS firestore addSnapshotListener stops receiving updates for 20-30 seconds

### ISSUE THREAD

**Issue by Greygooo** [firebase/firebase-ios-sdk#8935]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.0 (13A233)
  * Firebase SDK version: 7.11.0
  * Installation method: CocoaPods
  * Firebase Component: Firestore

### [REQUIRED] Step 2: Describe the problem

We once daily create a Firestore document (~4kB) which gets updated in regular intervals (every 10 seconds) in a timeframe of 15 minutes. Our iOS clients subscribe to changes on the document using addSnapshotListener and subsequently write changes to a subcollection of the document.

This setup has been running smoothly for about a year now. Since we have experienced a significant increase in new clients (from 300 to ~1.5k), once during the 15 minutes, most of the clients won't receive snapshot updates for about 20-30 seconds. Before and after this occurrence snapshots are received as expected.

#### Steps to reproduce:

So far we haven't been able to reproduce this issue using only a handful of clients. We're still working on implementing a stress test to try to reproduce the observed behavior.

Any suggestions would be greatly appreciated.

#### Relevant Code:
```
init(subscriber: S, ref: DocumentReference) {
    self.subscriber = subscriber
    self.listener = ref.addSnapshotListener(includeMetadataChanges: true) { [weak self] snapshot, error in
        self?.receive(snapshot: snapshot, error: error)
    }
}
```

**Comment by rizafran** [comment]
Thanks for reporting, @Greygooo. Per checking, below are some reasons why the database might be slow:

- If you are making a request which reads or writes a large number of documents from a database which typically handles a small number of requests, the latencies can be high (~1s / 500 documents). When making requests to Firestore, it is recommended to follow the [500/50/5 rule](https://firebase.google.com/docs/firestore/best-practices#ramping_up_traffic).
- If you are writing fast to the same document such as updating counters, you may need to restructure the data to avoid writing to the same document too fast.
- This could be due to offline mode.

You may check our Firestore [best practices document](https://firebase.google.com/docs/firestore/best-practices) for some tips on how to improve the performance of your database. 

Additionally, it seems like you're using an old SDK version. With this, will updating to the [latest one](https://firebase.google.com/support/release-notes/ios) fix the issue?

**Comment by Greygooo** [comment]
Thank you for the quick response and the suggestions.

- We're never writing or reading a large number of documents from a single source, but rather every client reads the same document and writes a single document into a subcollection of the shared document.
- The document the clients subscribe to is only being updated once every 10 seconds.
- Furthermore the clients are definitely online, since they are able to receive data from non firestore sources.

We'll update the SDK to see if it fixes the issue.
