### ISSUE TITLE
[IOS] Firebase phone number auth - enter a valid phone number

### ISSUE THREAD

**Issue by AnhNguyen241194** [firebase/firebase-ios-sdk#8972]
I am using Firebase auth phone number in my application in Japan. With some phone numbers work very good  and I can authenticate  accounts easily, but some numbers I've got an issue : Please Enter Valid Phone Number. I know that this error is from server Firebase. Could you help me to check , what's gonna here?.

In fact , these phone numbers are valid Japan mobile numbers.

For more informations, about my environment and tools,SDK : 

Xcode 13.0 
iOS 14.0 and over 
Firebase v8.8.0

**Comment by paulb777** [comment]
Changing tag from feature request to question.

**Comment by AnhNguyen241194** [comment]
> Changing tag from feature request to question.

I changed type for this issue . Please check and help me

**Comment by rizafran** [comment]
Hi @AnhNguyen241194, first off, is it possible for you to try the following and see if you'll also get an invalid phone number error:
- Use our Firebase [Auth quickstart app](https://github.com/firebase/quickstart-ios/tree/master/authentication) and check if the issue is reproducible
- Use this [FirebaseUI Auth demo](https://fir-ui-demo-84a6c.firebaseapp.com/) and see if they'll receive an SMS code

Let me know of your findings.
