### ISSUE TITLE
Dynamic link when app is installed

### ISSUE THREAD

**Issue by yamila-fraiman** [firebase/firebase-ios-sdk#8975]
[REQUIRED] Step 1: Describe your environment
Xcode version: 13.0
Firebase SDK version: FirebaseDynamicLinks 8.8.0
Installation method: CocoaPods
Firebase Component: DynamicLinks

[REQUIRED] Step 2: Describe the problem
Dynamic links are working fine when the app is already installed but not working after installing from Appstore (opened by the dynamic link because app is not pre installed). Receiving url but handleUniversalLink callback does not contain information.

Steps to reproduce:
Uninstall the app if is installed
Open a dynamic Link and will open Appstore
Install the app (if want to debug, install from XCode instead of Appstore)
"DynamicLinks.dynamicLinks().handleUniversalLink" is not returning the url

When app is installed:
url: https://facebank.page.link/RGyFypSxuhtCiowP9
dynamicLink.url: https://facebank.com.ar?convenio=201&vendedor=384&checksum=0f4d4731121ad4d577e96af98cfbf897

When app isn't installed:
url: ar.com.findo.facebank://google/link/?deep_link_id=https%3A%2F%2Ffacebank%2Ecom%2Ear%3Fconvenio%3D201%26vendedor%3D384%26checksum%3D0f4d4731121ad4d577e96af98cfbf897&match_type=unique&utm_medium=dynamic%5Flink&request_ip_version=IP%5FV4&utm_source=firebase&match_message=Link%20is%20uniquely%20matched%20for%20this%20device%2E
dynamicLink: no content

![image](https://user-images.githubusercontent.com/71793326/142063207-ebb38558-fdd8-4dd6-82d1-bd50526c1f3d.png)
![image](https://user-images.githubusercontent.com/71793326/142063230-29690c00-8e1d-4252-b1c0-4d3588cdc4c7.png)

**Comment by Pofjf18** [comment]
I would say you need to link other firebase systems related to triage like other sites that go with it to separate triage from a lobby or dirt field

**Comment by Pofjf18** [comment]
> `attach app compiler`

**Comment by Pofjf18** [comment]
Web based or operate system is not the same as desk top or laptop or tablet or platform

**Comment by yamila-fraiman** [comment]
Hi @rizafran my dynamic link url is https://facebank.page.link/RGyFypSxuhtCiowP9

Steps:

1. Uninstall the app
2. Open https://facebank.page.link/RGyFypSxuhtCiowP9
3. It will open App Store but don't install it
3. Run the app from XCode and log handleUniversalLink callback

**Comment by rizafran** [comment]
Thanks for the info, @yamila-fraiman. I'm still unable to reproduce the issue. Per checking your logs, it seems like your URL isn't being parsed correctly. You may check the following details in order to isolate any project/app implementation issues:

- Check if your Dynamic Link domain has been configured in the Associated Domains list of the Capabilities tab of the app's Xcode project. You can check out this [guide](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app) for reference. 
- Make sure that your link used doesn’t have any error or warning in the debug view of your FDL because it might affect the behavior of your links.
- You may try enabling the [iOS self-diagnostic tool](https://firebase.google.com/docs/dynamic-links/debug#ios_self-diagnostic_tool) to see if there's any warning or errors in the logs.

If you're still having issues, please try using our [quickstart app for FDL](https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks) if you'll be able to replicate it. You may also use it as a guide to compare with your setup.

**Comment by yamila-fraiman** [comment]
Have you tried using my url? Because why is it working when the app is already installed but is not working if it isn't? It's the same dynamic link.

**Comment by yamila-fraiman** [comment]
@rizafran after debugging I have more information:

Method Line 456 - https://github.com/firebase/firebase-ios-sdk/blob/bdac2b87f6d6e604deae914a970a75136b3a62b5/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m

matchesShortLinkFormat is false because FIRDLCanParseUniversalLinkURL in FDLUtilities at line 277 receives an URL with host @"google" and not @"goo.gl"

<img width="675" alt="Captura de pantalla 2021-11-18 a las 16 44 09" src="https://user-images.githubusercontent.com/71793326/142485959-c445612c-5f5f-44a2-a1fd-dfcdde6c7d05.png">

**Comment by yamila-fraiman** [comment]
I think I found the issue. I was always using handleUniversalLink but when the app is not installed we should use DynamicLinks.dynamicLinks().dynamicLink
