### ISSUE TITLE
Binary of the project which uses Crashlytics contains information about user workspace

### ISSUE THREAD

**Issue by fbaumgart** [firebase/firebase-ios-sdk#9027]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 13.1
  * Firebase SDK version: _____
  * Installation method: `CocoaPods`
  * Firebase Component: Analytics, Crashlytics
  * Target platform(s): `iOS`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

In project I use following commands in a few files:
`import Firebase`
`import FirebaseCrashlytics`
`Crashlytics.crashlytics().record(error: error)`

When the application is archived and distributed in AppStore mode the exported binary contains unwanted strings which include sensitive information about user and app workspace (app directory on the machine, dev username).

Example string with obfuscated user data:

```
// marker for objc_retainAutoreleaseReturnValueObjective-C VersionObjective-C Image Info VersionObjective-C Image Info Section__DATA,__objc_imageinfo,regular,no_dead_stripObjective-C Garbage CollectionObjective-C Class PropertiesDwarf VersionDebug Info Versionwchar_sizebranch-target-enforcementsign-return-addresssign-return-address-allsign-return-address-with-bkeyPIC Level__hidden#123963___hidden#123738___hidden#232___hidden#233___hidden#234_Apple clang version 13.0.0 (clang-1300.0.29.3)__hidden#123964___ir_hidden#14905___ir_hidden#14906___ir_hidden#14907___hidden#412__dispatch_oncebranch_weightsFirebaseCore/FirebaseCore/Sources/Private/FIRLogger.h/Users/XYZ/ExampleFolder1/ExampleFolder2/PodsFIRLogDebugFIRLogError__ir_hidden#15454_/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.hNSClassFromString/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/objc/runtime.hobjc_lookUpClassFIRLogInfo__hidden#123965_dispatch_once
```

```
SDK VersionDwarf VersionDebug Info Versionwchar_sizebranch-target-enforcementsign-return-addresssign-return-address-allsign-return-address-with-bkeyPIC Level__hidden#124471___hidden#123738___hidden#232___hidden#233___hidden#234_-frameworkCoreFoundationApple clang version 13.0.0 (clang-1300.0.29.3)__hidden#124473___ir_hidden#14907___ir_hidden#14905___ir_hidden#14906___ir_hidden#15456___ir_hidden#15454_FirebaseCrashlytics/Crashlytics/Crashlytics/Components/FIRCLSHost.h/Users/XYZ/ExampleFolder1/ExampleFolder2/PodsFIRCLSHostGetPageSize/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/include/sys/mman.hmmapFirebaseCrashlytics/Crashlytics/Crashlytics/Helpers/FIRCLSInternalLogging.hFIRCLSSDKFileLogmprotect
```

There are around 70 results of strings like that and I'm looking for a way to make them disappear, but I'm not sure where do they come from. Do you have any solutions to this problem?

**Comment by samedson** [comment]
@fbaumgart I am wondering how you getting these strings. Are you running the `strings` terminal command on the app binary?

**Comment by fbaumgart** [comment]
@samedson yes `strings`- here is the reference to the older thread where I started debugging it which lead me to this current thread https://developer.apple.com/forums/thread/676234

**Comment by samedson** [comment]
So I ran 4 tests - as far as I can tell there isn't anything specific to Crashlytics that's causing this.

I believe those paths are debug information that are stored in the binary. For debug apps, debug information is included in the app binary so that the debugger can know what line in your code crashed / had a breakpoint set in. For archived Release apps, this information should be stripped out, regardless of whether Crashlytics is installed. As far as I know there isn't anything in Crashlytics that can modify the outputted binary of your app (besides the compiled Crashlytics code itself).

Here are my results:

App with Crashlytics -> Build for Debug -> `strings <binary> | grep Users` -> has paths
App without Crashlytics -> Build for Debug -> `strings <binary> | grep Users` -> has paths
App with Crashlytics -> Archive -> `strings <binary> | grep Users` -> NO paths
App without Crashlytics -> Archive -> `strings <binary> | grep Users` -> NO paths

Are these the same results that you get?

**Comment by fbaumgart** [comment]
@samedson I have only tested this in 'Archive' mode and I still got the strings. After I removed Firebase-related cocoapods and related code this issue disappeared.

**Comment by javiermazorra** [comment]
Hi,

@fbaumgart, did you find a solution for this issue? I'm experiencing the same...

**Comment by fbaumgart** [comment]
> Hi,
> 
> @fbaumgart, did you find a solution for this issue? I'm experiencing the same...

Hi,
@javiermazorra unfortunately not. I did not resolve this, it is still an issue for me.

**Comment by themiswang** [comment]
Close this issue because there hasn't been any activity for a few months. Please make sure to update to the latest sdk version and check if that solves the issue. This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to [open a new one](https://github.com/firebase/firebase-ios-sdk/issues/new?assignees=&labels=&template=BUG_REPORT.yml) if you still experience this problem.
