### ISSUE TITLE
Crashed: com.apple.root.default-qos.overcommit

### ISSUE THREAD

**Issue by sspogra** [firebase/firebase-ios-sdk#9302]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version:13.1
  * Firebase SDK version:8.10.0
  * Installation method: CocoaPods 
  * Firebase Component: Auth, Core, Database, Firestore, Messaging, Storage
  * Target platform(s): iOS 13.4.1

### [REQUIRED] Step 2: Describe the problem

```
Crashed: com.apple.root.default-qos.overcommit
0  FirebaseFirestore              0x72e1c -[FSTListenerRegistration remove] + 4
1  AppName                      0x685f0 DbQuery.dispose() + 4368188912 (<compiler-generated>:4368188912)
2  AppName                      0x12daf4 DataUploadManager.addUploadListener() + 4368997108 (<compiler-generated>:4368997108)
3  AppName                      0x17603c closure #1 in closure #1 in UploadDownloadTimerManager.startTimer() + 33 (UploadDownloadTimerManager.swift:33)
4  AppName                      0x201d8c closure #1 in closure #1 in RepeatingTimer.timer.getter + 4369866124 (<compiler-generated>:4369866124)
5  AppName                      0x1013f8 thunk for @escaping @callee_guaranteed () -> () + 4368815096 (<compiler-generated>:4368815096)
6  libdispatch.dylib              0x5b524 _dispatch_client_callout + 16
7  libdispatch.dylib              0x3e98 _dispatch_continuation_pop$VARIANT$mp + 412
8  libdispatch.dylib              0x14430 _dispatch_source_invoke$VARIANT$mp + 1276
9  libdispatch.dylib              0x10438 _dispatch_root_queue_drain + 376
10 libdispatch.dylib              0x10bf8 _dispatch_worker_thread2 + 124
11 libsystem_pthread.dylib        0xbb38 _pthread_wqthread + 212
12 libsystem_pthread.dylib        0xe740 start_wqthread + 8
```

#### Steps to reproduce:
We are calling the dispose() function of DbQuery class from startTimer function as shown in below code.

#### Relevant Code:

```  
var dbQuery:DbQuery? = nil

func startTimer(){
        self.stopTimer()
        DispatchQueue.global(qos: .background).async {
            self.timer = RepeatingTimer(timeInterval: TimeInterval(AppConstants.uploadTimerInterval))
            self.timer?.eventHandler = {
              dbQuery?.dispose()
            }
            self.timer?.resume()
        }
    }

class RepeatingTimer {

    let timeInterval: TimeInterval
    
    init(timeInterval: TimeInterval) {
        self.timeInterval = timeInterval
    }
    
    private lazy var timer: DispatchSourceTimer = {
        let t = DispatchSource.makeTimerSource()
        t.schedule(deadline: .now() + self.timeInterval, repeating: self.timeInterval)
        t.setEventHandler(handler: { [weak self] in
            self?.eventHandler?()
        })
        return t
    }()

    var eventHandler: (() -> Void)?

    private enum State {
        case suspended
        case resumed
    }

    private var state: State = .suspended

    deinit {
        timer.setEventHandler {}
        timer.cancel()
        /*
         If the timer is suspended, calling cancel without resuming
         triggers a crash. This is documented here https://forums.developer.apple.com/thread/15902
         */
        resume()
        eventHandler = nil
    }

    func resume() {
        if state == .resumed {
            return
        }
        state = .resumed
        timer.resume()
    }

    func suspend() {
        if state == .suspended {
            return
        }
        state = .suspended
        timer.suspend()
    }
}

class DbQuery: NSObject {
    private var firebaseListener: ListenerRegistration?
    private var realtimeQuery: DatabaseQuery?
    private var realtimeRef:DatabaseReference?
    private var realtimeEventListener: UInt?
    
    init(listener: ListenerRegistration? = nil, query: DatabaseQuery? = nil , ref:DatabaseReference? = nil, realTimelistener: UInt? = nil) {
        firebaseListener = listener
        realtimeQuery = query
        realtimeRef = ref
        realtimeEventListener = realTimelistener
    }
    
    func dispose() {
        firebaseListener?.remove()
        firebaseListener = nil
        
        if realtimeEventListener != nil{
            realtimeQuery?.removeObserver(withHandle: realtimeEventListener ?? 0)
            realtimeRef?.removeObserver(withHandle: realtimeEventListener ?? 0)
        }else{
            realtimeQuery?.removeAllObservers()
            realtimeRef?.removeAllObservers()
        }
    }
}
```

**Comment by dconeybe** [comment]
Very odd. It looks like the problem is in `QueryListenerRegistration::Remove()`:

https://github.com/firebase/firebase-ios-sdk/blob/22032b6d6aa7f0d3678d6caef55c473a5222f098/Firestore/core/src/api/query_listener_registration.cc#L40-L54

Also, the `com.apple.root.default-qos.overcommit` error generally means that the dispatch queue in question is overwhelmed with work. I'll have to investigate.

**Comment by sspogra** [comment]
Hi @dconeybe Any update regarding this issue?

**Comment by dconeybe** [comment]
Apologies, no updates. Are you able to reproduce this crash or is this just from customer crash reports?

**Comment by dconeybe** [comment]
I've been investigating and haven't made much progress.

First, the stack trace is confusing. It is showing an exception being thrown in [`-[FSTListenerRegistration remove]`](https://github.com/firebase/firebase-ios-sdk/blob/355e1d1894ecd87a63c5f0f3d4cc8e9fac655b4a/Firestore/Source/API/FIRListenerRegistration.mm#L32-L34) but there is nothing in that method that could throw an exception.

`-[FSTListenerRegistration remove]` does, however, transitively call [`FirestoreClient::RemoveListener()`](https://github.com/firebase/firebase-ios-sdk/blob/355e1d1894ecd87a63c5f0f3d4cc8e9fac655b4a/Firestore/core/src/core/firestore_client.cc#L392-L401), which in turn calls [`AsyncQueue::Enqueue()`](https://github.com/firebase/firebase-ios-sdk/blob/355e1d1894ecd87a63c5f0f3d4cc8e9fac655b4a/Firestore/core/src/util/async_queue.cc#L93-L96), which in turn calls [`ExecutorLibdispatch::Execute()`](https://github.com/firebase/firebase-ios-sdk/blob/355e1d1894ecd87a63c5f0f3d4cc8e9fac655b4a/Firestore/core/src/util/executor_libdispatch.mm#L103-L116), which in turn calls [`dispatch_async_f()`](https://developer.apple.com/documentation/dispatch/1452834-dispatch_async_f) which could, in theory, crash due to `com.apple.root.default-qos.overcommit`.

I'm not a GCD expert, but my understanding is that tasks scheduled on a GCD queue get bumped to the "overcommit" queue if all of the threads in the dispatch queue are blocked. It's kind of like an "overflow". This normally shouldn't crash, but I think it could if "thread explosion" occurred, where so many threads of the dispatch queue were blocked that it reached a limit and could not create another thread to handle the task. Obviously, I don't know what else your app is doing. Is it running any work on dispatch queues that would block (e.g. acquiring a mutex, waiting on a condition variable)?

Unfortunately, I'm not able to reproduce so I can't do much to debug other than speculate. Could you see if you can reproduce locally? Even better, could you create a small app and publish it that I can use to reproduce and investigate?

Sorry this isn't much help. But I don't think I can make any more progress by staring at the code and reading about GCD.
