### ISSUE TITLE
Crash in -[FIRComponentContainer instanceForProtocol:]

### ISSUE THREAD

**Issue by matt-wormley** [firebase/firebase-ios-sdk#9377]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.2
  * Firebase SDK version: 8.8.0
  * Installation method: Zip File
  * Firebase Component: Crashlytics
  * Target platform(s): macOS

### [REQUIRED] Step 2: Describe the problem

This issue is being reported through crashalytics from production users.

https://console.firebase.google.com/u/0/project/adobe-xd-osx/crashlytics/app/ios:com.adobe.XD/issues/52337edda6bef351da8be15e57ca594b?time=last-ninety-days&types=crash&sessionEventKey=707e85ed8abe476088fa97ef8463e835_1644907815921193446

This issue has 108 crash events affecting 98 users

```
Crashed: SpMainThread
0  libsystem_platform.dylib       0x663c _os_unfair_lock_recursive_abort + 23
1  libsystem_platform.dylib       0x1a23 _os_unfair_lock_lock_slow + 256
2  libobjc.A.dylib                0xdd77 objc_object::sidetable_retain() + 81
3  FirebaseCore                   0x88af -[FIRComponentContainer instanceForProtocol:] + 30
4  FirebaseCrashlytics            0x2aaa9 +[FIRCrashlytics crashlytics] + 106
5  Adobe XD                       0x9725a9 sparkler::SpCrashReporterMac::log(NSString*) + 109 (SpCrashReporterMac.mm:109)
...
```

In the crashlytics report I'm seeing the following interesting key:
```
crash_info_entry_0 BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_unfair_lock
```

**Comment by morganchen12** [comment]
This very suspicious line
```
2  libobjc.A.dylib                0xdd77 objc_object::sidetable_retain() + 81
```
suggests that something is going wrong in your app's runtime that may not be related to Firebase. The lock causing this crash is owned by the ObjC runtime, not by Firebase, and it's being invoked through an otherwise ordinary and thread-safe retain call. Have you been able to reproduce this crash at all?

Some notes from my cursory investigation:
- [`_os_unfair_lock_recursive_abort`](https://opensource.apple.com/source/libplatform/libplatform-125/src/os/lock.c.auto.html) will only be triggered if the lock that is attempted is contended by (probably) the same thread holding the lock, hence the message about recursive locking. It's unclear to me if this results in deadlock for a bit while the second lock-acquiring call spins or if it simply crashes immediately.
- Since `sidetable_retain()` is not reentrant, it seems impossible based on the [implementation](https://opensource.apple.com/source/objc4/objc4-706/runtime/NSObject.mm.auto.html) for this to happen.

**Comment by matt-wormley** [comment]
We have not reproduced this to my knowledge. We only know of it from crash reports.

**Comment by morganchen12** [comment]
This is beyond my knowledge of libdispatch so I won't be able to provide much further help, but I'll keep this issue open in case it is being caused by Firebase and other people start running into it.

**Comment by paulb777** [comment]
More info about the integration with `Adobe XD` might be relevant here as well.

**Comment by kavitshah8** [comment]
Fortunately, I have some more context about `Adobe XD`. We intercept all the allowed POSIX signals, log it to local file, register the default signal handler for those POSIX signals, re-raise the signal in `SpPlatformSignalHandler.cpp`.

```
Crashed: SpMainThread
0  libsystem_platform.dylib       0x663c _os_unfair_lock_recursive_abort + 23
1  libsystem_platform.dylib       0x1a23 _os_unfair_lock_lock_slow + 256
2  libobjc.A.dylib                0xdd77 objc_object::sidetable_retain() + 81
3  FirebaseCore                   0x88af -[FIRComponentContainer instanceForProtocol:] + 30
4  FirebaseCrashlytics            0x2aaa9 +[FIRCrashlytics crashlytics] + 106
5  Adobe XD                       0x9725a9 sparkler::SpCrashReporterMac::log(NSString*) + 109 (SpCrashReporterMac.mm:109)
6  Adobe XD...
7  Adobe XD...
8  Adobe XD...
9  Adobe XD...
10 Adobe XD...
11 Adobe XD...                    0x2a2bbf (anonymous namespace)::sigHandler(int) + 114 (SpPlatformSignalHandler.cpp:114)
12 libsystem_platform.dylib       0x35fd _sigtramp + 29
```

 I believe what's happening we are in the middle of a crash, logging it tries to allocate memory (maybe because we are using custom keys in firebase logging) and it crashes again.

**Comment by matt-wormley** [comment]
Kavit was able to get to the bottom of this - thanks for the help. @morganchen12 was on the right track as there was lock contention on the same tread exactly as was noted. Thanks for the help. Clearly was our defect.
