### ISSUE TITLE
[FirebaseDatabase] queryStarting returns all values

### ISSUE THREAD

**Issue by mariohahn** [firebase/firebase-ios-sdk#940]
* Xcode version: Version 9.2 (9C40b)
  * Firebase Component: 4.8.0 (Database)

#### Steps to reproduce:

The Problem is that I also get messages which are less than the current timestamp

#### Relevant Code:

``` swift

let start = Date().timeIntervalSince1970

//get messages
 Database.database().reference()
            .child("test")
            .queryOrdered(byChild: "date")
            .queryStarting(atValue: start)
            .observe(.childAdded) { [weak self] snapshot in
            
            guard let dict = snapshot.value as? [String: Any] else {
                return
            }
        }
        
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 5.0) { [weak self] in
        Database.database().reference().child(test).childByAutoId().setValue(["message": "test", "date": Date().timeIntervalSince1970])
}
```

**Comment by mariohahn** [comment]
Do you need more information, or have you already found something?

**Comment by morganchen12** [comment]
I think Sebastian just hasn't had the time to look at this issue yet.

**Comment by schmidt-sebastian** [comment]
We will try to reproduce this locally. For now, there is no need to send us additional information. Thanks for your report.

**Comment by mariohahn** [comment]
ok perfect 👍

**Comment by schmidt-sebastian** [comment]
@mariohahn Can you do us a favor and try this again with the RTDB SDK 4.10.0? We fixed a precision issue with int64 numbers (such as those returned  Date().timeIntervalSince1970) that affects queries that use persistence.

Furthermore, since we have been unable to reproduce this locally, it would help us to get your debug logs after all. To see these logs, pass "-FIRDebugEnabled" to your app on launch and add the following code to your initialization:

```
Database.setLoggingEnabled(true)
```

**Comment by morganchen12** [comment]
@mariohahn please re-open this if it's still an issue.
