### ISSUE TITLE
Update async/await code to be available for iOS 13, etc.

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#9483]
Now that it is supported for iOS 13 instead of 15 starting with Xcode 13.2.1

**Comment by ryanwilson** [comment]
This will bump our min Xcode version to Xcode 13.2.1 right?

**Comment by paulb777** [comment]
Right. 

Seems worth it for the next major release to get the broader async/await support and Xcode 13.2.1+ usage is already 63%

**Comment by ryanwilson** [comment]
I wonder if we could use `#if swift(>=5.5.2`)` to check for it and set it to 13, otherwise set it to 15. May be a bit messy but could buy us a bit more time and we don't have *that* many instances of it. 

The one caveat is 13.2.0 specifically would break I think, but if we were thinking of removing support anyways it's not a huge dela.

**Comment by ryanwilson** [comment]
Testing this out now as there are only 7 non-test instances of these declarations.

**Comment by ryanwilson** [comment]
This is fixed in #9540
