### ISSUE TITLE
Users unexpectedly logged out when opening the app after some time

### ISSUE THREAD

**Issue by sergiocampama** [firebase/firebase-ios-sdk#9869]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Xcode 13.4
  * Firebase SDK version: 9.0.0
  * Installation method: `CocoaPods`
  * Firebase Component: Auth
  * Target platform(s): `iOS`

### [REQUIRED] Step 2: Describe the problem

We've been getting user reports that after updating to an app version that included 9.0.0, they've been getting logged out after closing the app and waiting some time, resulting in a degraded experience.

#### Steps to reproduce:

Sadly this is one of those issues that can't be reliably reproduced. We believe it's related to the Keychain and prewarming mitigation fix put in place in #9622, specifically to the part that checks whether `[UIApplication isProtectedDataAvailable]` returns true. There have been reports of `isProtectedDataAvailable` not returning true after `application(_:didFinishLaunchingWithOptions:)`, such as https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466. (this also contains some reproduction instructions, like force closing the app, putting the phone to sleep, waiting 30 minutes, unlock the phone and open the app)

Reading the code change in #9622, if `isProtectedDataAvailable` is false, then it will wait for the `UIApplicationProtectedDataDidBecomeAvailable` notification, which might never arrive if `isProtectedDataAvailable` never changed to `true`. This would result in the Auth component not being up to date on user launch, which would result in our app deciding it is logged out.

#### Workaround

To work around this issue, we should be able to manually send the `UIApplicationProtectedDataDidBecomeAvailable` in `application(_:didFinishLaunchingWithOptions:)` at some point after initializing the Auth component, but it might be tricky to figure out the right place if Auth is abstracted into other app-specific components.

Should there be an option to deactivate this automatic mitigation/checks in light of `isProtectedDataAvailable` not working as expected in all cases? I'll leave that up to the Firebase team, but as it stands, 9.0.0 introduces a new authentication issue for us that wasn't there before (at least in our case), and for now, we'll just stay in 8.15.0 which does not contain this change.

**Comment by rosalyntan** [comment]
Hi @sergiocampama, thanks for reporting this!

This definitely seems weird, as #9622 was intended to fix the issue described in the article you [linked]( https://sourcediving.com/solving-mysterious-logout-issues-on-ios-15-8b818c089466), where keychain access fails due to protected data not yet being available in `didFinishLaunchingWithOptions`. It seems like for your case, `isProtectedDataAvailable` is returning false even when protected data is in fact available.

To help with debugging, what are the iOS versions of the users you have that are experiencing this?

**Comment by sergiocampama** [comment]
I was finally able to reproduce this in iOS 15.5, following those same steps:

1. Open app
2. Log in
3. Force close the app
4. Put phone into sleep
5. Wait 30 min
6. Unlock phone
7. Open app

This does seem related to prewarming, which can also be random and dependent on the usage patterns of the app, so not sure if it'll reproduce as easily in other phones.

**Comment by rosalyntan** [comment]
Hi @sergiocampama, two follow-up questions to help with debugging:

1. Do you obtain the current user via the `AuthStateDidChangeListener` or the `User#getIDToken` API?
2. Does your app use the `UIScene` lifecycle?

**Comment by rosalyntan** [comment]
Thanks for the response @sergiocampama! Just want to confirm one more thing -- is your `FirebaseApp.configure()` call also in `didFinishLaunchingWithOptions`?

For context, I believe the prewarming issues in #8695 were caused by the undocumented behavior of `didFinishLaunchingWithOptions` being called as part of the [prewarming sequence](https://developer.apple.com/documentation/uikit/app_and_environment/responding_to_the_launch_of_your_app/about_the_app_launch_sequence?language=objc#3894431) (before the device is unlocked) for [apps that support scenes](https://developer.apple.com/forums/thread/696539). However, if your app does not support scenes, then `didFinishLaunchingWithOptions`, should not be called during prewarming sequence, so it looks like something else might be going on.

**Comment by sergiocampama** [comment]
Yes, `FirebaseApp.configure()` is called before `currentUser` (not directly in AppDelegate, but in the same stack as `didFinishLaunchingWithOptions`, i.e. not inside a callback invoked later in a different thread/stacktrace)

**Comment by matthewmoss** [comment]
Seeing the same issue here – we saw this issue very infrequently before Firebase 9.0.0. Since updating to 9.0.0 a few days ago, we've had multiple tester reporting the sign out issue. Seems like something broke here. I am running 15.4.1 and just hit the issue myself.

**Comment by sergiocampama** [comment]
Thanks @rosalyntan! Any idea on which version this might land in?

**Comment by rosalyntan** [comment]
No problem -- it should be included in `v9.2.0`.

**Comment by Claes34** [comment]
Hello @sergiocampama, we faced a lot of logout issues with v9.0. Our app wakes up with significant locations even if the phone is locked, the keychain being probably inaccessible at this moment, making `Auth.auth().currentUser` nil when opening the app. We downgraded to 8.15 but planning on updating to 9.2.0 soon. Did this version solve the logout issue for you ? Thanks in advance.
