### ISSUE TITLE
Firebase Messaging giving error when I import 'AEPCore' or import AEPAnalytics, AEPUserProfile, AEPIdentity, AEPLifecycle , AEPSignal , AEPServices , ACPCore , i.e any of the adobe service.

### ISSUE THREAD

**Issue by SHIVIVIJ** [firebase/firebase-ios-sdk#9976]
#9975 FirebaseMessaging
 

  * Xcode version: 13.3.1
  * Firebase SDK version: Latest
  * Installation method: CocoaPods 
  * Firebase Component: Messaging, 
  * Target platform(s): iOS 

### [REQUIRED] Step 2: Describe the problem
Firebase messaging feature gives error when I import Adobe Files. 
#### Steps to reproduce:

What happened? How can we make the problem occur?
I added 'import AEPCore' and other adobe classes in AppDelegate and Firebase Messaging started giving error. 
Why is firebase code getting effected by any other class ? 

// to reproduce the problem
Complete Firebase messaging code and then build the app. 
Further add these pods and try to import these in App Delegate file . 
import AEPAnalytics
import AEPUserProfile
import AEPIdentity
import AEPLifecycle
import AEPSignal
import AEPServices
import ACPCore
Then you get this error. 

![Screenshot 2022-07-01 at 4 00 35 PM](https://user-images.githubusercontent.com/108523267/176877877-757b4e16-93df-4aa8-a029-e4192e2a6d9c.png)

**Comment by rizafran** [comment]
Thanks for reporting, @SHIVIVIJ. I was able to reproduce the issue, and it seems like there's a conflict with the `MessagingDelegate` since Firebase also use this protocol. With this, could you try using instead the `MessagingDelegate` of Firebase SDK (you could try either of the suggestions below):
- Conform to the protocol in class (see this [link](https://stackoverflow.com/a/56022149) for sample)
- If you're extending the `AppDelegate`, try `extension AppDelegate: FirebaseMessaging.MessagingDelegate {}` instead of `extension AppDelegate: MessagingDelegate {}`

**Comment by SHIVIVIJ** [comment]
> Thanks for reporting, @SHIVIVIJ. I was able to reproduce the issue, and it seems like there's a conflict with the `MessagingDelegate` since Firebase also use this protocol. With this, could you try using instead the `MessagingDelegate` of Firebase SDK (you could try either of the suggestions below):
> 
> * Conform to the protocol in class (see this [link](https://stackoverflow.com/a/56022149) for sample)
> * If you're extending the `AppDelegate`, try `extension AppDelegate: FirebaseMessaging.MessagingDelegate {}` instead of `extension AppDelegate: MessagingDelegate {}`

Thanks @rizafran  , It worked with second point.
