### ISSUE TITLE
could not build objective-c module 'firebase' - Xcode 14 beta 2, iOS deployment-16.0

### ISSUE THREAD

**Issue by cadjenovic2020** [firebase/firebase-ios-sdk#9981]
I can build and run the app successfully in iOS 15.5 on my real iphone but when I try to build the project in a simulator for iOS 16, it gets errors.

**Comment by rizafran** [comment]
Thanks for reporting, @cadjenovic2020. Please provide the information needed from the issue template so we could try to reproduce and investigate the issue.

**Comment by cadjenovic2020** [comment]
I have installed firebase cocoapods
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/DynamicLinks'

deployment: 16.0
device: simulator (iphone 13 pro max)
Take a look at the screenshot
![image](https://user-images.githubusercontent.com/60456014/177240557-54d4b612-b6a1-49f7-bd5c-e9223b44ae1b.png)

build failed with the following errors:
Command SwiftCompile failed with a nonzerro exti code.
Could not build Objective-C module 'Firebase' (in AppDelegate file)
'FirebaseCore/FirebaseCore.h' file not found

I tried this way but nothing helped.
https://developer.apple.com/forums/thread/128535

I hope the information above helps you track the issue on your side.

**Comment by rizafran** [comment]
Thanks for sharing the info, @cadjenovic2020. I was able to reproduce the issue. Note that starting version 9, the `Firebase` pod is deprecated. With this, you need to import `FirebaseCore` instead of `Firebase`. Also, you need to reference product pods directly in your `Podfile`. You may check this [docs](https://firebase.google.com/docs/ios/setup#initialize-firebase) for more details.

Let me know how it goes.
